### ISSUE TITLE
[Resolved]  MacOS CondaHTTPError: HTTP 000 CONNECTION FAILED

### ISSUE THREAD

**Issue by baileythegreen** [conda/conda#10291]
## Current Behavior
In MacOS 10.13.6, using miniconda3, version 4.8.5, `conda` is unable to search for or install packages. This happens in my base environment, and in project environments that I have created. The information I have provided below is for the base environment.

Since yesterday I have been seeing problems with both `conda` and `pip` referencing my SSL module. I have tried installing an SSL module several ways. Nothing that uses `conda` or `pip` will currently work. I have managed to install one using `brew install openssl`, but this does not resolve either issue, or change the error messages I get in any way.

```
$ ls -lh /Users/baileythegreen/Software/miniconda3/bin/openssl
-rwxrwxr-x  1 Bailey  staff  641K Oct 14 23:42 /Users/baileythegreen/Software/miniconda3/bin/openssl
```

### Steps to Reproduce
I am getting the same error message no matter what I try to search for/install with conda.

```
$ conda search tree
Loading channels: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/osx-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/conda-forge/osx-64'
```

## Expected Behavior

When I try to search for a package, I should either see a list of locations in my channel list from which I could install it, or be told that it can't be found in any of the installed channels. 

## Environment Information
<details>
<summary><code>conda info</code></summary>

```
$ conda info
     active environment : base
    active env location : /Users/baileythegreen/Software/miniconda3
            shell level : 1
       user config file : /Users/baileythegreen/.condarc
 populated config files : /Users/baileythegreen/.condarc
          conda version : 4.8.5
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __osx=10.13.6
       base environment : /Users/baileythegreen/Software/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/baileythegreen/Software/miniconda3/pkgs
                          /Users/baileythegreen/.conda/pkgs
       envs directories : /Users/baileythegreen/Software/miniconda3/envs
                          /Users/baileythegreen/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.5 requests/2.23.0 CPython/3.8.3 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config --show-sources</code></summary>

(I have set `ssl_verify` to False in an attempt to circumvent this issue. The error occurs whether it is True or False. I have also been seeing issues with SSL errors using `pip`.)

```
$ conda config --show-sources
==> /Users/baileythegreen/.condarc <==
env_prompt: ({name}) 
ssl_verify: False
channels:
  - conda-forge
  - defaults
```

</details>

<details>
<summary><code>conda list --show-channel-urls</code></summary>

```
$ conda list --show-channel-urls
# packages in environment at /Users/baileythegreen/Software/miniconda3:
#
# Name                    Version                   Build  Channel
arrow                     0.17.0                   pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h5347e94_2    conda-forge
cffi                      1.14.0           py38hc512035_1    defaults
chardet                   3.0.4                 py38_1003    defaults
click                     7.1.2                    pypi_0    pypi
conda                     4.8.5            py38h5347e94_2    conda-forge
conda-package-handling    1.6.1            py38h1de35cc_0    defaults
cookiecutter              1.7.2                    pypi_0    pypi
cryptography              2.9.2            py38ha12b0ac_0    defaults
idna                      2.9                        py_1    defaults
jinja2                    2.11.2                   pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
joblib                    0.17.0                     py_0    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcxx                    10.0.0                        1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.3                  h0a44026_1    defaults
libgfortran               4.0.0               h50e675f_12    conda-forge
libgfortran4              7.5.0               h50e675f_12    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1    defaults
numpy                     1.19.1           py38h8ccc501_2    conda-forge
openssl                   1.1.1g               h1de35cc_1    intel
pip                       20.0.2                   py38_3    defaults
poyo                      0.5.0                    pypi_0    pypi
pycosat                   0.6.3            py38h1de35cc_1    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py38_0    defaults
pysocks                   1.7.1                    py38_0    defaults
python                    3.8.3                h26836e1_1    defaults
python-crfsuite           0.9.7            py38ha0d09dd_0    conda-forge
python-slugify            4.0.1                    pypi_0    pypi
python.app                2                       py38_10    defaults
python_abi                3.8                      1_cp38    conda-forge
pyyaml                    5.1.2            py38h0b31af3_0    conda-forge
readline                  8.0                  h1de35cc_0    defaults
requests                  2.23.0                   py38_0    defaults
ruamel_yaml               0.15.87          py38h1de35cc_0    defaults
scikit-learn              0.22.1           py38h3dc85bc_1    conda-forge
scipy                     1.4.1            py38h38b60c6_3    conda-forge
setuptools                46.4.0                   py38_0    defaults
six                       1.14.0                   py38_0    defaults
sklearn-crfsuite          0.3.6              pyh9f0ad1d_0    conda-forge
sqlite                    3.31.1               h5c1f38d_1    defaults
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
text-unidecode            1.3                      pypi_0    pypi
tk                        8.6.8                ha441bb4_0    defaults
tqdm                      4.46.0                     py_0    defaults
urllib3                   1.25.8                   py38_0    defaults
wheel                     0.34.2                   py38_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

</details>

**Comment by baileythegreen** [comment]
### Sharing the solution that seems to have finally solved this for me:

After trying many, many things (and technically before I posted the issue) this resolved it for the OpenSSL I installed through Homebrew:

I created the symbolic links described here (but for the correct version of OpenSSL):
https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7

Then ran this line to copy package config files: 
https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7#gistcomment-3355140

Both `pip` and `conda` now seem happy.

**Comment by chenghlee** [comment]
Out of curiosity, what's the output of running `env | grep -ci library_path` in your shell?

**Comment by baileythegreen** [comment]
I don't have any `library_path` variables set, so it is 0.

(Note, there is no particular reason they aren't set, either.)

**Comment by kenodegard** [comment]
Closing since it was apparently resolved by updating the available OpenSSL.

**Comment by Egosis** [comment]
Same issue here, the SSL Update Reinstall and Link did not solve my issue :(
