### ISSUE TITLE
conda install leaves .tmp files when the install fails

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#1319]
When you perform a conda install and for whatever reason the install fails (md5 hash failure, etc) the .tmp files remain in the file system.  

using conda clean, with any of its options, does not get rid of them as users might expect

can we add a new option to conda clean or have failed installs cleanup after themselves immediately?

![conda md5 tmp files](https://cloud.githubusercontent.com/assets/11463175/7483330/b04aaf42-f343-11e4-8e64-1b77a0a18a37.png)

**Comment by asmeurer** [comment]
These are coming from `try_hard_link`. They should be removed automatically from the function, so I'm guessing either conda crashed, or, more likely, it somehow doesn't have permissions to remove the files (even though it is able to create them). Do you know if conda ever gave any errors about being unable to remove those files?

**Comment by jmsy00** [comment]
Is there any progress on this?  There are no errors that conda had issues trying to remove the .tmp files.  This happens when you choose 'n' at the install prompt (not just "failed" installs, technically the same situation I guess.)

**Comment by asmeurer** [comment]
@jmsy00 the `y/n/f` stuff is completely gone in the latest version of conda. Can you `conda update conda` and report if you still see this issue?

**Comment by jmsy00** [comment]
I will give that a try, but I want to note that .tmp files litter cloned envs also even when the original environment did not have any latent .tmp files.

**Comment by jmsy00** [comment]
also, I am at the most recent conda:

F:\>conda update conda
Fetching package metadata: ..
# All requested packages already installed.
# packages in environment at ///
#
conda                     3.17.0                   py27_0

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1618 which I just merged may end up fixing this.

**Comment by jmsy00** [comment]
This is still happening on windows, currently using conda version 4.0.9 and is causing issues when trying to clone an environment.

**Comment by kalefranz** [comment]
There are a series of commits in 4.2.0 that should resolve this issue.  @JeremyEnns, please re-open if that's not the case.

To get 4.2.0:

    conda config --add channels conda-canary
    conda update conda
