### ISSUE TITLE
Better support for conda envs accessed by multiple users

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1329]
This is taken straight from the Anaconda mailing list from an individual Piyanat Boom.  Below is my summary of the issue they are facing with using conda in a multi-user environment.  If what they want should currently be possible then we should speak with them further to debug why it isn't working.  If it isn't currently possible then in the short term I'd say we need to provide better warning/error messages when not-the-env-owner tries to modify the env, and in the medium/longer term figure out if we can support this interaction/usage model.

What you are trying to do is very reasonable and, if possible, should be supported by Anaconda and conda.  My best guess as to what is happening is that conda is attempting to hard-link the packages into the default "envs" directory and that this operation is not possible because the underlying packages are owned by someone _other_ than the user creating the new environment.

I think a summary of what you want to achieve is:
1. Install Anaconda with a root env ownership of boss:team and permissions of u+rwX, g+rX, o-rwX.  This means: readable and writable by "boss", only readable by "team", and no access for anyone else.
2. The package cache directory "pkgs" and the environments directory "envs" will also have ownership of boss:team, with permissions of u+rwX, g+rwX, o-rwX.  This means that _both_ "boss" and "team" can add/remove packages from the package cache, create custom envs, and modify _any_ environment.
3. If "minion_steve" creates a new env "foo" in the standard location, then Steve should be able to use it afterwards (ie. it should be created in the right place, and be fully usable by the person who created it).
4. If "minion_judy" wants to use "foo" she should be able to, including being able to update "foo" or add new packages to it.  Any modifications will not stop Steve from using "foo".
5. New packages installed into "foo" by Steve or Judy go into the "standard" package cache available to all team members so packages aren't installed multiple times.

If you can confirm that this description broadly matches your use case, then we can evaluate what is currently preventing this from working and propose a work-around or discuss a possible fix for an upcoming conda release.

**Comment by asmeurer** [comment]
Also take a look at http://conda.pydata.org/docs/troubleshooting.html?highlight=umask#issue-permission-denied-errors-during-install

**Comment by ijstokes** [comment]
@asmeurer I'm not sure if that conda.pydata.org link you provided is supposed to tell me "this should just work, and if it doesn't then it is just a umask issue when envs are created".  Or is it that the use case I describe (that the particular user was experiencing) is not really supported by conda?

I feel like there are 3 things here that need to be considered:

1. What can this person do *now* given they are using conda in a group setting and the members of the group are experiencing this problem?  What (if anything) will allow them to use conda the way they would like?

2. What can a similar group of people do in today if they want to prep their operational system *in advance* so conda will play nicely with "shared read/write environments" they are about to create?  It sounds like the answer might be "umask", but maybe not, or maybe that is not enough.

3. Are there features we could add to conda that would allow users to configure it so things like "default group" and "umask" could be set automatically on each conda operation that writes to disk, in order to make "group" use of environments work better?

**Comment by ijstokes** [comment]
@asmeurer and @ilanschnell: we now have a Wakari Enterprise customer who is suffering, we believe, from exactly this problem.  We could really do with 20 minutes of your time to discuss the options that exist right now and also to understand if there is anything that could be done to change the way either conda works or the way Wakari Enterprise works with conda as it stands to avoid this problem.

**Comment by ijstokes** [comment]
We are taking a top-down approach to debugging this as we have reproduced it on a trial system.  We have not yet isolated the exact commands which are creating the problems with shared environments, however we are ending up with files in the root environment that have mixed ownership:

```
lrwxrwxrwx   1 root      root             19 May 13 16:17 /opt/wakari/anaconda/lib/libpython2.7.so -> libpython2.7.so.1.0*
-rwxrwx--x+  3 johnsmith johnsmith   1175940 Jan  3  2014 /opt/wakari/anaconda/lib/libreadline.a*
lrwxrwxrwx   1 root      root             16 May  1 15:07 /opt/wakari/anaconda/lib/libreadline.so -> libreadline.so.6*
lrwxrwxrwx   1 root      root             18 May  1 15:07 /opt/wakari/anaconda/lib/libreadline.so.6 -> libreadline.so.6.2*
-rwxrwx--x+  5 johnsmith johnsmith   4424066 Mar 23 16:36 /opt/wakari/anaconda/lib/libsqlite3.a*
lrwxrwxrwx   2 wakari    wakari           19 Apr 14 12:34 /opt/wakari/anaconda/lib/libsqlite3.so -> libsqlite3.so.0.8.6*
-rwxrwx--x+  5 johnsmith johnsmith   3168602 Mar 23 16:36 /opt/wakari/anaconda/lib/libsqlite3.so.0.8.6*
-rwxrwx--x+  5 johnsmith johnsmith    748682 Mar 11 12:21 /opt/wakari/anaconda/lib/libssl.a*
lrwxrwxrwx   2 wakari    wakari           15 Apr 14 12:34 /opt/wakari/anaconda/lib/libssl.so -> libssl.so.1.0.0*
-rwxrwx--x+  5 johnsmith johnsmith    483420 Mar 11 12:21 /opt/wakari/anaconda/lib/libssl.so.1.0.0*
lrwxrwxrwx   1 root      root             19 Apr 24 14:00 /opt/wakari/anaconda/lib/libstdc++.so -> libstdc++.so.6.0.19*
lrwxrwxrwx   1 root      root             19 Apr 24 14:00 /opt/wakari/anaconda/lib/libstdc++.so.6 -> libstdc++.so.6.0.19*
-rwxrwx--x+  3 johnsmith johnsmith   6674362 Apr  1 16:10 /opt/wakari/anaconda/lib/libstdc++.so.6.0.19*
```

In particular notice that a bunch of those `johnsmith` files are not world readable.  One answer is "don't do that", but this then comes back to "does conda support environments that are read/write accessible by groups of users"?  Also, we can't right now figure out *how* `johnsmith` managed to write files into that location -- one hunch is that it has something to do with environments, linking, and differences of permissions on user environments vs. the "root" env.  The directories where those `johnsmith` files exist are **NOT** writable by `johnsmith`:

```
drwxr-xr-x   15 wakari    wakari         4096 May 13 16:50 /opt/wakari/anaconda/
drwxr-xr-x   14 wakari    wakari        16384 May 13 16:17 /opt/wakari/anaconda/lib/
```

so the mystery deepens!

**Comment by ijstokes** [comment]
In a custom user environment `testnb` the user `johnsmith` did a `conda update seaborn` which resulted in an update of Python to 2.7.10.  Looking at this env I see:

```
# ldd /projects/johnsmith/TestNotebook/envs/testnb/bin/python
	linux-vdso.so.1 =>  (0x00007fff4cbff000)
	libpython2.7.so.1.0 => /projects/johnsmith/TestNotebook/envs/testnb/bin/../lib/libpython2.7.so.1.0 (0x00007eff05a7a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007eff05854000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007eff05650000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007eff0544d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007eff051c8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007eff04e34000)
	/lib64/ld-linux-x86-64.so.2 (0x00007eff05e5e000)
```

This is the only place I can think of where `johnsmith` has modified a user environment.

**Comment by ijstokes** [comment]
@csoja is there any chance this issue could get some more attention?  I know we organized a phone conference to discuss it several weeks ago, but I'm not clear on what the outcomes were from that:  documentation of what is and isn't possible; processes that will make some limited version of this work; development effort that will make future versions of conda play more nicely in such a setting.

**Comment by ijstokes** [comment]
@stephenakearns: this is high priority for us to be able to do multi-user "projects" well in Anaconda Enterprise. @csoja, another ping on this issue, and perhaps @teoliphant  and @pzwang also want to weigh in on the priority of this issue.

I've just stepped on this land-mine again in another context with #1733.

**Comment by ijstokes** [comment]
Stepped on that landmine again. 30-60 minutes of my life **ZAP** gone like that.

```bash
wakari@olympic ~ $ sudo -u wakari $CONDA_ROOT_ENV/bin/conda update conda
Fetching package metadata: ......
Solving package specifications: ................
Package plan for installation in environment /opt/wakari/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2d             |                0         3.2 MB
    python-2.7.10              |                2        12.0 MB
    conda-env-2.4.4            |           py27_0          24 KB
    requests-2.8.1             |           py27_0         603 KB
    setuptools-18.4            |           py27_0         342 KB
    conda-3.18.3               |           py27_0         175 KB
    ------------------------------------------------------------
                                           Total:        16.2 MB

The following packages will be UPDATED:

    conda:      3.18.1-py27_0 --> 3.18.3-py27_0
    conda-env:  2.4.2-py27_0  --> 2.4.4-py27_0 
    openssl:    1.0.1k-1      --> 1.0.2d-0     
    python:     2.7.10-1      --> 2.7.10-2     
    requests:   2.8.0-py27_0  --> 2.8.1-py27_0 
    setuptools: 18.3.2-py27_0 --> 18.4-py27_0  

Proceed ([y]/n)? y

Fetching packages ...
openssl-1.0.2d 100% |#########################################################################################| Time: 0:00:00  15.35 MB/s
python-2.7.10- 100% |#########################################################################################| Time: 0:00:00  21.69 MB/s
conda-env-2.4. 100% |#########################################################################################| Time: 0:00:00   3.10 MB/s
requests-2.8.1 100% |#########################################################################################| Time: 0:00:00   8.23 MB/s
setuptools-18. 100% |#########################################################################################| Time: 0:00:00   3.94 MB/s
conda-3.18.3-p 100% |#########################################################################################| Time: 0:00:00   4.15 MB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|############################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                      |  16%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/miniconda/bin/conda", line 5, in <module>
    
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 427, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/install.py", line 611, in link
    _link(src, dst, lt)
  File "/opt/wakari/miniconda/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/opt/wakari/miniconda/lib/python2.7/shutil.py", line 130, in copy2
  File "/opt/wakari/miniconda/lib/python2.7/shutil.py", line 83, in copyfile
IOError: [Errno 13] Permission denied: '/opt/wakari/miniconda/lib/python2.7/config/Makefile'
```

Ooops, meant to do that as `root` instead of as the `wakari` user, switch and try again:

```bash
[root@olympic ~]# sudo -u wakari $CONDA_ROOT_ENV/bin/conda update conda
sudo: /opt/wakari/miniconda/bin/conda: command not found

[root@olympic ~]# which conda
/usr/bin/which: no conda in (/opt/wakari/wakari-server/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
```

**Comment by ijstokes** [comment]
Comment for internal and external audiences: Anaconda "free thing you download" is targeted for individual use, and optimized around that.  There are many complexities involved in addressing deplopyments of "Anaconda thing-you-download" in a multi-user environment and we may only implement the necessary capabilities in our commercial Anaconda Enterprise product.

**Comment by kalefranz** [comment]
I used to experience this exact same issue.  And I complained about it last week with Travis in the room.  Although I didn't understand the root cause.  After reading through these issues I think I might.

I've since done some more poking around, and here's what *does* work.  If you expect conda to be a system level package manager like yum or apt-get, you have to treat it like one from the beginning.  That is, install it as `root` and always mutate system state as `root`.  In fact, an install with `/bin/bash Miniconda-latest-Linux-x86_64.sh -bfp /usr/local` is working great so far.

What conda doesn't do is fall back gracefully to a user-writable location, especially for interacting with conda envs, when it can't write to the default install location.  If I install conda at `/usr/local` as root, and then as my own user try to create an env in my project directory, any type of caching and stuff should just happen at `~/.conda/pkgs`, etc.

**Comment by bkreider** [comment]
> What conda doesn't do is fall back gracefully to a user-writable location, especially for interacting with conda envs, when it can't write to the default install location. If I install conda at /usr/local as root, and then as my own user try to create an env in my project directory, any type of caching and stuff should just happen at ~/.conda/pkgs, etc.

Doesn't that happen?  It is supposed to happen.  Maybe your .condarc is disallowing it?  That's where the fallback location is defined.  If you can't write to $PREFIX_ROOT, it should fall back to ~/.conda/envs or ~/envs.

**Comment by QCaudron** [comment]
Just throwing in my two cents. I'd love a multi-user conda setup similar to that described above :

- installed in a root location
- users are able to create environments and install packages there
- separate package versions are kept in different environments, but for the default package version, it should go in the standard package dir

@ijstokes has highlighted several pitfalls that make this difficult. I'm sorry to see mods things might only go into Anaconda Enterprise, but it's understandable - it would still be great to have something like this work well, even at cost.

**Comment by thoth291** [comment]
More example of multi-user setup which we currently use.
1. admin installs anaconda into admin-specific location: writable only by admin, but readable by everyone.
2. Users using CONDA_ENVS_PATH to point to the place for new personal environments
3. Once user's environment is mature (some packages are well tested) - admin graduates it content into existing "root" environment or creates new writable only by admin environment so that other users could take advantage of it.

It's crucially important that admin don't set CONDA_ENVS_PATH so he has access only to the "root" environment and always installs into it only.
We also made CONDA_ENVS_PATH specific to each user - so they don't share environments by default.

Just a reminder that "cp" don't support propagation of ACLs on NFS and this is what one would possibly use in real multi-user environment.

In addition to that imagine that user A generates .pyc or other temporary cache file (like numba does) in "root" environment then there are high probabilities that user B will not be able to regenerate that file (umask 2 is not really helpful - again thanks goes to NFS).

So please be careful when you implement this.

**Comment by ijstokes** [comment]
Snatched from the Conda mailing list (2016-09-29) by @pelson :

> I have been developing the tooling to deploy centrally managed environments for some time, and have arrived at a solution that has scaled really well for several hundred workstations as well as an extremely large HPC facility. Importantly, it has allowed us to use the normal git workflow for anybody in our organisation to propose changes and through various CI hooks, much of the deployment is automated.

> Whilst I haven't fully written it up yet, I do have a draft document that will give some context and an idea of what route I took: https://rawgit.com/pelson/conda-rpms/master/tmp_overview_docs/scitools-env-workflow.html.

> We do not currently expose the ability to create custom environments through concern that there will be a huge amount of duplication and a general sense that the environments would go stale, however we are considering exposing a temporary environment concept ala conda-execute (https://github.com/pelson/conda-execute).

> I will re-post here when this document is replaced by something with a little more detail.

> Hope that's helpful,

**Comment by ijstokes** [comment]
@damianavila has a bunch to contribute on this topic based on experience with 4.2 in a multi-user environment.  I know he is planning on doing that, but when this topic gets reviewed I wanted to make sure those issues are incorporated.

**Comment by timothymillar** [comment]
@ijstokes thank you for documenting these issues, it's very helpful. I hope this is a suitable place to describe another multi-user setup.

At our institute we are trying to provide a multi-user Anaconda installation to give (a handful of advanced) users flexible access to scipy an related libraries. We are trying to avoid users running environments in their home folders in an effort to enhance transparency and reproducability.

Our current setup involves a root environment controlled by the admin, and a root condarc file that uses `envs_dirs:` to specify a shared workspace for environments. This would also make it easy to copy/clone other users environments and allow multiple users to connect to the same environment (with appropriate cation). We also have a jupyterhub instance that users can connect their environments to via a kernelspec.

This set up was working well until I noticed that several environments had broken/missing packages that went undetected because [issue 2437](https://github.com/conda/conda/issues/2437). I'm investigating upgrading conda from 4.0.5 to 4.2.x to avoid the silently failing hard-links, but the underlying permissions issues still persist. 

I'm curious if enforcing group read/write access (at the file system level) to the shared .pkgs directory will fix the permissions issues and/or result in other issues?

One more thing:
> Anaconda "free thing you download" is targeted for individual use, and optimized around that. There are many complexities involved in addressing deplopyments of "Anaconda thing-you-download" in a multi-user environment and we may only implement the necessary capabilities in our commercial Anaconda Enterprise product.

If multi-user environments are not going to be supported outside of enterprise, it would be very helpful to make this clear in the documentation for a [centralized installation](http://conda.pydata.org/docs/install/central.html). It was this documentation that lead me down the road of a shared installation.

Thanks, Tim.

**Comment by thoth291** [comment]
@timothymillar, depending on the file system you're using, I'm afraid that enforcing group read/write access might not be enough due to the fact that ACLs are not propagating appropriately.

In our case that was the reason why we moved from centralized shared multiuser setup to centralized private multiuser setup (as I described in my [post above](https://github.com/conda/conda/issues/1329#issuecomment-237985765)).

**Comment by kalefranz** [comment]
Full multi-user support is being bumped to conda 4.4, but it *will* be implemented in 4.4 which will be released within 2016.

**Comment by mforbes** [comment]
@kalefranz Any eta on multi-user support.  I have a system I would like to use this on, but and not sure if I should wait, or hack a fix in the meantime.  Thanks.

**Comment by csoja** [comment]
@mforbes conda v4.3.4 that was released to repo.continuum.io on Friday included multi-user support. (conda changelog:  https://github.com/conda/conda/blob/master/CHANGELOG.md) Any feedback is greatly appreciated!

**Comment by alexbarrera** [comment]
@csoja I was giving it a try to the multi-user feature in the newly released conda, but I'm running into the same permissions issue that I encountered before (apparently, every user needs write permissions to conda root dir). 
Maybe is too much to ask, but would you mind to state what we can expect from this new full multi-user support and a brief recipe to how to setup such a system? 
Thanks so much for all the hard work!!

**Comment by kalefranz** [comment]
@alexbarrera With 4.3, any further hiccups with permissions issues are easy to fix. If you run into one, file an issue with your terminal output, the commands you ran, and a bit of description on how to reproduce what you're seeing, and I'll do my best to quickly get a fix into a 4.3.x patch release.

**Comment by thoth291** [comment]
@alexbarrera have you tried the multi-user setup described here: https://github.com/conda/conda/issues/1329#issuecomment-237985765?
I have no time to test multi-user now but will try to do one before AnacondaCon17.

**Comment by haarburger** [comment]
@kalefranz I'm trying to set up a centralized installation where the env dir for a user `john` should be set to `/foo/john/envs`. Note that this is not inside the home directory. Following the [documentation](http://conda.pydata.org/docs/install/central.html#specify-environment-directories-envs-dirs) I'd like to set this by the admin config file. Is there any way to set up a centralized condarc like this? 
```
envs_dirs:
  - /foo/$USERNAME/envs
```
This doesn't work of course, but you get the point...

**Comment by kalefranz** [comment]
Actually, `/foo/$HOME/envs` *should* work!  Since most shells set the `$HOME` environment variable.  If in a 4.3 conda version that doesn't work, it's a quick fix.

**Comment by haarburger** [comment]
Unfortunately it didn't work. Instead, a directory `$HOME` is created and the variable is not interpreted as a variable.
I've taken a different approach then, adding 
```
export CONDA_ENVS_PATH=/work/$USER/envs
export PATH="/usr/local/anaconda3/bin:$PATH"
```
to a file `/etc/profile.d/conda_envs.sh`, which works well. So far, I didn't face any permission problems. Maybe you can reproduce yours, @alexbarrera?

**Comment by thoth291** [comment]
@haarburger , I used to do set env variable in my setup and it worked even with older conda - what is the benefit of the new conda?
In order to reproduce the problem you may try cache mode in numba
```python
@jit(cache=True)
```
It used to introduce some issues - but the code might be fixed right now...

**Comment by abalter** [comment]
So, we've been doing some experimentation with using ACLs on a group directory and they are not working. Somehow, when conda installs things, it is able to apply permissions that are overriding or circumventing the ACLs.

We created a sandbox directory `permstest`. 
```
balter@exalab3:.../permstest$ getfacl .
# file: .
# owner: burchard
# group: BioCoders
# flags: -st
user::rwx
group::rwx
other::---
default:user::rwx
default:group::rwx
default:group:BioCoders:rwx
default:mask::rwx
default:other::---
balter@exalab3:.../permstest$ getfacl miniconda3
# file: miniconda3
# owner: balter
# group: BioCoders
# flags: -s-
user::rwx
group::rwx
group:BioCoders:rwx
mask::rwx
other::---
default:user::rwx
default:group::rwx
default:group:BioCoders:rwx
default:mask::rwx
default:other::---
```
When I or anyone else creates files or directories in that directory, everything "works":

```
balter@exalab3:.../permstest$ echo "main (){}" > test.c
balter@exalab3:.../permstest$ gcc test.c
balter@exalab3:.../permstest$ touch touchtest
balter@exalab3:.../permstest$ mkdir dirtest
balter@exalab3:.../permstest$ ./miniconda3/bin/python -c "f=open('filecreatedbypy','w'); f.write('test'); f.close()"
balter@exalab3:.../permstest$ ./miniconda3/bin/python -c "import os; os.mkdir('dirbypy')"
balter@exalab3:.../permstest$ ls -lrt
total 19875
-rw-rw----+  1 balter   BioCoders 33905474 Feb  2 23:05 Miniconda3-latest-Linux-x86_64.sh
drwxrws---+ 12 balter   BioCoders     4096 Feb  3 09:05 miniconda3
-rw-rw----+  1 balter   BioCoders       10 Feb  3 12:07 test.c
-rwxrwx--x+  1 balter   BioCoders     6262 Feb  3 12:08 a.out
-rw-rw----+  1 balter   BioCoders        0 Feb  3 12:09 touchtest
drwxrws---+  2 balter   BioCoders     4096 Feb  3 12:09 dirtest
-rw-rw----+  1 balter   BioCoders        4 Feb  3 12:09 filecreatedbypy
drwxrws---+  2 balter   BioCoders     4096 Feb  3 12:09 dirbypy
```

When I installed miniconda, the permissions went in as 770 as hoped for. However, when I or anyone else installs, they are going in as 755. This means that only the installer will be able to remove, update, etc.

Conda is simply a python program, and it invokes other compilers and installers. So based on the experiments above, it seems like anything done with a python program or system compiler should result in the expected permissions.

But, clearly conda is able to do something we don't understand regarding how it is able to override permissions.

Any clarity that can be shed on this would be greatly appreciated!

**Comment by ijstokes** [comment]
@kalefranz is the Conda Czar and apparently there are some big updates in 4.3 (available now) that are supposed to help with the broader points brought up in this issue.  Unfortunately I don't know details, but it does sound like weird stuff is happening for you @abalter !  My last experience with conda in this regard (which granted was ~1 year ago) suggested that conda, as you point out, should just "do normal stuff", and doesn't take any special action WRT ownership and permissions.  `uid` and `gid` associated with the conda `pid` and `umask` **should** be the basis of any ownership, end of story.

**Comment by abalter** [comment]
Supposedly, this will be addressed (in whatever way) in v 4.4

https://github.com/conda/conda/issues/1329#issuecomment-255640965

We shall see...

**Comment by thoth291** [comment]
@ijstokes nothing new happens with @abalter setup - it's been known for a while and was addressed before in this post: https://github.com/conda/conda/issues/1329#issuecomment-237985765.

**Comment by kalefranz** [comment]
Notwithstanding the pending bug fix https://github.com/conda/conda/pull/4604, I believe this issue is basically resolved as of conda 4.3.  If specific issues with multiuser support are still encountered, please file a new bug report with the stack trace and conda version.
