### ISSUE TITLE
conda convert does not update subdir

### ISSUE THREAD

**Issue by johanneskoester** [conda/conda#1337]
The subdir key in info/index.json of the conda package is not updated when running conda convert.
This results in overwriting the builds of other platforms when uploading to binstar.

Version: conda 3.12.0

**Comment by asmeurer** [comment]
This should be fixed by https://github.com/conda/conda-build/pull/377. Run `conda update conda-build` and try again.

**Comment by johanneskoester** [comment]
`conda update conda-build` did not update anything for me. I guess I have already the newest version. Still the same problem.

**Comment by johanneskoester** [comment]
Conda-build is 1.12.1/py34_0.

**Comment by asmeurer** [comment]
Oh sorry, it looks like this change hasn't made it into a release yet.
