### ISSUE TITLE
menuinst failure on Windows (PermissionError)

### ISSUE THREAD

**Issue by pitrou** [conda/conda#1717]
Just got the following:
```
[27] c:\>conda32 install ipython
Fetching package metadata: ........
Solving package specifications: ...........
Package plan for installation in environment C:\Miniconda-32\envs\27:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    decorator-4.0.4            |           py27_0          11 KB
    ipython_genutils-0.1.0     |           py27_0          32 KB
    path.py-8.1.2              |           py27_0          44 KB
    pyreadline-2.1             |           py27_0         127 KB
    simplegeneric-0.8.1        |           py27_0           6 KB
    pickleshare-0.5            |           py27_0           8 KB
    traitlets-4.0.0            |           py27_0          88 KB
    ipython-4.0.0              |           py27_0         965 KB
    ------------------------------------------------------------
                                           Total:         1.3 MB

The following NEW packages will be INSTALLED:

    decorator:        4.0.4-py27_0
    ipython:          4.0.0-py27_0
    ipython_genutils: 0.1.0-py27_0
    path.py:          8.1.2-py27_0
    pickleshare:      0.5-py27_0
    pyreadline:       2.1-py27_0
    simplegeneric:    0.8.1-py27_0
    traitlets:        4.0.0-py27_0

Proceed ([y]/n)?

Fetching packages ...
decorator-4.0. 100% |###############################| Time: 0:00:00   0.00  B/s
ipython_genuti 100% |###############################| Time: 0:00:00 352.97 kB/s
path.py-8.1.2- 100% |###############################| Time: 0:00:00 242.99 kB/s
pyreadline-2.1 100% |###############################| Time: 0:00:00 268.53 kB/s
simplegeneric- 100% |###############################| Time: 0:00:00   0.00  B/s
pickleshare-0. 100% |###############################| Time: 0:00:00   0.00  B/s
traitlets-4.0. 100% |###############################| Time: 0:00:00 222.66 kB/s
ipython-4.0.0- 100% |###############################| Time: 0:00:01 614.15 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):#############       |  87%
  File "C:\Miniconda-32\lib\site-packages\conda\install.py", line 343, in mk_men
us
    env_setup_cmd=env_setup_cmd)
  File "C:\Miniconda-32\lib\site-packages\menuinst\__init__.py", line 44, in ins
tall
    m.create()
  File "C:\Miniconda-32\lib\site-packages\menuinst\win32.py", line 71, in create

    os.mkdir(self.path)
PermissionError: [WinError 5] Access is denied: 'C:\\ProgramData\\Microsoft\\Win
dows\\Start Menu\\Programs\\Anaconda (32-bit)'
[      COMPLETE      ]|##################################################| 100%
```

**Comment by msarahan** [comment]
If menuinst is installed into an admin-level installation of Python, then it tries to create shortcuts in that global location, rather than the user location (%HOME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs).

I don't know a good solution, other than not installing Anaconda as admin?  I'll see about fixing menuinst so that it falls back to trying to write shortcuts into the user folder if a PermissionError occurs.

**Comment by pitrou** [comment]
Yes, at least not aborting the install in an inconsistent state sounds like a good idea. I don't really care about the menu entries :-)

**Comment by msarahan** [comment]
This should be addressed in current versions of menuinst.  Closing this issue.  Reopen if it recurs, please.

**Comment by shailensobhee** [comment]
This issue is not resolved. When you start the installer, you are asked whether to install for the current user only or system-wide for all users. If you choose the current user, anaconda/miniconda is installed in C:\Users\<username>\AppData\Local\Continuum\miniconda3.

That said, the installer should not fail on the lack of Admin rights.
