### ISSUE TITLE
Can't update fresh install

### ISSUE THREAD

**Issue by chadkennedyonline** [conda/conda#1783]
I'm on Windows 8.1 64-bit. I uninstalled my old Anaconda installation. Confirmed C:\Anaconda directory was deleted. Installed Windows 64-bit 3.5 Anaconda, for "Just Me" using Anaconda's installer from their website. First thing I did after installation finished was open Anaconda Prompt and type "conda update --all". I get the following error:

    Error: Unsatisfiable package specifications.
    Generating hint:
    [      COMPLETE      ]|##################################################| 100%

    Hint: 'qt' has unsatisfiable dependencies (see 'conda info qt')

    Note that the following features are enabled:
      - vc9
      - vc10
      - vc14

**Comment by j9ac9k** [comment]
Suspect this is the same issue for #1779 (which has no solution yet).

**Comment by chadkennedyonline** [comment]
Interesting. Closed and reopened the Anaconda Prompt window. Performed "conda update conda", which reported I was already running the latest version. The tried "conda update --all" again. I got the same error as above, but this time for the zeromq package instead of qt. So I ran "conda update --all" again. Now same error, but for the jpeg package. It seems every time I run "conda update --all" I get the same error, but for an apparently random package.

**Comment by j9ac9k** [comment]
The issue isn't quite for a random package, but for a package that is depending on msvc_runtime (which all those packages are on Windows environments).

You may be able to run "conda update msvc_runtime", but that still didn't solve my problems.

**Comment by breisfeld** [comment]
On Windows 7, I am having the same problems as @chadkennedyonline (unsatisfiable package specifications, with a different unsatisfied package every time ```conda update --all``` is run). 

Trying to update ```msvc_runtime``` gives

```
$ conda update msvc_runtime
Fetching package metadata: ........
Solving package specifications: ...................
Package plan for installation in environment D:\Python\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    msvc_runtime-1.0.1         |           vc14_0         2.2 MB
    conda-env-2.4.4            |           py35_1          52 KB
    ------------------------------------------------------------
                                           Total:         2.2 MB

The following packages will be UPDATED:

    conda-env:    2.4.4-py35_0 --> 2.4.4-py35_1
    msvc_runtime: 1.0.0-vc14_0 [vc14] --> 1.0.1-vc14_0 [vc14]

Proceed ([y]/n)? y

Fetching packages ...
msvc_runtime-1 100% |###############################| Time: 0:00:14 151.50 kB/s
conda-env-2.4. 100% |###############################| Time: 0:00:01  30.76 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
not was unexpected at this time.################                         |  50%
Error: Error: post-link failed for: conda-env-2.4.4-py35_1
```

**Comment by msarahan** [comment]
Sorry for the many conflated issues.  Here's an explanation:

1. PREFIX/Library/bin was not put on PATH by old installers (Anaconda < 2.4; Miniconda <3.18).  This led to Matplotlib and/or spyder not loading, because the Qt dlls were not found.
2. conda-env-2.4.4-1 was my approach to add Library/bin to path.  There was a mistake in it that made it work only on Python3 base installations: https://github.com/ContinuumIO/anaconda-issues/issues/509#issuecomment-154517037
3. @marscher recommended using site.py instead of trying to modify PATH: https://github.com/conda/conda/issues/1753#issuecomment-154421628 - this will avoid the troubles with the batch script.  The downside is that any additional executables (hdf5 tools, for example) will not be directly accessible from the root environment, if that root environment was installed with an old installer, and you have not otherwise added PREFIX/Library/bin to your PATH.

I am presently building and testing fixes.  I hope to have these out later today.

**Comment by collawolley** [comment]
Hi, I uninstall my old Anaconda and installed the latest anaconda. unfortunately, I have not been able to install my preferred package. an attempt at installing gensim and scikit-learns gave many errors:
i.e. ensuring that c\users\anaconda\library\bin is on your user path environment variable
"" was expected at this time
error: error: post-link failed for : conda-env-2.4.4-py27_1

I am using windows 7, 64 bit.  and this is the content of my user path variable: C:\Users\user\Anaconda2;C:\Users\user\Anaconda2\Scripts;C:\Users\user\Anaconda2\Library\bin;C:\Users\user\Anaconda\Library\bin


I will appreciate any help.

Thanks
Colla

**Comment by msarahan** [comment]
We'll have a fix as soon as we can.  For now, a workaround is to force installation of the older conda-env package:

```
del (your install prefix)\Scripts\.conda-env-post-link.bat
conda install scikit-learn gensim conda-env=2.4.2
```

Doing so will leave the known Matplotlib/png/qt dll issues.  If you add (Prefix)\Library\bin to your PATH yourself, those go away.

Easier fix coming soon.

**Comment by collawolley** [comment]
Thanks for the reply. But the problem is the same for any package, even for gensim. do you think your suggestion solves it all?
thanks

**Comment by msarahan** [comment]
Forcing conda-env to the lower version prevents it from being automatically updated.  When that happens, it is trying to run the post-link script.  The post link script is broken for Python 2.7.  If you don't run the post-link script (by deleting it, and preventing it from getting installed), then yes, I think my suggestion solves it all.

**Comment by collawolley** [comment]
Thanks. so where do i delete the "\Scripts\.conda-env-post-link.bat' from in order to activate your suggestion?
thanks

**Comment by collawolley** [comment]
so i did as you suggetsed but got the same error.
![screenshot 2015-11-07 21 37 19](https://cloud.githubusercontent.com/assets/15602821/11017191/fc534b56-8597-11e5-8b9e-c79eb39031ba.png)

**Comment by msarahan** [comment]
I don't think you deleted the post-link script.  Based on your screenshot, it lives at C:\Users\user\Anaconda2\Scripts\

**Comment by collawolley** [comment]
Ok thanks. I just did and it worked. so must I specify that conda-env=2.2 anytime i want to install any package?
thanks

**Comment by msarahan** [comment]
Until we can roll out a better fix, yes.

**Comment by collawolley** [comment]
ok thanks

**Comment by msarahan** [comment]
This issue should be fixed.  The relevant fixed packages were:

python-2.7.10-4.
python-3.4.3-4
python-3.5.0-3

conda-env-2.4.4 (build 2)
menuinst-1.2.2

The fix is that the conda-env post-link script has been removed.  It has been replaced by a modified Lib/site.py file in each Python installation, plus a library_bin.pth file in each Python installation.  The combination of these lead to Library/bin being added to os.environ["PATH"] for any Python process.  Any programs you install that end up in Library/bin (for example, patch) will still not be on PATH for older installations.  You can either modify PATH to add Library/bin yourself, or uninstall and reinstall using a new installer (Anaconda >= 2.4.0; Miniconda >= 3.18)

I'm closing this issue, but please reopen it if you are still having issues.

**Comment by breisfeld** [comment]
Sorry to be dense, but I am still having the ```Error: Unsatisfiable package specifications.``` issue with ```conda update --all``` on  ```Python 3.5.0 |Anaconda 2.4.0 (64-bit)| (default, Oct 20 2015, 07:26:33) [MSC v.1900 64 bit (AMD64)] on win32```. 

I have renamed ```.conda-env-post-link.bat```. 

Was this fix to address a different issue or am I missing a crucial step?  

Thank you for your hard work on this.

**Comment by msarahan** [comment]
By no means are you being dense.  Thanks for your patience.  This is the next problem that I'm working to resolve.  I hope to have an update soon.

**Comment by bschoenhense** [comment]
conda-env-2.4.4 (build 2) worked for me, but only after manually deleting .conda-env-post-link.bat.

**Comment by demen777** [comment]
@bschoenhense
+1
