### ISSUE TITLE
Cannot clone environment

### ISSUE THREAD

**Issue by jni** [conda/conda#1930]
I've created an Anaconda/Python 3.5 environment as follows:

```console
 ~ $ conda create -n ana3 python=3.5 anaconda
 ~ $ source activate ana3
 ~ $ pip install line_profiler memory_profiler
```

This works fine. Now I want to clone that environment so I can install some other packages on top of that. Unfortunately, this fails:

```console
 ~ $ conda create -n flatten --clone ana3
Fetching package metadata: ........
src_prefix: '/Users/nuneziglesiasj/anaconda/envs/ana3'
dst_prefix: '/Users/nuneziglesiasj/anaconda/envs/flatten'
Packages: 149
Files: 24
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/nuneziglesiasj/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 246, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/site-packages/conda/misc.py", line 237, in clone_env
    shutil.copystat(src, dst)
  File "/Users/nuneziglesiasj/anaconda/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/nuneziglesiasj/anaconda/envs/flatten/lib/libgcc_s.10.5.dylib'
```

In case this helps, here's the file giving `shutil.copystat` trouble:

```console
 ~ $ ls -l /Users/nuneziglesiasj/anaconda/envs/flat3/lib/libgcc_s.10.5.dylib
-rwxr-xr-x  1 nuneziglesiasj  staff    60K  3 Dec 17:36 /Users/nuneziglesiasj/anaconda/envs/flat3/lib/libgcc_s.10.5.dylib

 ~ $ ls -l /Users/nuneziglesiasj/anaconda/envs/ana3/lib/libgcc_s.10.5.dylib
lrwxr-xr-x  1 nuneziglesiasj  staff    25B 29 Dec 22:11 /Users/nuneziglesiasj/anaconda/envs/ana3/lib/libgcc_s.10.5.dylib -> /usr/lib/libgcc_s.1.dylib
```

And last but not least, the conda version. `conda update conda` did not help with this error.

```console
 ~ $ conda --version
conda 3.19.0
```

Thanks!

**Comment by msarahan** [comment]
Pinging @ilanschnell

**Comment by eadsjr** [comment]
I appear to be having the same issue on OSX El Capitan.

Username removed.

```
$ conda create -n cv2 python=2.7 anaconda
...
```
```
$ conda create -n py_cv2 --clone cv2
...
Traceback (most recent call last):
  File "/Users/USER/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/USER/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/USER/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/USER/anaconda/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/USER/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 246, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/USER/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/USER/anaconda/lib/python3.5/site-packages/conda/misc.py", line 237, in clone_env
    shutil.copystat(src, dst)
  File "/Users/USER/anaconda/lib/python3.5/shutil.py", line 212, in copystat
    lookup("chflags")(dst, st.st_flags, follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted: '/Users/USER/anaconda/envs/py_cv2/lib/libgcc_s.10.5.dylib'
```
```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.8.1
     root environment : /Users/USER/anaconda  (writable)
  default environment : /Users/USER/anaconda
     envs directories : /Users/USER/anaconda/envs
        package cache : /Users/USER/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

```
$ ls -l /Users/USER/anaconda/envs/py_cv2/lib/libgcc_s.10.5.dylib
-rwxr-xr-x  1 USER  staff  61072 Oct 17 16:47 /Users/USER/anaconda/envs/py_cv2/lib/libgcc_s.10.5.dylib
```

**Comment by colin-svds** [comment]
I wanted to chime in and say I'm also experiencing this on El Capitan
```
$ conda create --name env2 --clone env1
Fetching package metadata: ....
src_prefix: '/Users/USER/miniconda2/envs/env1'
dst_prefix: '/Users/USER/miniconda2/envs/env2'
Packages: 160
Files: 9
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/USER/miniconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/USER/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/USER/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/USER/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/USER/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 246, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/USER/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/USER/miniconda2/lib/python2.7/site-packages/conda/misc.py", line 237, in clone_env
    shutil.copystat(src, dst)
  File "/Users/USER/miniconda2/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/USER/miniconda2/envs/env2/lib/libgcc_s.10.5.dylib'

$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.8
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : /Users/USER/miniconda2  (writable)
  default environment : /Users/USER/miniconda2
     envs directories : /Users/USER/miniconda2/envs
        package cache : /Users/USER/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by jakirkham** [comment]
As a workaround can you create an environment file from this first in environment and use it to substantiate the second one? Admittedly a little more work, but it is less work than reinstalling everything by hand. Maybe this will help until there is a proper fix.

**Comment by motjuste** [comment]
@jakirkham I was facing the same issue, and I tried creating from file. **It worked** without any problems.

PS I had to remove the `conda` packages from the file since I was cloning from root.

**Comment by jakirkham** [comment]
Glad it helped @motjuste. Given that you were cloning root, creating a file seems like a better way to go. Clone might have be misbehaved in some weird way otherwise (though probably in a different way than in this issue).

**Comment by harperic** [comment]
It looks like I may be having a related problem, however this is not on OS X but on Ubuntu Linux 15.10:

~ ❯❯❯ conda create --name flowers --clone snowflakes
Fetching package metadata: ....
src_prefix: '/home/harperic/miniconda3/envs/snowflakes'
dst_prefix: '/home/harperic/miniconda3/envs/flowers'
Packages: 13
Files: 0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/harperic/miniconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/misc.py", line 243, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 716, in dependency_sort
    for key, value in iteritems(must_have):
  File "/home/harperic/miniconda3/lib/python3.5/site-packages/conda/compat.py", line 157, in iteritems
    return iter(getattr(d, _iteritems)())
AttributeError: 'list' object has no attribute 'items'

Current conda install:

             platform : linux-64
        conda version : 4.0.1
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/harperic/miniconda3  (writable)
  default environment : /home/harperic/miniconda3
     envs directories : /home/harperic/miniconda3/envs
        package cache : /home/harperic/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False


As you can tell I am going through the test drive and have stopped here as the cloning appears to be broken.

**Comment by mcg1969** [comment]
There are two issues at play here, fixed by the following two PRs:
https://github.com/conda/conda/pull/2193
https://github.com/conda/conda/pull/2194

**Comment by toastmaker** [comment]
The cloning is still broken after the conda update to 4.0.1

    conda create --name miriclone --clone mirisim

Traceback (most recent call last):
  File "/Users/topinka/anaconda2/envs/mirisim/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/topinka/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/topinka/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/topinka/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/topinka/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/topinka/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/topinka/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 237, in clone_env
    shutil.copystat(src, dst)
  File "/Users/topinka/anaconda2/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/topinka/anaconda2/envs/miriclone/lib/libgcc_s.10.5.dylib'


    conda info

Current conda install:
platform : osx-64
conda version : 4.0.1
conda-build version : 1.18.2
python version : 2.7.11.final.0
requests version : 2.9.1
root environment : /Users/topinka/anaconda2  (writable)
default environment : /Users/topinka/anaconda2/envs/mirisim
envs directories : /Users/topinka/anaconda2/envs
package cache : /Users/topinka/anaconda2/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
https://repo.continuum.io/pkgs/free/noarch/
https://repo.continuum.io/pkgs/pro/osx-64/
https://repo.continuum.io/pkgs/pro/noarch/
config file : None
is foreign system : False

**Comment by mcg1969** [comment]
Yes, those two PRs are not in 4.0.1

**Comment by kalefranz** [comment]
Should be fixed with today's `4.0.2` release.
