### ISSUE TITLE
conda update anaconda fails: specifications in conflict

### ISSUE THREAD

**Issue by Arn-O** [conda/conda#2181]
I use Anaconda on Mac OS X and was used to update my installation with ``conda update conda`` and ``conda update anaconda``. I have noticed that no updates have been pushed for a while, which was suspicious since I knew that new versions were available.

Today I have tried again and conda has been updated to version 4.0. But now, when I try to update Anaconda, I got the following error messages:

```
$ conda update -f anaconda   
Fetching package metadata: ....
Solving package specifications: ....

The following specifications were found to be in conflict:
  - anaconda -> _license 1.1 py34_0|1.1 py35_1
  - anaconda -> abstract-rendering 0.5.1 np110py34_0|0.5.1 np110py35_0|0.5.1 np19py26_0|0.5.1 np19py33_0|0.5.1 np19py34_0
  - anaconda -> alabaster 0.7.3 py26_0|0.7.3 py33_0|0.7.3 py34_0|0.7.6 py34_0|0.7.6 py35_0|0.7.7 py34_0|0.7.7 py35_0
  - anaconda -> anaconda-client 1.1.0 py34_0|1.1.0 py35_0|1.2.1 py34_0|1.2.1 py35_0|1.2.2 py34_0|1.2.2 py35_0
  - anaconda -> appnope 0.1.0 py34_0|0.1.0 py35_0
...
  - anaconda -> wheel 0.26.0 py34_1|0.26.0 py35_1
  - anaconda -> xlrd 0.9.2 py26_0|0.9.2 py33_0|0.9.3 py26_0|0.9.3 py33_0|0.9.3 py34_0|0.9.4 py34_0|0.9.4 py35_0
  - anaconda -> xlsxwriter 0.5.2 py26_0|0.5.2 py33_0|0.5.5 py26_0|0.5.5 py33_0|0.5.5 py34_0|0.5.7 py26_0|0.5.7 py33_0|0.5.7 py34_0|0.6.7 py26_0|0.6.7 py33_0|0.6.7 py34_0|0.7.3 py26_0|0.7.3 py33_0|0.7.3 py34_0|0.7.7 py34_0|0.7.7 py35_0|0.8.4 py34_0|0.8.4 py35_0
  - anaconda -> xlwings 0.3.4 py26_0|0.3.4 py33_0|0.3.4 py34_0|0.3.5 py26_0|0.3.5 py33_0|0.3.5 py34_0|0.4.1 py34_0|0.4.1 py35_0|0.5.0 py34_0|0.5.0 py35_0|0.6.4 py34_0|0.6.4 py35_0
  - anaconda -> xlwt 0.7.5 py26_0|1.0.0 py26_0|1.0.0 py33_0|1.0.0 py34_0|1.0.0 py35_0
Use "conda info <package>" to see the dependencies for each package.
```

The list has been shorten, it is a very long list of packages.

Any idea of what's going on?

Thank you for your help!

**Comment by mcg1969** [comment]
Can you attach the (long) output of `conda --debug update anaconda`? And can you also list your current environment with a `conda list`?

We've updated the solver to ensure that environments remain consistent. This was a somewhat major change, so it looks like your particular environment is exercising a corner case we didn't catch.

**Comment by Arn-O** [comment]
Sure. Here are the outputs:

[conda debug.txt](https://github.com/conda/conda/files/159925/conda.debug.txt)
[conda list.txt](https://github.com/conda/conda/files/159926/conda.list.txt)

A workaround is totally fine to me. If I need to uninstall/reinstall, that's ok.

**Comment by mcg1969** [comment]
I'll be honest, a fresh install is never going to hurt :-) According to the debug output, your current environment is indeed "inconsistent"---that is, it has one or more dependency violations. Unfortunately it also looks like it is unable to fix them. 

If you need to do the update urgently I would try `conda update --all` first, followed by a fresh install if that fails. (Yes, @kalefranz, I just _recommended_ `conda update --all`, how about that?) But I'm going to see if I can reproduce your exact solver call in a test script and determine more precisely what the conflict is. If you want to wait for that, there may be a simpler fix.

**Comment by Arn-O** [comment]
First of all, let's me say that the support of this project is AWESOME!

No hurry from my end, so I will wait. If I need to a fresh install, how shall I do the unistall? With ``conda remove anaconda``?

**Comment by acycliq** [comment]
Just to say i have the exact same issue with Arn-O. I decided to update my anaconda about an hour ago and I did a `conda update conda` first which updated the following
```
    conda:      3.18.7-py27_0 defaults --> 4.0.0-py27_0  defaults
    conda-env:  2.4.4-py27_0  defaults --> 2.4.5-py27_0  defaults
    openssl:    1.0.2d-0      defaults --> 1.0.2g-0      defaults
    pip:        7.1.2-py27_0  defaults --> 8.0.3-py27_0  defaults
    python:     2.7.10-2      defaults --> 2.7.11-0      defaults
    requests:   2.8.1-py27_0  defaults --> 2.9.1-py27_0  defaults
    setuptools: 18.5-py27_0   defaults --> 20.1.1-py27_0 defaults
    sqlite:     3.8.4.1-1     defaults --> 3.9.2-0       defaults
    wheel:      0.26.0-py27_1 defaults --> 0.29.0-py27_0 defaults
```

Following that executing `conda update anaconda` resulted to a very long list of specifications in conflict which as far as I can tell is identical to the one attached by Arn-O. I guess therefore I will also have to do a reinstall, so I you have any directions please let me know too. (Not the most preferable solution for me though cause It had taken me almost a full weekend to figure out how to connect to a MS SQL server from anaconda running on OSX)

**Comment by mcg1969** [comment]
I'm sorry you're having trouble. I have a radical suggestion for both of you: try _removing anaconda_. Not the entire distribution, mind you, just the Anaconda metapackage. In other words:
```
conda remove anaconda --force
```
The reason this helps is that the various versions of Anaconda select _exact_ versions and builds of the various python packages. This has obvious benefits most of the time, but once the packages are _installed_, the `anaconda` metapackage prevents those packages from being updated separately.

Once you've removed `anaconda`, now try doing `conda update --all`, or any other operation you need to. With that metapackage out of the picture, the solver should have an easier time resolving dependency conflicts.

Please let me know what you come up with! In the meanwhile I'm going to investigate alternate solutions.

**Comment by acycliq** [comment]
Many thanks for your help! It does looks to work. I did what you proposed (ie `conda remove anaconda --force` and then  `conda update --all`) which installed a whole lot of packages  (some new, some got upgraded and some got downgraded - the latter I guess happened cause I had upgraded a few packages in my last anaconda). My connection to the MS SQL server has been broken unfortunately but I will look into it tomorrow. I have kept a walkthrough, hopefully It wont be as painful as the first time.
I havent tried to run the usual `conda updata conda` and `conda update anaconda`, i guess it wont add anything new but wont do any harm either, is that correct? Many thanks again your help is highly appreciated

**Comment by mcg1969** [comment]
Ouch, that's not good about your SQL connection. Are you in Gitter? Maybe we can move the discussion over to the conda chat there (since it really isn't related to this issue anymore) and we can figure out your SQL issue.

**Comment by mcg1969** [comment]
I know think these problems are at least in part due to https://github.com/conda/conda/issues/2179

**Comment by Arn-O** [comment]
So the update gave me this:

```
Arnauds-MacBook-Pro:~ arnaud$ conda update --all
Fetching package metadata: ....
Solving package specifications: ...........

Package plan for installation in environment /Users/arnaud/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    binstar-0.12               |                2          697 B
    libdynd-0.7.1              |                0         4.2 MB
    libsodium-1.0.3            |                0         338 KB
    mkl-11.3.1                 |                0        99.1 MB
    xz-5.0.5                   |                1         173 KB
    alabaster-0.7.7            |           py27_0          15 KB
    boto-2.39.0                |           py27_0         1.3 MB
    certifi-2015.9.6.2         |           py27_0         212 KB
    cloudpickle-0.1.1          |           py27_0          15 KB
    colorama-0.3.6             |           py27_0          19 KB
    cytoolz-0.7.5              |           py27_0         249 KB
    decorator-4.0.9            |           py27_0          12 KB
    enum34-1.1.2               |           py27_0          55 KB
    et_xmlfile-1.0.1           |           py27_0          15 KB
    future-0.15.2              |           py27_0         616 KB
    futures-3.0.3              |           py27_0          17 KB
    heapdict-1.0.0             |           py27_0           4 KB
    jdcal-1.2                  |           py27_0           7 KB
    kiwisolver-0.1.2           |           py27_0          69 KB
    libxslt-1.1.28             |                1         475 KB
    locket-0.2.0               |           py27_0           5 KB
    nltk-3.2                   |           py27_0         1.8 MB
    numpy-1.9.3                |           py27_1         2.9 MB
    pep8-1.7.0                 |           py27_0          47 KB
    pil-1.1.7                  |           py27_2         351 KB
    pillow-3.1.1               |           py27_0         472 KB
    psutil-4.0.0               |           py27_0         198 KB
    py-1.4.31                  |           py27_0         123 KB
    pycurl-7.19.5.3            |           py27_0          43 KB
    pyflakes-1.1.0             |           py27_0          65 KB
    pygments-2.1.1             |           py27_0         1.2 MB
    snowballstemmer-1.2.1      |           py27_0          73 KB
    sphinx_rtd_theme-0.1.9     |           py27_0         629 KB
    sqlalchemy-1.0.12          |           py27_0         1.3 MB
    ujson-1.35                 |           py27_0          20 KB
    werkzeug-0.11.4            |           py27_0         391 KB
    xlsxwriter-0.8.4           |           py27_0         188 KB
    astropy-1.0.4              |       np19py27_0         5.3 MB
    babel-2.2.0                |           py27_0         4.3 MB
    bcolz-0.11.3               |           py27_0         378 KB
    chest-0.2.3                |           py27_0           9 KB
    clyent-1.2.1               |           py27_0          13 KB
    cycler-0.10.0              |           py27_0          11 KB
    dateutil-2.4.1             |           py27_0         218 KB
    dynd-python-0.7.1          |           py27_0         849 KB
    gevent-1.0.2               |           py27_0         346 KB
    lxml-3.5.0                 |           py27_0         975 KB
    networkx-1.11              |           py27_0         1.1 MB
    numexpr-2.4.4              |       np19py27_0         103 KB
    openpyxl-2.3.2             |           py27_0         248 KB
    patsy-0.4.0                |       np19py27_0         326 KB
    pytest-2.8.5               |           py27_0         223 KB
    scipy-0.17.0               |       np19py27_0        12.9 MB
    xlwings-0.6.4              |           py27_0         343 KB
    anaconda-client-1.2.2      |           py27_0          94 KB
    conda-build-1.19.0         |           py27_0         211 KB
    datashape-0.5.1            |           py27_0          89 KB
    enaml-0.9.7                |           py27_0         1.1 MB
    gevent-websocket-0.9.5     |           py27_0          25 KB
    ipython-4.1.2              |           py27_0         928 KB
    matplotlib-1.4.3           |       np19py27_3        40.8 MB
    numba-0.23.1               |       np19py27_0         1.5 MB
    pbr-1.3.0                  |           py27_0          82 KB
    pytables-3.2.2             |       np19py27_0         1.6 MB
    sphinx-1.3.5               |           py27_0         1.2 MB
    bokeh-0.11.1               |           py27_0         3.1 MB
    enable-4.4.1               |       np19py27_0         1.4 MB
    flask-cors-2.1.2           |           py27_0          15 KB
    mock-1.3.0                 |           py27_0          95 KB
    odo-0.4.2                  |           py27_0         177 KB
    partd-0.3.2                |           py27_1          23 KB
    sockjs-tornado-1.0.0       |           py27_0          30 KB
    blaze-core-0.9.0           |           py27_0         542 KB
    chaco-4.5.0                |       np19py27_0         871 KB
    dask-0.8.0                 |           py27_0         276 KB
    ipykernel-4.3.1            |           py27_0         117 KB
    blaze-0.9.1                |           py27_0         542 KB
    jupyter_console-4.1.0      |           py27_0          24 KB
    ipywidgets-4.1.1           |           py27_0          98 KB
    ------------------------------------------------------------
                                           Total:       198.9 MB

The following NEW packages will be INSTALLED:

    chest:              0.2.3-py27_0     
    cloudpickle:        0.1.1-py27_0     
    dask:               0.8.0-py27_0     
    et_xmlfile:         1.0.1-py27_0     
    flask-cors:         2.1.2-py27_0     
    heapdict:           1.0.0-py27_0     
    locket:             0.2.0-py27_0     
    mkl:                11.3.1-0         
    partd:              0.3.2-py27_1     
    pbr:                1.3.0-py27_0     

The following packages will be UPDATED:

    abstract-rendering: 0.5.1-np110py27_0  --> 0.5.1-np19py27_0 
    alabaster:          0.7.6-py27_0       --> 0.7.7-py27_0     
    anaconda-client:    1.2.1-py27_0       --> 1.2.2-py27_0     
    babel:              2.1.1-py27_0       --> 2.2.0-py27_0     
    bcolz:              0.9.0-np19py27_0   --> 0.11.3-py27_0    
    binstar:            0.11.0-py27_0      --> 0.12-2           
    blaze:              0.6.3-np19py27_0   --> 0.9.1-py27_0     
    blaze-core:         0.8.3-py27_0       --> 0.9.0-py27_0     
    bokeh:              0.10.0-py27_0      --> 0.11.1-py27_0    
    boto:               2.38.0-py27_0      --> 2.39.0-py27_0    
    bottleneck:         1.0.0-np110py27_0  --> 1.0.0-np19py27_0 
    certifi:            14.05.14-py27_0    --> 2015.9.6.2-py27_0
    chaco:              4.4.1-np19py27_0   --> 4.5.0-np19py27_0 
    clyent:             1.2.0-py27_0       --> 1.2.1-py27_0     
    colorama:           0.3.3-py27_0       --> 0.3.6-py27_0     
    conda-build:        1.8.2-py27_0       --> 1.19.0-py27_0    
    cycler:             0.9.0-py27_0       --> 0.10.0-py27_0    
    cytoolz:            0.7.4-py27_0       --> 0.7.5-py27_0     
    datashape:          0.4.7-np110py27_1  --> 0.5.1-py27_0     
    dateutil:           2.1-py27_2         --> 2.4.1-py27_0     
    decorator:          4.0.6-py27_0       --> 4.0.9-py27_0     
    dynd-python:        0.7.0-py27_0       --> 0.7.1-py27_0     
    enable:             4.3.0-np19py27_2   --> 4.4.1-np19py27_0 
    enum34:             1.0.4-py27_0       --> 1.1.2-py27_0     
    future:             0.13.1-py27_0      --> 0.15.2-py27_0    
    futures:            2.2.0-py27_0       --> 3.0.3-py27_0     
    gevent:             1.0.1-py27_0       --> 1.0.2-py27_0     
    gevent-websocket:   0.9.3-py27_0       --> 0.9.5-py27_0     
    ipykernel:          4.2.2-py27_0       --> 4.3.1-py27_0     
    ipython:            4.0.3-py27_0       --> 4.1.2-py27_0     
    ipywidgets:         4.1.0-py27_0       --> 4.1.1-py27_0     
    jdcal:              1.0-py27_0         --> 1.2-py27_0       
    jupyter_console:    4.0.3-py27_0       --> 4.1.0-py27_0     
    libdynd:            0.7.0-0            --> 0.7.1-0          
    libsodium:          0.4.5-0            --> 1.0.3-0          
    lxml:               3.4.4-py27_0       --> 3.5.0-py27_0     
    mock:               1.0.1-py27_0       --> 1.3.0-py27_0     
    networkx:           1.10-py27_0        --> 1.11-py27_0      
    nltk:               3.1-py27_0         --> 3.2-py27_0       
    numba:              0.22.1-np110py27_0 --> 0.23.1-np19py27_0
    numexpr:            2.4.4-np110py27_0  --> 2.4.4-np19py27_0 
    odo:                0.3.4-py27_0       --> 0.4.2-py27_0     
    openpyxl:           2.2.6-py27_0       --> 2.3.2-py27_0     
    pandasql:           0.6.3-np110py27_0  --> 0.6.3-np19py27_0 
    patsy:              0.4.0-np110py27_0  --> 0.4.0-np19py27_0 
    pep8:               1.6.2-py27_0       --> 1.7.0-py27_0     
    pil:                1.1.7-py27_1       --> 1.1.7-py27_2     
    pillow:             3.0.0-py27_1       --> 3.1.1-py27_0     
    psutil:             3.3.0-py27_0       --> 4.0.0-py27_0     
    py:                 1.4.30-py27_0      --> 1.4.31-py27_0    
    pycurl:             7.19.5.1-py27_3    --> 7.19.5.3-py27_0  
    pyflakes:           1.0.0-py27_0       --> 1.1.0-py27_0     
    pygments:           2.1-py27_0         --> 2.1.1-py27_0     
    pytables:           3.2.2-np110py27_0  --> 3.2.2-np19py27_0 
    pytest:             2.8.1-py27_0       --> 2.8.5-py27_0     
    scikit-image:       0.11.3-np110py27_0 --> 0.11.3-np19py27_0
    scipy:              0.16.0-np110py27_1 --> 0.17.0-np19py27_0
    snowballstemmer:    1.2.0-py27_0       --> 1.2.1-py27_0     
    sphinx:             1.3.1-py27_0       --> 1.3.5-py27_0     
    sphinx_rtd_theme:   0.1.7-py27_0       --> 0.1.9-py27_0     
    sqlalchemy:         1.0.9-py27_0       --> 1.0.12-py27_0    
    statsmodels:        0.6.1-np110py27_0  --> 0.6.1-np19py27_0 
    ujson:              1.33-py27_0        --> 1.35-py27_0      
    werkzeug:           0.11.2-py27_0      --> 0.11.4-py27_0    
    xlsxwriter:         0.7.7-py27_0       --> 0.8.4-py27_0     
    xlwings:            0.5.0-py27_0       --> 0.6.4-py27_0     
    xz:                 5.0.5-0            --> 5.0.5-1          

The following packages will be DOWNGRADED:

    astropy:            1.0.6-np110py27_0  --> 1.0.4-np19py27_0 
    enaml:              0.9.8-py27_0       --> 0.9.7-py27_0     
    h5py:               2.5.0-np110py27_4  --> 2.5.0-np19py27_3 
    kiwisolver:         0.1.3-py27_0       --> 0.1.2-py27_0     
    libxslt:            1.1.28-2           --> 1.1.28-1         
    matplotlib:         1.5.1-np110py27_0  --> 1.4.3-np19py27_3 
    numpy:              1.10.2-py27_0      --> 1.9.3-py27_1     
    pandas:             0.17.1-np110py27_0 --> 0.16.2-np19py27_0
    ply:                3.8-py27_0         --> 3.4-py27_0       
    scikit-learn:       0.17-np110py27_1   --> 0.16.1-np19py27_0
    sockjs-tornado:     1.0.1-py27_0       --> 1.0.0-py27_0     
    sqlparse:           0.1.16-py27_0      --> 0.1.15-py27_0 
```

Which I have accepted. And at the end, I got this message:

```
...
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!
!!  The 'binstar' conda package has been renamed to 'anaconda-client'.
!!  Please run:
!!
!!    conda install anaconda-client
!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Shall I install this package?

**Comment by Arn-O** [comment]
FYI, if I try to install again anaconda, most of the packages are downgraded.

**Comment by acycliq** [comment]
-Arnaud: I got the same message too, (the 'binstar' conda package etc stuff..) sorry forgot to mention. I guess its better to wait for the thumbs from Michael. However I decided to do as prompted and run 'conda install anaconda-client`. FYI, this is what I got after that. 

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ...........

# All requested packages already installed.
# packages in environment at /Users/Dimitris/anaconda:
#
anaconda-client           1.2.2                    py27_0

```

A quick check didnt show anything  bad with my new anaconda apart from my broken connection with my SQL Server but that was expected.

-Michael, I am not on Gitter (I might sign up, sounds good idea) but many thanks for providing your help and advice. I have some notes on how to deal with the broken SQL Server, so fingers crossed it should get fixed tomorrow

**Comment by mcg1969** [comment]
Folks, I'm reasonably convinced #2179 is essential for the fix. I wouldn't try too much more until 4.0.1.

**Comment by mcg1969** [comment]
Nothing wrong with a fresh install of Anaconda 2.5.0, though :-)

**Comment by mcg1969** [comment]
Yep, if I use a patched version of conda (the `fix2179` branch) I get much smoother results.

**Comment by acycliq** [comment]
An issue that has cropped up is that 

- I cant update packages via conda. I used to run pandas 0.17 which was installed with conda in my last installation, but it looks now conda cannot pick it up.
- conda thinks anaconda package is missing

Here is my console window:
```

iMacDimitris:~ Dimitris$ conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /Users/Dimitris/anaconda:
#
conda                     4.0.0                    py27_0  
iMacDimitris:~ Dimitris$ conda update anaconda
Error: package 'anaconda' is not installed in /Users/Dimitris/anaconda
iMacDimitris:~ Dimitris$ conda update pandas
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ...........

# All requested packages already installed.
# packages in environment at /Users/Dimitris/anaconda:
#
pandas                    0.16.2               np19py27_0  
```
However conda sees anaconda (list too long to include, only first few are shown) :
```
iMacDimitris:~ Dimitris$ conda search anaconda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
anaconda                     1.6.0                np16py26_0  defaults        
                             1.6.0                np16py26_0  defaults
                             1.6.0                np16py27_0  defaults        
                             1.6.0                np16py27_0  defaults         

```

My SQL problems seem to be related to api changes between v0.16 and v.0.17 of pandas. Where I am using pandas/sql Alchemy interface to connect to my MS SQL server the fix was easy. Outside pandas, SQL connection works fine hence the issue isnt as bad as initially thought.  However the current version of pandas (v0.16) breaks the code elsewhere and I would prefer to install the latest rather that having to use functions which are currently deprecated.

**Comment by mcg1969** [comment]
I'm guessing that the reason you can't install `pandas 0.17` is because the dependency relationships don't allow it. `conda` is now more strict about these things. For most users that's the right choice, but in your case it may not be. So what you may have to do is force-install a particular version of pandas.

**Comment by mcg1969** [comment]
As for the missing anaconda package: can you do a `conda list`? If it's not there, it's not there. If you followed my directions above to `conda remove --force anaconda`, then of course it wouldn't be there.

**Comment by acycliq** [comment]
Ah I see! Do you know if there is a way to force conda fetch a specific version please? When I do conda update -f pandas it picks up v16.2 instead of v0.17 which I would prefer.
Btw, I am on gitter now.

Thanks

iMacDimitris:~ Dimitris$ conda update -f pandas
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ...........

Package plan for installation in environment /Users/Dimitris/anaconda:

The following packages will be UPDATED:

    pandas: 0.16.2-np19py27_0 --> 0.16.2-np19py27_0

**Comment by acycliq** [comment]
Yes, i followed your directions and I removed the anaconda package by force. When I do a `conda list` I can see `anaconda-client` only. I thought however that the `conda update --all` would install anaconda back too.

**Comment by mcg1969** [comment]
No, anaconda is just a package like any other. Once it is removed it will not come back unless you reinstall it. And since you need to override the version enforcement anyway, you don't want it back.

I have to be honest I do not recall the exact syntax to install a specific version of pandas. It might be `conda install -f pandas=0.17` but you might have the go further and specify a build. And you're going to want to "pin" that version because conda will want to change it later.

Perhaps the Gitter crowd can help more than I here.

**Comment by Arn-O** [comment]
I will close the issue, there is no point to keep it open from my perspective. I have done a fresh install, by deleting the anaconda folder and installing the bundle from the download web page. All the packages are at the right level. Didn't check all, but at least numpy, matplotlib and pandas are OK.

To be noticed, I have tried to update ``conda``, and it has been updated from 3.9 to 4.0 (version 3.9 is listed on the anaconda package list).

**Comment by acycliq** [comment]
Michael, many thanks for all your help and advice. I dont want to waste your name, I will also do a fresh install and get anaconda 2.5.0.
Cheers

**Comment by mcg1969** [comment]
@acycliq, you aren't wasting my time at all. Package management is not easy, and as much as we test we need the experience of end users to really shake things out. It's why we do rapid release cycles and regular updates of conda. I hope the fresh install will help! 

@Arn-O, thanks again for posting the issue. I do think #2179 is going to go a long way towards fixing the issues you're seeing, but I'm glad you've found a good solution for yourself in the meanwhile.

**Comment by Arn-O** [comment]
Thank you @mcg1969 for the time.

**Comment by acycliq** [comment]
All good from my side too. Did a fresh install, checked everything and looks quite healthy (after some minor changes). Lots of thanks!

**Comment by kalefranz** [comment]
Should be fixed with #2183, which will go into `4.0.1` being released today.

**Comment by iskandr** [comment]
Still getting this with conda 4.0.5. Uninstalling anaconda doesn't help.

**Comment by zillurbmb51** [comment]
Hi,
I am having this problem for few days. I was trying to run "conda install -c asmeurer scitools" but it gave me specification conflict. Herewith some output of my commands. Thanks in advance. 
Best Regards
Zillur
[conda-info.txt](https://github.com/conda/conda/files/265328/conda-info.txt)
[conda-install-scitools.err.txt](https://github.com/conda/conda/files/265331/conda-install-scitools.err.txt)
[conda-list.txt](https://github.com/conda/conda/files/265329/conda-list.txt)
[conda-update-all.txt](https://github.com/conda/conda/files/265330/conda-update-all.txt)

**Comment by mcg1969** [comment]
In fact, that version of scitools is so old that it requires NumPy 1.7. I would recommend against using it and try and find another source---or perhaps even install it with `pip`.

**Comment by zillurbmb51** [comment]
Thank you very much. I have tried with pip. But got this:
 MacBook-Pro-6:mrbayes ZILLURRAHMAN$ pip install scitools
Collecting scitools
  Could not find a version that satisfies the requirement scitools (from versions: )
No matching distribution found for scitools

**Comment by mcg1969** [comment]
Let's take this over to your separate issue.

**Comment by aqikz** [comment]
I am just simply trying to add bioconda and fithic in miniconda3 Win x64 based, but so far I am lost, the published information and commands are not working.
error details attached, please help work due for Tuesday.
[error 1.txt](https://github.com/conda/conda/files/4567962/error.1.txt)
[error 2.txt](https://github.com/conda/conda/files/4567963/error.2.txt)
