### ISSUE TITLE
non-conda version on pythonpath broke conda.

### ISSUE THREAD

**Issue by enfascination** [conda/conda#2240]
I was doing a small simple install of a random library with conda's version of pip. Everything went south (console below) and now, I get strange errors when I do anything.  Even just typing "conda" goes haywire. The reason for the going south is clear: there was a collision with another install of Python on my machine. My PYTHONPATH, due to a fluke, was at the time incorrectly continuing to list the MacPorts version of Python 2.7 (I'm on OS X).  Less clear is how to fix things.  

I'm not sure this is an issue for github, but this url popped up, so maybe it is. Maybe this is an unrealistic feature request for "conda magicwand" or "conda undodisaster," or maybe conda shouldn't be this sensitive to such mistakes and this is a bug report.

Here is the output during an install just before things got weird. I knew something strange was happening when it started trying to upgrade numpy all of a sudden.
```
Collecting numpy (from numpy-stl==1.7.1)
  Downloading numpy-1.10.4-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 77kB/s
Requirement already up-to-date: nine in /Users/XXX/anaconda/envs/typehigh/lib/python3.5/site-packages (from numpy-stl==1.7.1)
Requirement already up-to-date: python-utils>=1.6.2 in /Users/XXX/anaconda/envs/typehigh/lib/python3.5/site-packages (from numpy-stl==1.7.1)
Installing collected packages: numpy, numpy-stl
  Found existing installation: numpy 1.10.2
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.10.2:
Exception:
Traceback (most recent call last):
  File "/Users/XXX/anaconda/envs/typehigh/lib/python3.5/shutil.py", line 538, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.10.2-py2.7.egg-info' -> '/var/folders/l_/g_8wzxmx2wq3mf30rzcjsnw40000gp/T/pip-carcnb8f-uninstall/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.10.2-py2.7.egg-info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 725, in install
    requirement.uninstall(auto_confirm=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 756, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 266, in renames
    shutil.move(old, new)
  File "/Users/XXX/anaconda/envs/typehigh/lib/python3.5/shutil.py", line 553, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.10.2-py2.7.egg-info'
```

Now, when I do anything I get strange errors.  Even just typing "conda" goes haywire:
```
usage: conda [-h] [-V] [--debug] command ...

conda is a tool for managing and deploying applications, environments and packages.   

Options:

positional arguments:
  command
    info         Display information about current conda install.
    help         Displays a list of available conda commands and their help
                 strings.
...
    convert      Various tools to convert conda packages. Takes a pure Python package build for
                 one platform and converts it to work on one or more other platforms, or
                 all.
    develop      Install a Python package in 'development mode'.
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
    env          positional arguments:
                   {attach,create,export,list,remove,upload,update}
                     attach              Embeds information describing your conda environment
                                         into the notebook metadata
                     create              Create an environment based on an environment file
                     export              Export a given environment
                     list                List the Conda environments
                     remove              Remove an environment
                     upload              Upload an environment to anaconda.org
                     update              Update the current environment based on environment
                                         file
Traceback (most recent call last):
  File "/Users/XXX/anaconda/bin/conda-index", line 5, in <module>
    sys.exit(main())
  File "/Users/XXX/anaconda/lib/python3.5/site-packages/conda_build/main_index.py", line 21, in main
    default=[os.getcwd()],
FileNotFoundError: [Errno 2] No such file or directory
failed: /Users/XXX/anaconda/bin/conda-index --help
    inspect      Tools for inspecting conda packages.
    metapackage  Tool for building conda metapackages.  A metapackage is a package with no
                 files, only metadata.  They are typically used to collect several packages
                 together into a single package via dependencies.
    pipbuild     *** This command is no longer supported.  It will be removed in a future release of conda-build. ***
                 The recommended way to build conda packages from packages on
                 PyPI is using conda skeleton pypi and conda build.
                 Tool for building conda packages using pip install.
 
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
    server       Anaconda Cloud command line manager
    sign         Tool for signing conda packages.  Signatures will be written alongside the
                 files as FILE.sig.
    skeleton     Generates a boilerplate/skeleton recipe, which you can then edit to create a
                 full recipe. Some simple skeleton recipes may not even need edits.
```

So does conda index:
```
Traceback (most recent call last):
  File "/Users/XXX/anaconda/bin/conda-index", line 5, in <module>
    sys.exit(main())
  File "/Users/XXX/anaconda/lib/python3.5/site-packages/conda_build/main_index.py", line 21, in main
    default=[os.getcwd()],
FileNotFoundError: [Errno 2] No such file or directory
```

Here is my conda info (which still works):
```
Current conda install:

             platform : osx-64
        conda version : 3.19.3
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/XXX/anaconda  (writable)
  default environment : /Users/XXX/anaconda/envs/typehigh
     envs directories : /Users/XXX/anaconda/envs
        package cache : /Users/XXX/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by kalefranz** [comment]
Try this...

    curl http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda3.sh
    bash ~/miniconda3.sh -bfp ~/anaconda
    conda update conda
    conda update --all

and see how far you get...

**Comment by enfascination** [comment]
Thank you for your response.  Depending how you measure, I either got very far or not at all. All of these commands completed, but they mixed errors with normal output and my problems from before remain.  The command "conda" mixes the same errors with output.  "conda index" still responds:
...
Traceback (most recent call last):
  File "/Users/sfrey/anaconda/bin/conda-index", line 5, in <module>
    sys.exit(main())
  File "/Users/sfrey/anaconda/lib/python3.5/site-packages/conda_build/main_index.py", line 21, in main
    default=[os.getcwd()],
FileNotFoundError: [Errno 2] No such file or directory
...
And running conda's version of pip still just gives:
...
The folder you are executing pip from can no longer be found.
...


As for the errors mixed in which each command you recommended: running the second command gives 
...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
PREFIX=/Users/XXX/anaconda

chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
...
then normal output and, last, a very long list of warnings that every file already exists.

"conda update conda" goes fine except for the same error appearing at the very beginning and very end of the output:
...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ....................
Package plan for installation in environment /Users/XXX/anaconda:

The following packages will be UPDATED:

    conda:      3.19.0-py35_0 --> 4.0.4-py35_0
    openssl:    1.0.2d-0      --> 1.0.2g-0
    pip:        7.1.2-py35_0  --> 8.1.0-py35_0
    requests:   2.9.0-py35_0  --> 2.9.1-py35_0
    setuptools: 18.8.1-py35_0 --> 20.2.2-py35_0
    sqlite:     3.8.4.1-1     --> 3.9.2-0
    wheel:      0.26.0-py35_1 --> 0.29.0-py35_0
    xz:         5.0.5-0       --> 5.0.5-1

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|################################################################################################################################| 100%
Linking packages ...
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory                                    |   0%
[      COMPLETE      ]|################################################################################################################################| 100%
...

"conda update --all" only gives the error in the very beginning of the output, and otherwise gives normal output.   


Thank you very much for your willingness to help.  Hopefully these errors make the problem obvious enough that you can find the solution, but not so obvious that I really should have been able to figure this out myself.

**Comment by kalefranz** [comment]
Try `cd ~`. Is your home directory still there and ok? Also `ls -al` should show your anaconda directory.

With the `cd` command, I'm guessing things are fixed. Or maybe with starting a new she'll?

**Comment by enfascination** [comment]
Ah, dumb. That did it!  

caveats: I did still get errors during the process, re: permissions.  
```
Traceback (most recent call last):
  File "/Users/XXX/anaconda/pkgs/conda-3.19.0-py35_0/lib/python3.5/site-packages/conda/install.py", line 832, in <module>
    main()
  File "/Users/XXX/anaconda/pkgs/conda-3.19.0-py35_0/lib/python3.5/site-packages/conda/install.py", line 818, in main
    link(pkgs_dir, prefix, dist, linktype)
  File "/Users/XXX/anaconda/pkgs/conda-3.19.0-py35_0/lib/python3.5/site-packages/conda/install.py", line 680, in link
    create_meta(prefix, dist, info_dir, meta_dict)
  File "/Users/XXX/anaconda/pkgs/conda-3.19.0-py35_0/lib/python3.5/site-packages/conda/install.py", line 314, in create_meta
    with open(join(meta_dir, dist + '.json'), 'w') as fo:
PermissionError: [Errno 13] Permission denied: '/Users/XXX/anaconda/conda-meta/requests-2.9.0-py35_0.json'
```
This file was just one of many owned by root. I think it shouldn't be that way since I've never used sudo with conda, until now — I got around that problem by running "sudo bash ~/miniconda3.sh -bfp ~/anaconda" immediately before reading that "You should avoid using sudo with Anaconda" (http://stackoverflow.com/questions/29088972/how-do-i-fix-my-anaconda-python-distribution). Now almost everything is owned by root.  Any advice on fixing permissions or am I looking at a total reinstall?  Will "chown -R me ~/anaconda" do the trick or are things more complicated than that?

**Comment by kalefranz** [comment]
Yeah, with sudo

   sudo chown -R $USER:$USER ~/anaconda 

is probably exactly what you want.
