### ISSUE TITLE
activation not working for root env

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2498]

**Comment by kalefranz** [comment]
@mingwandroid This ticket is now addressed by #2501, correct?

**Comment by mingwandroid** [comment]
Well, activation is still not working for the root env, but it doesn't matter for the MSYS2 packages, I'd say. It's still a good goal to have the package specific activate and deactivate scripts be run at the appropriate time.

**Comment by kalefranz** [comment]
`source activate root` on OS X seems to work as expected for me.

**Comment by kalefranz** [comment]
@mingwandroid What are the details/steps to reproduce the issue on Windows?

**Comment by mingwandroid** [comment]
Right, it's working for me too on OS X, I think I had the wrong end of the stick and the issue is just that we don't emit `source activate root` into `.bashrc` when the installers install Anaconda or Miniconda.

I will fake up a Windows activate.bat now and report back.

**Comment by mingwandroid** [comment]
I've setup a test-case for this, but while trying it I ran into another, IMHO, blocker issue for 4.1.

Build any package locally, then install with:
`conda install pkg -c local`
.. then try to re-install with:
`conda install pkg -c local --force`
.. and you'll run into:
```
Traceback (most recent call last):
  File "C:\Users\ray\mc3-x64-3.5\Scripts\conda-script.py", line 9, in <module>
    load_entry_point('conda==0.0.0', 'console_scripts', 'conda')()
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\cli\install.py", line 309, in install
    update_deps=args.update_deps)
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\plan.py", line 450, in install_actions
    force=force, always_copy=always_copy)
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\plan.py", line 309, in ensure_linked_actions
    elif install.try_hard_link(fetched_dir, prefix, dist):
  File "C:\Users\ray\mc3-x64-3.5\lib\site-packages\conda-0.0.0-py3.5.egg\conda\install.py", line 558, in try_hard_link
    assert isfile(src), src
AssertionError: C:\Users\ray\activate-test-1.0.0-0\info\index.json
```

**Comment by mingwandroid** [comment]
I've submitted something for this problem now: https://github.com/conda/conda/pull/2507

**Comment by mingwandroid** [comment]
OK, activate.bat gets run for Windows when I do `activate root` which is good. The only problem then is that we don't emit `activate root` to any startup / login scripts nor do we make a point of telling people to activate their root environments.

**Comment by kalefranz** [comment]
> The only problem then is that we don't emit activate root to any startup / login scripts nor do we make a point of telling people to activate their root environments.

I don't think we ever have done this.  I have a full schedule today, but let's jump on a video chat tomorrow morning about this. I don't think it needs to block 4.1.0rc3 though, do you?

**Comment by mingwandroid** [comment]
You are right we haven't done it yet and IMHO it's definitely not a blocker for 4.1. I think @msarahan would like to take part too and he's not around tomorrow (AFAIK). It's something we should look to address after 4.1 for sure as activate scripts that only work in sub-envs are weird at best.
