### ISSUE TITLE
Anaconda Navigator does not invoke installed environment 

### ISSUE THREAD

**Issue by sushmit86** [conda/conda#2728]
I am using  conda 4.1.0, 

I created another environment called we_moduletest1 which has a package we_module installed
when I invoke the jupyter notebook using navigator (see attached screenshot1)

<img width="753" alt="screenshot1" src="https://cloud.githubusercontent.com/assets/5600498/16131710/91a09c10-33dd-11e6-81c8-54eb8a34677a.png">

  the notebook is not able to activate the environment. When I try to import we_module it fails ( see attached screenshot2).
![screenshot2](https://cloud.githubusercontent.com/assets/5600498/16131963/02c9efd0-33df-11e6-9132-ae8323adbe1e.png)

However when I do the following 1) Open terminal 2) source activate we_moduletest1 3) jupyter notebook then I am able to import the package

Also I am able to import the package when I invoke ipython shell from navigator ( see attached screenshot 3)
<img width="852" alt="screenshot3" src="https://cloud.githubusercontent.com/assets/5600498/16131965/073dc3a2-33df-11e6-8c44-0b5f1b1d1fe9.png">

**Comment by kalefranz** [comment]
@goanpeca Where's the best place to file this issue?

**Comment by goanpeca** [comment]
this bug is fixed in the new version to be rekeased in 2 weeks

**Comment by goanpeca** [comment]
anaconda-issues is the usual repo for this

**Comment by kalefranz** [comment]
Thanks @goanpeca.  Closing as fixed in a future release.

**Comment by thepurpleowl** [comment]
Even in the future version with respect to this post, i.e, conda version 4.3.13 the same problem remains if the conda is installed for all users but another environment is created by a specific user.
