### ISSUE TITLE
Config for `conda-build/root-dir` ignored

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#3744]
We set `conda-build/root-dir` at conda-forge so that we can share packages that are built with the Docker container and also set a place for them to upload. Using the most recent release of `4.2.11`, appears to not respect this.

**Comment by jakirkham** [comment]
Temporary workaround seems to be switching to `4.1.12` where the problem goes away.

**Comment by jakirkham** [comment]
Am able to reproduce this all the way back to `conda` version `4.2.7`.

Was unable to confirm with `conda` version `4.2.6` due to other bugs. In particular, `4.2.6` fails to import `move_path_to_trash`, which blocks `conda-build` from even running.

**Comment by jakirkham** [comment]
cc @msarahan

**Comment by kalefranz** [comment]
This is related to https://github.com/conda/conda/issues/3741 and https://github.com/conda/conda/issues/3732.  Fix forthcoming.

**Comment by kalefranz** [comment]
fixed with #3747

**Comment by jakirkham** [comment]
We are still [seeing]( https://circleci.com/gh/conda-forge/blosc-feedstock/20 ) this problem in `conda` version `4.2.12`, which should have the fix, @kalefranz . Could we please reopen this issue and take another look?

cc @jjhelmus

**Comment by jjhelmus** [comment]
Yes, I am still seeing this issue with conda `4.2.12`.  As an example:

```
~$ cat ~/.condarc
conda-build:
  root-dir: ~/conda-builds
~$ conda config --debug --get
unknown key conda-build
~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.7
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/jhelmus/anaconda  (writable)
    default environment : /home/jhelmus/anaconda
       envs directories : /home/jhelmus/anaconda/envs
          package cache : /home/jhelmus/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jhelmus/.condarc
           offline mode : False
```

The conda-build: syntax is given in the [conda build configuration section] (http://conda.pydata.org/docs/config.html#conda-build-configuration) of the conda documentation.

**Comment by msarahan** [comment]
I'm inclined to say that this is a bug in conda build, until proven
otherwise. Will investigate.

**Comment by jjhelmus** [comment]
@msarahan I agree:

```
~$ cat ~/.condarc
conda-build:
    root-dir: ~/conda-builds
~$ conda build --version
conda-build 1.21.14+0.g4dfebe9.dirty
~$ python -c "from conda_build.config import Config; print(Config().croot)"
/home/jhelmus/conda-builds
~$ conda install conda-build
...
~$ conda build --version
conda-build 2.0.8
~$ python -c "from conda_build.config import Config; print(Config().croot)"
/home/jhelmus/anaconda/conda-bld
```

**Comment by jjhelmus** [comment]
Although it is some kind of odd interplay between `conda` and `conda-build`:

```
~$ conda --version
conda 4.2.12
~$ conda build --version
conda-build 1.21.14+0.g4dfebe9.dirty
~$ python -c "from conda_build.config import Config; print(Config().croot)"
/home/jhelmus/anaconda/conda-bld
```

It seems that conda 4.1.x AND conda build 1.x are needed for the conda-build/root-dir configuration to work.  Upgrading either breaks the configuration.

**Comment by jjhelmus** [comment]
Sorry, one more update.  I'm back to the stance that this is a conda issue:

```
conda 4.1.12
~$ python -c "import conda.config as cc; print(cc.rc.get('conda-build', {}).get('root-dir'))"
~/conda-builds
...
conda 4.2.12
~$ python -c "import conda.config as cc; print(cc.rc.get('conda-build', {}).get('root-dir'))"
None
```

**Comment by msarahan** [comment]
Thanks @jjhelmus - given that simple test, I agree that this is a conda issue.  I'm reopening this issue accordingly.

@kalefranz please comment - how did you test this for #3747 ?

**Comment by kalefranz** [comment]
Fixed with #3875

**Comment by jjhelmus** [comment]
Can confirm that this is fixed in conda `4.2.13`.  Thanks for the help @msarahan and the fix @kalefranz!
