### ISSUE TITLE
tar.gz automatically uncompressed by conda -> conda-build md5 check KO

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#3798]
_From @afeblot on October 25, 2016 20:36_

With conda 4.2.11 (and 4.2.10) and conda build 2.0.7 (and 2.0.6), 

Building the zlib recipe from conda-recipe fails with:

MD5 mismatch: '1142191120b845f4ed8c8c17455420ac' != '44d667c142d7cda120332623eab69f40'

It seems conda:fetch.py:download() (thanks to requests) is automatically gunzipping the archive, and checks the md5 of the 2.7 uncompressed .tar (even though the created file is still named .tar.gz), whereas the md5 specified in the recipe is obviously the one of the original compressed archive.

I don't know which behavior is wanted for download(), but it's currently not consistent with conda-build.

_Copied from original issue: conda/conda-build#1483_

**Comment by kalefranz** [comment]
_From @msarahan on November 3, 2016 14:53_

Thanks for hunting this down.  This has been very confusing.  I think the right answer is that our use of requests should not be automatically gunzipping things, and I'll try to figure out how to make that happen.

**Comment by kalefranz** [comment]
_From @msarahan on November 3, 2016 14:53_

CC @kalefranz

**Comment by kalefranz** [comment]
_From @msarahan on November 3, 2016 14:58_

http://stackoverflow.com/questions/25749345/how-to-download-gz-files-with-requests-in-python-without-decoding-it

**Comment by kalefranz** [comment]
Yup! Thanks @afeblot!

With things being gzippes all the time for web transfer, we usually want this behavior. For example when downloading the plaintext repodata.json file, the web server will typically gzip it. 

I think the solution is that if a URL ends with .gz, we turn unzip off. We also trust that the web server hasn't taken the liberty of adding an extra gzip round. (gzipping an already gzipped file)

**Comment by kalefranz** [comment]
Looks like CHANGELOG  `2015-02-24 3.9.1` comments

> don't let requests decode gz files when downloaded

**Comment by kalefranz** [comment]
Could help: http://docs.python-requests.org/en/latest/api/?highlight=raw#requests.Response.raw

**Comment by kalefranz** [comment]
possibly related: https://github.com/conda/conda/pull/2755

**Comment by kalefranz** [comment]
@msarahan #2755 is the only thing that's changed "recently" that could possibly affect this (that I know of)

**Comment by mwiebe** [comment]
This looks like a duplicate of https://github.com/conda/conda/issues/3540

**Comment by mwiebe** [comment]
This bug appears to do the same thing to http://www.robertnz.net/ftp/newmat10.tar.gz

**Comment by kalefranz** [comment]
We've done a lot of work to clean this up.  Should be fixed in 4.3, if not 4.2.  Possibly related discussion in https://github.com/conda/conda/pull/3991.

**Comment by afeblot** [comment]
/me happy to have contributed to a better conda ;-)

**Comment by isuruf** [comment]
This issue is back https://github.com/conda/conda-build/issues/3799
