### ISSUE TITLE
Unable to set conda-build.root-dir with config

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#4302]
Not sure the right way to do this, but it looks like there might not be any right way ATM. I would like to be able to use `conda config` to get the following added to my `.condarc` file.

```yaml
conda-build:
    root-dir: /tmp
```

If I try to set `conda-build.root-dir` with `conda config`, I get this error.

```bash
$ conda config --set "conda-build.root-dir" "/tmp"


CondaValueError: Value error: Error key must be one of add_anaconda_token, shortcuts, add_pip_as_python_dependency, ssl_verify, client_tls_cert, binstar_upload, use_pip, add_binstar_token, always_copy, always_yes, client_tls_cert_key, channel_alias, changeps1, channel_priority, show_channel_urls, update_dependencies, allow_softlinks, anaconda_upload, offline, allow_other_channels, auto_update_conda, not conda-build.root-dir


```

**Comment by jakirkham** [comment]
cc @msarahan

**Comment by kalefranz** [comment]
`conda config --set` doesn't currently support map-type parameters.

**Comment by goanpeca** [comment]
It should be possible to do

`conda config --set proxy_servers.http 1.2.3.4:4004`

and

`conda config --get proxy_servers.http`

**Comment by kalefranz** [comment]
resolved with #5310

**Comment by teake** [comment]
This still doesn't work for me (on conda 4.5.12, conda-build 3.17.6, both CentOS and macOS):

```shell
$ conda config --set "conda-build.root-dir" "/tmp"

CondaValueError: Key 'conda-build' is not a known primitive parameter.

```
