### ISSUE TITLE
Import error after "conda install numpy"

### ISSUE THREAD

**Issue by astrojuanlu** [conda/conda#444]
I tried "conda install numpy" in a new environment under Arch Linux, and after a successful installation this is what I got:

```
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/Development/Python/conda_test/venv/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
    import add_newdocs
  File "/home/juanlu/Development/Python/conda_test/venv/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/home/juanlu/Development/Python/conda_test/venv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 13, in <module>
    from polynomial import *
  File "/home/juanlu/Development/Python/conda_test/venv/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 17, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/juanlu/Development/Python/conda_test/venv/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 48, in <module>
    from linalg import *
  File "/home/juanlu/Development/Python/conda_test/venv/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 23, in <module>
    from numpy.linalg import lapack_lite
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

This in turn prevents me from using any scientific Python package. It might be an error in the configuration, because this is what I have in my computer:

```
$ ls /usr/lib/libgfortran.so*
/usr/lib/libgfortran.so    /usr/lib/libgfortran.so.3.0.0
/usr/lib/libgfortran.so.3
```

**Comment by SteveDiamond** [comment]
I'm having the same issue now on Travis CI (see https://travis-ci.org/cvxgrp/cvxpy/jobs/80546655). It worked yesterday. Is there anything Travis could have changed to cause this failure?

**Comment by KelSolaar** [comment]
Same here since yesterday: https://travis-ci.org/colour-science/colour/jobs/80611854, I'm clueless from initial inspection.

**Comment by asmeurer** [comment]
I think this is a problem on our side, which we are working to fix.

**Comment by ilanschnell** [comment]
The fix is uploaded (adding the `libgfortran` dependency to the ATLAS linked numpy packages), the problem should be resolved.

**Comment by KelSolaar** [comment]
@ilanschnell Anything to do on our end? I relaunched the build but it is still crashing with the same error.

**Comment by nehalecky** [comment]
I've hit same error recently, however, through a `from scipy import stats` call. Downgrading to scipy 0.15.1 resolved the issue. I suspect they are related to the the same error encountered in this thread, but please let me know if I should open a new issue for this. Thanks :)

```python

In [2]: from scipy import stats
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-9d55e67ee92d> in <module>()
----> 1 from scipy import stats

/home/vagrant/miniconda-3.16.0/envs/cs-7641-machine-learning/lib/python2.7/site-packages/scipy/stats/__init__.py in <module>()
    319 from __future__ import division, print_function, absolute_import
    320 
--> 321 from .stats import *
    322 from .distributions import *
    323 from .morestats import *

/home/vagrant/miniconda-3.16.0/envs/cs-7641-machine-learning/lib/python2.7/site-packages/scipy/stats/stats.py in <module>()
    178 from scipy._lib.six import callable, string_types
    179 from numpy import array, asarray, ma, zeros
--> 180 import scipy.special as special
    181 import scipy.linalg as linalg
    182 import numpy as np

/home/vagrant/miniconda-3.16.0/envs/cs-7641-machine-learning/lib/python2.7/site-packages/scipy/special/__init__.py in <module>()
    599 from __future__ import division, print_function, absolute_import
    600 
--> 601 from ._ufuncs import *
    602 
    603 from .basic import *

ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory
```

Fix with 

```bash
$ conda install scipy=0.15.1
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/vagrant/miniconda-3.16.0/envs/test:

The following packages will be DOWNGRADED:

    scipy: 0.16.0-np19py27_1 --> 0.15.1-np19py27_0

Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###############################################################################################################################################################################| 100%
```
In IPython

```python
In [1]: from scipy import stats

In [2]: stats.
Display all 231 possibilities? (y or n)
stats.Tester                stats.circmean              stats.frechet_l             stats.johnsonsu             stats.mstats                stats.probplot              stats.threshold
stats.absolute_import       stats.circstd               stats.frechet_r             stats.kde                   
```

**Comment by lesteve** [comment]
@KelSolaar it seems like numpy 1.8.1 is still missing the libgfortran dependency. Using 1.8.2 fixed it in our case.

For completeness, [here](https://travis-ci.org/lesteve/nilearn/jobs/81532982) is an example of Travis failure and [here](https://travis-ci.org/lesteve/nilearn/jobs/81537182) is the log of the Travis successful build after the work-around.

**Comment by ilanschnell** [comment]
Yes, I only added the missing dependency to the latest numpy x.x versions.  That is: 1.5.1, 1.6.2, 1.7.1, 1.8.2, 1.9.2,

**Comment by lesteve** [comment]
> Yes, I only added the missing dependency to the latest numpy x.x versions. That is: 1.5.1, 1.6.2, 1.7.1, 1.8.2, 1.9.2.

Just curious, will the libgfortran dependency added to the other numpy versions eventually ? Maybe it just wasn't deemed worth the pain. Just for completeness, numpy 1.8.1 is in Ubuntu 14.04 and I can imagine my future self slightly surprised if I ever want to do conda install numpy=1.8.1.

**Comment by moorepants** [comment]
I'm getting this error with numpy 1.7.0:

https://travis-ci.org/pydy/pydy/jobs/83943357

Can this dependency be added for all versions of NumPy 1.6+?
