### ISSUE TITLE
Ctrl+C does not kill gcc

### ISSUE THREAD

**Issue by msarahan** [conda/conda#4443]
@sscherfke commented on [Fri Jan 27 2017](https://github.com/conda/conda-build/issues/1705)

If I build a C-lib with conda-build, I can no longer cancel the build using `Ctrl-C`. Conda itself will die, but the compiler processes will continue to run. It looks like the signals are not (or no longer) forwared to all sub processes.

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.6.0.final.0
       requests version : 2.12.5
             user-agent : conda/4.3.8 requests/2.12.5 CPython/3.6.0 Linux/4.8.15-200.fc24.x86_64 Fedora/24 glibc/2.23
```

---

@msarahan commented on [Fri Jan 27 2017](https://github.com/conda/conda-build/issues/1705#issuecomment-275667441)

Confirmed.  Switching to conda 4.2.x fixes it for me.  Leaving this issue here until I can isolate it further.

**Comment by msarahan** [comment]
Copied from conda-build.  I'm not sure yet whether this is a bug in conda or conda-build.  In my searches through conda's code, there were no changes to code involving KeyboardInterrupt between 4.2.x and 4.3.x.  Still, this bug is present with conda 4.3.x and not 4.2.x, so it seems to be some exception swallowing added in 4.3.x.

**Comment by kalefranz** [comment]
Yes, there's a signal handler in 4.3.  It's invoked and registered anytime logging is also configured.

https://github.com/conda/conda/blob/4.3.x/conda/gateways/signals.py
https://github.com/conda/conda/blob/4.3.x/conda/gateways/__init__.py

I've created a pull request to handle signal forwarding better: https://github.com/conda/conda/pull/4447

I've based what I'm doing in the PR on http://stackoverflow.com/questions/13593223/making-sure-a-python-script-with-subprocesses-dies-on-sigint

**Comment by sscherfke** [comment]
Is this fixed in 4.3.9? It looks like #4447 landed in that version.

**Comment by msarahan** [comment]
@kalefranz this is still an issue with conda 4.3.11.  I don't understand your response, though - is this something you're working on fixing in conda, or is it like logging where it needs some fix on the conda-build side too?

**Comment by kalefranz** [comment]
related: https://github.com/conda/conda/issues/4503

**Comment by msarahan** [comment]
@kalefranz can you please update this issue with current status?  I've just received a report from Samsung that they are using the latest conda from canary and are still seeing this issue.

**Comment by kalefranz** [comment]
Full history of this issue can be tracked from https://github.com/conda/conda/pull/5133#issuecomment-296795452 I think.  There's also https://github.com/conda/conda/issues/5135.

The only reason conda needs to deal with signal handlers at all is to be able to attempt a rollback during an install transaction if a signal is sent mid-transaction.

I've spent time with http://stackoverflow.com/questions/13593223/making-sure-a-python-script-with-subprocesses-dies-on-sigint and implemented pretty much every suggestion in there.  If anybody has any more ideas, please share!

**Comment by kalefranz** [comment]
As in that stack overflow link, whenever conda-build subprocesses, it should also be sure it's forwarding signals to child processes, apparently by setting stdin as PIPE.

**Comment by kalefranz** [comment]
conda-build is also free to use [`conda.exports.subprocess_call`](https://github.com/conda/conda/blob/master/conda/exports.py#L129) that implements all those suggestions in that stackoverflow comment.

https://github.com/conda/conda/blob/master/conda/gateways/subprocess.py#L38-L60

**Comment by kalefranz** [comment]
@msarahan Have we made progress on this at all in recent versions of conda?  Do you feel like it's getting better at least?

**Comment by kalefranz** [comment]
I'm going to close this issue for now.  For the conda-build case in particular, I think it should mostly be solved with registering signal handlers only right before executing unlink-link transactions, and the deregistering them afterward.  In the initial implementation for signal handling, conda registered signal handlers on import, and then kept them registered.
