### ISSUE TITLE
root environment is always writable

### ISSUE THREAD

**Issue by hartzell** [conda/conda#4888]
I'm assembling a [Spack](https://github.com/llnl/spack) package for miniconda.

I'd like to treat the resulting installation as "read only" -- in particular, environments installed by users shouldn't end up in the root environment.

This bit in the "envs_dirs" section of [the documentation about centralized installation](https://conda.io/docs/install/central.html) :
> Specify directories in which environments are located. If this key is set, the root prefix envs_dir is not used unless explicitly included. This key also determines where the package caches will be located.

tells me that if I set a value for `envs_dir` then the one in the root prefix will not be used.

But, this .condarc in the root environment directory:

```
envs_dirs:
  - ~/.conda/envs
```

produces this output in `conda info`:

```
...
       envs directories : /home/users/hartzelg/.conda/envs
                          /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/envs
```

I've seen other mention that if the root environment is not writable then it is not included in envs directories list.

I have been unable to convince `conda` that the root env. directory is not writable.

I've chmod'ed the root directory itself to `555`.

Then I figured out that it was actually testing `.../conda-meta/history` so I chmod'ed that `444` and for good measure chmod'ed `.../conda-meta` to `555`.

With these changes, the root environment is still reported as writable.

In desperation, I hacked the definition of `root_writable` in `context/base/context.py` to print out some extra info.

```python
    @property
    def root_writable(self):
        from ..gateways.disk.test import prefix_is_writable
        print("in root_writable, self.root_prefix is: %s" % self.root_prefix)
        print("in root_writable, prefix_is_writable(self.root_prefix) is: %s" % prefix_is_writable(self.root_prefix))
        return prefix_is_writable(self.root_prefix)
```

I also added a debug statement to `file_path_is_writable` in `gateways/disk/test.py`

```python
def file_path_is_writable(path):
    log.debug("In file_path_is_writable: %s", access(path, W_OK))
    if isdir(dirname(path)):
```

and finally added a print statement to `cli/main_info.py` just before it dumps out the info:

```python
        print("In info_dict, root_writable is: %s" %info_dict['root_writable'])
        info_dict['_rtwro'] = ('writable' if info_dict['root_writable'] else
                               'read only')
        print("""\
```

Here's the resulting output:

```
$ conda info --debug
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
in root_writable, prefix_is_writable(self.root_prefix) is: True
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
DEBUG conda.gateways.disk.test:prefix_is_writable(58): testing write access for prefix '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq' using path '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(21): In file_path_is_writable: False
in root_writable, prefix_is_writable(self.root_prefix) is: True
DEBUG conda.gateways.disk.test:prefix_is_writable(58): testing write access for prefix '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq' using path '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(21): In file_path_is_writable: False
in root_writable, self.root_prefix is: /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
DEBUG conda.gateways.disk.test:prefix_is_writable(58): testing write access for prefix '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq' using path '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(21): In file_path_is_writable: False
in root_writable, prefix_is_writable(self.root_prefix) is: True
DEBUG conda.gateways.disk.test:prefix_is_writable(58): testing write access for prefix '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq' using path '/remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/conda-meta/history'
DEBUG conda.gateways.disk.test:file_path_is_writable(21): In file_path_is_writable: False
In info_dict, root_writable is: True
Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq  (writable)
    default environment : /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
       envs directories : /home/users/hartzelg/.conda/envs
                          /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/envs
          package cache : /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/pkgs
                          /home/users/hartzelg/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-229.el7.x86_64 CentOS Linux/7.1.1503 glibc/2.17
                UID:GID : 84348:20
```

This confuses me greatly:

1. There seem to be many invocations of `prefix_is_writable()` from `root_writable()` that return `True` without ever actually seeming to call `prefix_is_writable()`.
2. When I do see `prefix_is_writable()` get called it should return `False`, yet `root_writable()` is reporting `True`.

How can I ensure that end users can't write into the root environment?

**Comment by kalefranz** [comment]
I think this is already fixed in 4.3.13.  Actually 4.3.14 is out now.  Mind trying with one of the newer patch versions?

**Comment by kalefranz** [comment]
You found correctly that we're keying off of the `conda-meta/history` file as a proxy for environment permissions.  Conda has always tried to infer permissions based on directory permissions in the past, and that just doesn't work.  I think 4.3.13 is *finally* where we got all the kinks worked out around this.

**Comment by hartzell** [comment]
Thanks for the quick followup!

4.3.11 is the latest version that I see here: https://repo.continuum.io/miniconda/

Is there somewhere else from which I should be pulling the file?

**Comment by hartzell** [comment]
After making the various files and directories writable again, I used `conda update conda` to update to 4.3.14.

Then I made the canary file read-only.

```
hartzelg@rpbuchop002:spack (package/miniconda2 +)$ chmod 444 /remote/home/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/conda-meta/history
hartzelg@rpbuchop002:spack (package/miniconda2 +)$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq  (read only)
    default environment : /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq
       envs directories : /home/users/hartzelg/.conda/envs
                          /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/envs
          package cache : /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/pkgs
                          /home/users/hartzelg/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-229.el7.x86_64 CentOS Linux/7.1.1503 glibc/2.17
                UID:GID : 84348:20

hartzelg@rpbuchop002:spack (package/miniconda2 +)$
```

Now the root environment is correctly marked `read-only` but the root environment is still listed in the list of envs directories.  It's second because of the .condarc file and its envs_var statement.  If I remove that file then I get:

```
...
       envs directories : /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/envs
                          /home/users/hartzelg/.conda/envs
...
```

and things still get written to the root environment.

```
hartzelg@rpbuchop002:miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq (package/miniconda2 +)$ conda create --name snowflakes biopython
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/users/hartzelg/tmp/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.3/miniconda2-4.3.11-vseza2bw4ufem7htzv4jltbvxuzglbmq/envs/snowflakes:

```

**Comment by kalefranz** [comment]
Well we're making progress at least :)

There are, or soon will be, three canary files.  `conda-meta/history`, `pkgs/urls.txt`, and `envs/catalog.json`.  That last doesn't exist in shipped code yet, so we're using `pkgs/urls.txt` right beside it for now.  Try changing the permissions of that file too.

**Comment by kalefranz** [comment]
I general, I think things work fine if your install-from-scratch process is something like

    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda3.sh
    sudo /bin/bash /tmp/miniconda3.sh -bfp /opt/conda
    sudo /opt/conda/bin/conda update conda
    export PATH="/opt/conda/bin:$PATH"

where I've used `/opt/conda` as the install location.  Doesn't matter where you put it though.

**Comment by mingwandroid** [comment]
`source /opt/conda/bin activate` please!

We need to get away from conflating env activation with PATH modification. Yes they often are the same but when they aren't things don't work.

**Comment by hartzell** [comment]
> I think things work fine if your install-from-scratch process is something like [...]

Unfortunately, that's not true.

When Spack installs things, they often end up in a fairly deep tree (spack includes various metadata in the path name).  Depending on where the tree is rooted, this can cause the `#!` header line of various things to become "too long".

Spack catches this and fixes it when it installs the package.

These fixes work fine for the `conda` that Spack installed, but when conda comes along and updates it the new copies haven't had their #! properly twiddled.

**Perhaps even more importantly**, the process above isn't repeatable.  Who knows what '...latest...' refers to, and who knows what '... update conda' installs?  The spack package tracks the digest/signature for the distro, every time you roll it will generate an error/headache (I'm looking at *you*, texlive...).  

**The versioned installers are really important.**

**Comment by hartzell** [comment]
Making `conda-meta/history` read-only is sufficient to make `conda info` report that the "root environment" is "read only".

The problem that is, even when the root environment is "read only" the `/path/to/root/environment/envs` directory is still on the "envs directories" list.  The bit of docs that I quoted up at the very top really really makes it sounds as if when the "root environment" is read-only then it will not be included on the "envs directories" list (and therefore won't be used for installations.

Just to be sure, I also made `pkgs/urls.txt` read-only and that did not change the situation.

**Comment by hartzell** [comment]
This has been addressed in newer releases.

**Comment by Wilfred** [comment]
I can still reproduce this with anaconda 5.0.0.1 and conda 4.3.27.

I did the following:

```
$ chmod ugo-w conda-meta/history
$ chmod ugo-w pkgs/urls.txt
$ cat .condarc
auto_update_conda: False
envs_dirs:
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /shared/anaconda3/5.0.0.1  (read only)
    default environment : /shared/anaconda3/5.0.0.1
       envs directories : /users/wilfred/.conda/envs
                          /shared/anaconda3/5.0.0.1/envs
          package cache : /shared/anaconda3/5.0.0.1/pkgs
                          /users/wilfred/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /shared/anaconda3/5.0.0.1/.condarc
            config file : /shared/anaconda3/5.0.0.1/.condarc
             netrc file : /users/wilfred/.netrc
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Linux/3.10.0-514.10.2.el7.x86_64 CentOS Linux/7.3.1611 glibc/2.17
                UID:GID : 111405:28
```

Should `/shared/anaconda3/5.0.0.1/envs` be in the envs directories list? I couldn't see any discussion of read-only environments on https://conda.io/docs/user-guide/configuration/admin-multi-user-install.html and I haven't spotted any other relevant docs.

**Comment by kalefranz** [comment]
> The problem that is, even when the root environment is "read only" the /path/to/root/environment/envs directory is still on the "envs directories" list.

> Should /shared/anaconda3/5.0.0.1/envs be in the envs directories list?

Yes.  By default, there are two locations in the envs directories list.  One associated with the root environment and one associated with the current user's home environment.  The root environment is preferred if it's writable, otherwise we assume that the user's home environment is writable.  Just like the package cache, the requirement is that at least one of these directories is writable, for the creation of new environments.

However, read-only locations are still in the list.  Read-only environments can still be activated.  They just can't be installed into.
