### ISSUE TITLE
Fresh install of conda owned by root fails to allow standard users to make new environments

### ISSUE THREAD

**Issue by Wildcarde** [conda/conda#5507]
Setup:
Fresh install on a centos 7.3 OS of the latest anaconda x86 python 2.7 from the main website
Anaconda installed by root into /opt/anaconda
User on system has `export PATH=/opt/anaconda/bin:$PATH` added to the end of their .bash_profile file.

Results in (this is run as a local non root user on the machine):
```
conda create --name=psiturk python=2.7 pip anaconda
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/rmasis/.conda/envs/psiturk:

The following NEW packages will be INSTALLED:
...

anaconda-4.4.0 100% |#############################################################################################################################################################################################| Time: 0:00:00  12.63 MB/s
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::dbus-1.10.10-0'.
IOError(13, 'Permission denied')
Attempting to roll back.


IOError(13, 'Permission denied')
```

**Comment by tyler-thetyrant** [comment]
I ran the same command in a clean CentOS7 container with a fresh Anaconda install, but I wasn't able to reproduce the error. 
Can you provide more context and paste your `conda info` command?

**Comment by tyler-thetyrant** [comment]
Also conda does not require root privileges.

**Comment by Wildcarde** [comment]
I'll have to make a new VM in order to test this at this point, I made the user the owner of the folder as a work around on the systems I setup yesterday. We install anaconda's root environment as root so it's immutable to the end user but they can make their own variants if they wish to in their own folders. In the specific install I'm doing here the reason being so we know that there is a good working unbreakable environment for them to build off of. On other systems we do it because those root versions are installed in a central NFS mount accessible via a 'module load' command, allowing us to craft environments for researchers to use that they can't break and can point to for new researchers to use when deploying code or are just getting started with our systems.

**Comment by wkerzendorf** [comment]
we have the same problem.

**Comment by nehaljwani** [comment]
@tyler-thetyrant I was able to reproduce this using a docker container for CentOS7. 
Steps to reproduce:
```bash
[nwani@somemachine] mkdir fakenfs
[nwani@somemachine] sudo docker run -it --rm -v $PWD/fakenfs:/opt centos:7 /bin/bash
[root@c5ed33824e46 /] cd
[root@c5ed33824e46 ~] curl -Lso Miniconda3-4.3.21-Linux-x86_64.sh https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh
[root@c5ed33824e46 ~] yum install -y bzip2
[root@c5ed33824e46 ~] bash Miniconda3-4.3.21-Linux-x86_64.sh -bp /opt/anaconda
[root@c5ed33824e46 ~] /opt/anaconda/bin/conda install dbus
[root@c5ed33824e46 ~] useradd -m testuser
[root@c5ed33824e46 ~] su - testuser
[testuser@c5ed33824e46 ~] /opt/anaconda/bin/conda create --name=psiturk python=2.7 dbus -vvv
```

The exact trackeback is:

```bash
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda  (read only)
    default environment : /opt/anaconda
       envs directories : /home/testuser/.conda/envs
                          /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
                          /home/testuser/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-78-generic CentOS Linux/7.3.1611 glibc/2.17
                UID:GID : 1000:1000

`$ /opt/anaconda/bin/conda create --name=psiturk python=2.7 dbus -vvv`




    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 256, in create_link
        link(src, dst)
    OSError: [Errno 18] Invalid cross-device link: '/opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh' -> '/home/testuser/.conda/envs/psiturk/bin/.dbus-post-link.sh'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 326, in _execute_actions
        action.execute()
      File "/opt/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 245, in execute
        force=context.force)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 262, in create_link
        copy(src, dst)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 216, in copy
        _do_copy(src, dst)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 221, in _do_copy
        shutil_copy(src, dst)
      File "/opt/anaconda/lib/python3.6/shutil.py", line 235, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/opt/anaconda/lib/python3.6/shutil.py", line 114, in copyfile
        with open(src, 'rb') as fsrc:
    PermissionError: [Errno 13] Permission denied: '/opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh'


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/opt/anaconda/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/opt/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh'
```

**Comment by nehaljwani** [comment]
The problem occurs because no other than root user has access to read the these two files:
```bash
[root@40b7f7d32436 ~] ls -l /opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh
-rwxr-x--- 2 root root 766 Sep 13  2016 /opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh

[root@40b7f7d32436 ~] ls -l /opt/anaconda/pkgs/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper
-rwxr-x--- 1 root root 176268 Sep 13  2016 /opt/anaconda/pkgs/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper
```
Workaround is simple. As root user, grant read privileges. 
```bash
[root@40b7f7d32436 ~] chmod +r /opt/anaconda/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh
[root@40b7f7d32436 ~] chmod +r /opt/anaconda/pkgs/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper
```
@kalefranz If this was not intentional while creating the dbus package, this could be a packaging bug.

**Comment by slavoutich** [comment]
I don't think @nehaljwani is completely right. For me problem appears also without dbus, in the case of pure empty environment setup (see [the output](https://github.com/conda/conda/files/1068713/env_create.txt) of command `conda create --yes python=3.6 -n test_conda43_2 -vvv > ../env_create.txt 2>&1`.)

I would like to point out couple of things:
 - I have read access to the root environment (I am an owner, I just removed write privileges for debugging).
- I for sure have write privileges for the folder I create environment in.
- I have set in my condarc `allow_softlinks: False` and `always_copy: True`. If this is a problem with soft/hard links, this should happen harassing condarc.

But of course this may be completely unrelated issue :)

Just in case, my full [condarc](https://github.com/conda/conda/files/1068748/condarc.txt).

**Comment by slavoutich** [comment]
May be conda forgets to fix write permissions after copying from read-only location?

**Comment by mingwandroid** [comment]
Conda plays no part in setting permissions, nor should it IMHO. conda-build however could try to help out in an advisory role, but it would, I think, have to take the form of warnings (with a possibility for warnings as errors).

**Comment by slavoutich** [comment]
@mingwandroid I think you're right, in my case I just used wrong assumption, that in the case I remove writing permission from myself, it would be equivalent to root-owned environment.

**Comment by Wildcarde** [comment]
I can confirm that if I simply chmod -Rv +r the entire anaconda source tree it resolves this issue (we want it world readable in this case anyway).

**Comment by kalefranz** [comment]
I don't know of any mechanism where conda would have changed the read permissions bits on a path.  So is there a package that has wrong permissions set in it?

**Comment by hannes-brt** [comment]
+1
Workaround of setting read permissions to the dbus scripts worked for me.

**Comment by dmorel** [comment]
There seems to be a packaging problem, indeed.
```
[damorel@crb1-shell1 ~]$ find /home/common-prod/Anaconda3-4.4.0-Linux-x86_64/ ! -perm -o+r
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/info/recipe/build.sh
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/info/recipe/meta.yaml.template
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/info/recipe/post-link.sh.Darwin
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/info/recipe/post-link.sh.Linux
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/info/recipe/meta.yaml
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/bin/.dbus-post-link.sh
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/dbus-1.10.10-0/libexec/dbus-daemon-launch-helper
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/gst-plugins-base-1.8.0-0/info/recipe/build.sh
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/gst-plugins-base-1.8.0-0/info/recipe/meta.yaml
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/gstreamer-1.8.0-0/info/recipe/meta.yaml
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/pkgs/gstreamer-1.8.0-0/info/recipe/build.sh
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/envs/py35/bin/.dbus-post-link.sh
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/envs/py35/libexec/dbus-daemon-launch-helper
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/bin/.dbus-post-link.sh
/home/common-prod/Anaconda3-4.4.0-Linux-x86_64/libexec/dbus-daemon-launch-helper
```

**Comment by nehaljwani** [comment]
There is a new version of dbus `1.10.20` available in the defaults channel.

**Comment by kingaj12** [comment]
This should NOT be closed.  Anaconda files are owned by root.  This is unacceptable.

**Comment by mingwandroid** [comment]
@kingaj12 the bug here was that some files in one package were not readable by others. That is fixed, so this bug was closed.

If you are having some other problem please file a new bug report.

Files are not owned by root unless you install as root, which is entirely reasonable.

**Comment by ddofer** [comment]
I ran the chmod scripts for my anaconda directory, it didn't help. Still getting the same errors. (OSX).

`
sudo chmod -R a+rx ~/anaconda/
conda update --all
`
$ conda update --all
Solving environment: done

## Package Plan ##

  environment location: /Users/danofer/anaconda

The following packages will be UPDATED:

    anaconda-navigator: 1.6.12-py36_0                     --> 1.7.0-py36_0                     
    dbus:               1.12.2-haa0f8f7_0                 --> 1.12.2-h5243cc1_1                
    gensim:             3.1.0-py36h33de7db_0              --> 3.3.0-py36h917ab60_0             
    more-itertools:     3.2.0-py36_0                      --> 4.1.0-py36_0                     
    msgpack-python:     0.5.1-py36h04f5b5a_0              --> 0.5.5-py36h04f5b5a_0             
    olefile:            0.44-py36ha08bf50_0               --> 0.45.1-py36_0                    
    openjdk:            8.0.121-1                         --> 8.0.152-h393ad39_1               
    plotly:             2.2.2-py36h097dc49_0              --> 2.4.0-py36_0                     
    quandl:             3.2.0-py36h73fb0f8_0              --> 3.3.0-py36_0                     
    requests:           2.14.2-py36_intel_0  intel        [intel] --> 2.18.4-py36_intel_0  intel        [intel]

The following packages will be DOWNGRADED:

    conda:              4.4.11-py36_0        conda-canary --> 4.4.6-py36_0         conda-canary
    setuptools:         38.4.0-py36_0                     --> 27.2.0-py36_intel_0  intel        [intel]

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
**Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while uninstalling package 'defaults::dbus-1.12.2-haa0f8f7_0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Permission denied')**

> 



Conda info output:

>      active environment : None
       user config file : /Users/danofer/.condarc
 populated config files : /Users/danofer/.condarc
          conda version : 4.4.11
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /Users/danofer/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/intel/osx-64
                          https://conda.anaconda.org/intel/noarch
                          https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/danofer/anaconda/pkgs
                          /Users/danofer/.conda/pkgs
       envs directories : /Users/danofer/anaconda/envs
                          /Users/danofer/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.14.2 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by remusdmello18** [comment]
Did you get the solution?

**Comment by ShixiangWang** [comment]
if I have no root permission, how to fix this?

**Comment by gabefair** [comment]
Was anyone able to fix this?
