### ISSUE TITLE
conda can't install any package???

### ISSUE THREAD

**Issue by ilove1368** [conda/conda#5754]
i found i can't  install any package through this code `conda install  packagename`, does anyone know how to solve this problem? Here is an example ,thank you !

`[Anaconda2] C:\WINDOWS\system32>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-32
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False`

`[Anaconda2] C:\WINDOWS\system32>conda install pymongo
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 240, in install
    prefix=prefix)
  File "C:\Anaconda2\lib\site-packages\conda\cli\common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\api.py", line 43, in get_index
    unknown=unknown)
  File "C:\Anaconda2\lib\site-packages\conda\utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda2\lib\site-packages\concurrent\futures\_base.py", line 403, in result
    return self.__get_result()
  File "C:\Anaconda2\lib\site-packages\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda2\lib\site-packages\requests\adapters.py", line 376, in send
    timeout=timeout
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 554, in urlopen
    self._prepare_proxy(conn)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 750, in _prepare_proxy
    conn.connect()
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connection.py", line 217, in connect
    conn = self._new_conn()
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\util\connection.py", line 64, in create_connection
    if host.startswith('['):
AttributeError: 'NoneType' object has no attribute 'startswith'`

**Comment by nehaljwani** [comment]
Two things:

(i) You probably have something wrongly formatted in your `%HOME%\.condarc` file
(ii) You are using a very old version of conda

**Comment by ilove1368** [comment]
here is the `%HOME%\.condarc` file, is there anything  wrong with it?  and  the version of conda is 4.0.0

channels:
  - conda-canary
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
show_channel_urls: yes
ssl_verify: false

**Comment by nehaljwani** [comment]
Try removing the entry `https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/` and see if it works. I am not very sure, but this might have been resolved with more recent versions of conda. Please update to `v4.3.x`

**Comment by nehaljwani** [comment]
If remove that entry doesn't work, please share output for the command: `set` on the command prompt.

**Comment by ilove1368** [comment]
i have tried to remove that entry and update the version to `v4.4.0`, but the problem still exist, here is the output for the command: `set`

[Anaconda2] C:\WINDOWS\system32>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Danny\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-NK4GQSH
ComSpec=C:\WINDOWS\system32\cmd.exe
CONDA_DEFAULT_ENV=C:\Anaconda2
CONDA_PATH_BACKUP=C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\bin;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\Library\bin;C:\ProgramData\Anaconda2\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\R2014b\runtime\win64;C:\Program Files\MATLAB\R2014b\bin;C:\Program Files\MATLAB\R2014b\polyspace\bin;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\bin;C:\Wind\Wind.NET.Client\WindNET\bin\;C:\Users\Danny\AppData\Local\Microsoft\WindowsApps
ESET_OPTIONS=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
HOMEDRIVE=C:
HOMEPATH=\Users\Danny
LOCALAPPDATA=C:\Users\Danny\AppData\Local
LOGONSERVER=\\DESKTOP-NK4GQSH
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\Danny\OneDrive
OS=Windows_NT
Path=C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\bin;C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\bin;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\Library\bin;C:\ProgramData\Anaconda2\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\R2014b\runtime\win64;C:\Program Files\MATLAB\R2014b\bin;C:\Program Files\MATLAB\R2014b\polyspace\bin;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Wind\Wind.NET.Client\WindNET\bin\;C:\Users\Danny\AppData\Local\Microsoft\WindowsApps
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=[Anaconda2] $P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\PowerShell\Modules\
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\Danny\AppData\Local\Temp
TMP=C:\Users\Danny\AppData\Local\Temp
USERDOMAIN=DESKTOP-NK4GQSH
USERDOMAIN_ROAMINGPROFILE=DESKTOP-NK4GQSH
USERNAME=Danny
USERPROFILE=C:\Users\Danny
windir=C:\WINDOWS

**Comment by kalefranz** [comment]
Related to or duplicate of #3962.

**Comment by kalefranz** [comment]
Please move future discussion to #3962.
