### ISSUE TITLE
Installation with spaces// Anaconda prompt stop responding after updating conda.

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6704]
_From @Usama23 on January 10, 2018 12:29_

OS: Windows
Anaconda2/3- 5.0.1
Anaconda Navigator 1.6.12

**Steps to Reproduce:**

1: Download and install anaconda with single space (single User/ All User).
2: From anaconda prompt update conda to latest version (4.4.7) .
3: Open another anaconda prompt.

**Actual Result:**

A weird statement appear on the start of prompt and then nothing works on that newly open prompt.

``` 
> was unexpected at this time.
C:\Users\tester>@IF NOT ""=="" @chcp  > NUL
```
![screenshot_767](https://user-images.githubusercontent.com/21064099/34772662-9d459fd2-f62a-11e7-96a2-a3369c741ba9.png)
![screenshot_768](https://user-images.githubusercontent.com/21064099/34772663-9d7f0d58-f62a-11e7-982c-8bc7e7a0820c.png)
![screenshot_769](https://user-images.githubusercontent.com/21064099/34772664-9db54026-f62a-11e7-9860-96d60f1a8a4a.png)

_Copied from original issue: ContinuumIO/anaconda#1175_

**Comment by kalefranz** [comment]
_From @mingwandroid on January 10, 2018 12:44_

Please copy and paste the text instead of screenshots.

@kalefranz this looks like one for you?

**Comment by mbargull** [comment]
Ah, looking at the second screenshot more closely, that one says
```
activate does not accept more than one argument:
('C:\\ProgramData\\Anaconda', '3')
```
. So from that I assume Anaconda was installed to `C:\ProgramData\Anaconda 3` (note the space).
In `conda.bat` we call `... activate %*` (at https://github.com/conda/conda/blob/4.4.7/conda/shell/Library/bin/conda.bat#L30) and it could be that `anaconda-navigator` and the `Anaconda Prompt`-shortcut run the `activate` command with the full prefix, i.e., include the space-containing path but don't properly quote it?
I wasn't sure whether `CMD` will reinterpret the contents of `%*` prior to passing it on to Python, so it tried
```bat
REM a.bat
@FOR /F "delims=" %%i IN ('@CALL C:\home\maba\conda\miniconda-win64\python.exe -c "import sys; print(sys.argv)" %*') DO @SET "o=%%i"
echo(%o%
```
but it seems to work as intended:
```cmd
C:\>a "C:\ProgramData\Anaconda 3"
['-c', 'C:\\ProgramData\\Anaconda 3']
```
, hence I'm leaning towards an issue with `anaconda-navigator`/`console_shortcut`.

**Comment by mbargull** [comment]
I messed with this in a VM and can confirm, this is not a `conda` issue but one of the launchers.

----

The `Anaconda Prompt` shortcut uses
```cmd
%windir%\System32\cmd.exe "/K" "C:\ProgramData\Anaconda 3\Scripts\activate.bat" "C:\ProgramData\Anaconda 3"
```
for which the last parameter is passed on to `activate.bat` as `"C:\ProgramData\Anaconda 3` (note the missing end quote).
If I change the target to
```cmd
%windir%\System32\cmd.exe /K ""C:\ProgramData\Anaconda 3\Scripts\activate.bat" "C:\ProgramData\Anaconda 3""
```
, everything works fine and `activate.bat`/`conda.bat` get `"C:\ProgramData\Anaconda 3"`.
Conclusion: For the `Anaconda Prompt` this is a `menuinst` (+`console_shortcut`) issue [quoting in `menuinst` is broken](https://github.com/ContinuumIO/menuinst/commit/fcf395dbc7ccfd5130b2c38a243056820034081f)...

----

What we'd actually need, is that in `console_shortcut`
```json
"scriptarguments": ["/K", "${ROOT_PREFIX}\\Scripts\\activate.bat", "${PREFIX}"],
```
should be changed to
```json
"scriptarguments": ["/K", "\"${ROOT_PREFIX}\\Scripts\\activate.bat\" \"${PREFIX}\""],
```
and in `menuinst.win32` *not* add quotes around `/K` via `menuinst.win32.quoted` in https://github.com/ContinuumIO/menuinst/blob/1.4.10/menuinst/win32.py#L292 and *not* let `menuinst.win32.quoted` unconditionally remove quotes at the beginning and end of the arguments in https://github.com/ContinuumIO/menuinst/blob/1.4.10/menuinst/win32.py#L292-L293, cc @mingwandroid. As previously discussed, it would be wise to add a bunch of test cases to `menuinst` to get all those subtleties right; breaking changes might likely have to be postponed for a `menuinst 2.x`, I think.

----

@goanpeca: You are concerned with `anaconda-navigator`'s development, right? In the user's screenshot does the second window show an interactive Python session launched via Navigator? If so, how does Navigator launch the environment activation exactly? This will likely be need to fixed, too. (`anaconda-navigator` is still closed-source, so nothing I can directly help with, right?)

**Comment by mbewley** [comment]
Confirming that I have this same issue too (installing under Windows 10 with a user with a space in the username). Manually running the command with quotations on the failed anaconda prompt fixes it and activates the environment.

**Comment by kalefranz** [comment]
We should probably create an issue in the appropriate repo now.  Or move this one.

**Comment by mbewley** [comment]
Please! It's a fairly major issue - making the anaconda prompt effectively unusable for any windows user with a space in their username. Sounds like the fix would be pretty straightforward though?

**Comment by kalefranz** [comment]
So we need changes to https://github.com/AnacondaRecipes/aggregate/tree/master/console_shortcut-feedstock/recipe and  https://github.com/ContinuumIO/menuinst as proposed in https://github.com/conda/conda/issues/6704#issuecomment-357327468

**Comment by kalefranz** [comment]
I've created issues in appropriate repos.  As this is not a conda issue, going to close this issue now.

**Comment by mbewley** [comment]
can you add a link to the issues here?

**Comment by kalefranz** [comment]
The issue that's public is https://github.com/ContinuumIO/menuinst/issues/58

**Comment by mbewley** [comment]
Thanks!

**Comment by mbargull** [comment]
I had a quick peek at its code and can say Navigator needs fixes, too. To whomever is responsible for Navigator, feel free to contact me if you need any directions on that.

**Comment by kalefranz** [comment]
^^ @goanpeca

**Comment by goanpeca** [comment]
@mbargull could you ping me on where I need to issue a fix?

**Comment by mbargull** [comment]
I think the following could work for `anaconda-navigator 1.6.12`:
```diff
--- anaconda_navigator/utils/launch.py
+++ anaconda_navigator/utils/launch.py
@@ -351 +351 @@
-            cmd = 'start cmd.exe /k activate ' + activate
+            cmd = 'start cmd.exe /k "activate "{}""'.format(activate)
@@ -439 +439 @@
-            cmd = '"activate {} & {}"'.format(activate, cmd)
+            cmd = '"activate "{}" & {}"'.format(activate, cmd)
```
, but I didn't test this and don't really know that code otherwise (only `grep`ed for "activate").

**Comment by mingwandroid** [comment]
@kalefranz, you said we need changes to https://github.com/AnacondaRecipes/aggregate/tree/master/console_shortcut-feedstock/recipe

.. are you sure? I think it should work OK with just the new menuinst?

**Comment by mbargull** [comment]
@mingwandroid, that'd might've come from me babbling in https://github.com/conda/conda/issues/6704#issuecomment-357327468. With the new changes in `menuinst` I would assume no changes to `console_shortcut` are needed -- haven't tested that, though.

**Comment by kalefranz** [comment]
@mingwandroid `console_shortcut` shouldn't need changes with the new menuinst.  If I said that, I was mistaken.

**Comment by msarahan** [comment]
I believe this is fixed with conda 4.4.9 and menuinst 1.4.11.  I have tested this against new Anaconda preview installers, and everything appears to be working.  No rebuild necessary for console_shortcut.

**Comment by JawadAr** [comment]
![image](https://user-images.githubusercontent.com/40181115/57826935-d30f5600-77be-11e9-9202-f856b9e85299.png)

The issue is still persistent in the latest release.

**Comment by dantravers** [comment]
I'm finding this issue still present in conda version 4.7.12.
I did an un-install and fresh install of anaconda.  Tried to create a new environment running in anaconda prompt (as Administrator): 

>conda create --name dan3.7min python=3.7 pandas numpy SciPy scikit-learn matplotlib seaborn xarray

Receive error message, containing issue with installation, but assuming this in linked to the activate issue at the end (Travers is my last name and I have a space before it in windows):

ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\ProgramData\Anaconda3\envs\dan37min\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:
stderr: The system cannot find the path specified.
activate does not accept more than one argument:
['C:\\ProgramData\\Anaconda3\\envs\\dan37min', 'Travers\\AppData\\Local\\Temp\\conda-15131-29410.tmp']

**Comment by dantravers** [comment]
Same problem evidenced here: 
>conda install anaconda-clean

Downloading and Extracting Packages
anaconda-clean-1.1.0 | 23 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
The system cannot find the path specified.
reactivate does not accept arguments
remainder_args: ['Travers\\AppData\\Local\\Temp\\conda-14456-906.tmp']

**Comment by KeystoneScience** [comment]
> Confirming that I have this same issue too (installing under Windows 10 with a user with a space in the username). Manually running the command with quotations on the failed anaconda prompt fixes it and activates the environment.

sorry, I am new to this stuff, but just need to get a library installed for use with spyder,
what command did you type into the failed anaconda prompt that allowed it to work?
