### ISSUE TITLE
conda permission errors 

### ISSUE THREAD

**Issue by jsignell** [conda/conda#8155]
Originally posted as https://github.com/appveyor/ci/issues/2822

## Current Behavior

In Appveyor, using conda 4.6.1 to install any libraries which attempt to write an entrypoint script into the miniconda env directory raises Permission Denied errors and causes the build to fail. An example is [this build](https://ci.appveyor.com/project/pyviz/hvplot/builds/21921315/job/yr6fahphkmxw1cim) on the public hvPlot repo:

```traceback
ERROR conda.core.link:_execute(543): An error occurred while installing package 'conda-forge::ipykernel-5.1.0-py36h39e3cac_1001'.
PermissionError(13, 'Permission denied')
Attempting to roll back.
Rolling back transaction: ...working... done
[Errno 13] Permission denied: 'C:\\Miniconda36-x64\\envs\\earthml\\Scripts\\jupyter-kernel.exe'
```

### Steps to Reproduce

```
conda install jupyter
```

## Expected Behavior

On conda 4.5.4 the install works as expected

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.6.1
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : C:\Miniconda36-x64  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\.conda\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\.conda\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.1 requests/2.18.4 CPython/3.6.5 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by msarahan** [comment]
Of course, I can't reproduce this locally.  I think it might come down to an "all-users" vs "just-me" install.  As a hack you could try adding an empty ``.nonadmin`` file to the ``C:\Miniconda36-x64`` folder.

Sorry, but it might be a while before we can get around to debugging this.  If you're stuck, I recommend just pinning to the older conda version for now.

**Comment by philippjfr** [comment]
As far as I can tell this is affecting all appveyor miniconda builds which install packages with entrypoint scripts, and presumably also a sizable portion of regular Windows users. Would be great to get a fix for this soon so we can start enjoying the speed improvements in latest conda :smile:

I'll try reproducing it locally on my windows machine and dig a bit.

**Comment by kalefranz** [comment]
There's something that doesn't quite line up here.  How is it that the package is `conda-forge::ipykernel-5.1.0-py36h39e3cac_1001`, but there's no mention of the `conda-forge` channel anywhere else in the report?

**Comment by kalefranz** [comment]
I see.  That actual command according to https://ci.appveyor.com/project/pyviz/hvplot/builds/21921315/job/yr6fahphkmxw1cim#L720 was

    conda install -y  -c pyviz/label/dev -c conda-forge "bokeh >=1.0.0" "holoviews >=1.11.0" "pandas<0.24.0" "coveralls" "nose" "flake8" "parameterized" "pytest" "nbsmoke >=0.2.0"

**Comment by jsignell** [comment]
Ah right - forgot to mention the channel info - like I said this was on appveyor so hard to debug.

**Comment by kalefranz** [comment]
My guess is the environment creation command was

    conda create -n test -c pyviz/label/dev -c conda-forge "param>=1.7.0" "pyct>=0.4.4" "setuptools>=30.3.0"

So the two-step recreation process would be

    conda create -n test -c pyviz/label/dev -c conda-forge "param>=1.7.0" "pyct>=0.4.4" "setuptools>=30.3.0"
    conda install -y  -c pyviz/label/dev -c conda-forge "bokeh >=1.0.0" "holoviews >=1.11.0" "pandas<0.24.0" "coveralls" "nose" "flake8" "parameterized" "pytest" "nbsmoke >=0.2.0"

but it would be helpful to have that confirmed.

**Comment by msarahan** [comment]
There is a really neat trick to debug things on appveyor: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by kalefranz** [comment]
Using `-vv` should show you the full stack trace and you’ll probably see right where the problem is.

**Comment by soapy1** [comment]
Looks like this is fixed on master, it should be resolved in the next release of conda

**Comment by ocefpaf** [comment]
I just tested `conda 4.6.2` from the canary channel and it seems that the problem persists:

https://ci.appveyor.com/project/ocefpaf/notebooks-demos/builds/21998415

It may be specific to my config there. I'll try to isolate the problem and create some steps to reproduce it.

**Comment by dhirschfeld** [comment]
ping @SylvainCorlay - this might be of interest.

**Comment by SylvainCorlay** [comment]
Thanks @dhirschfeld. This appears to be it!
