### ISSUE TITLE
BUG: conda lib paths for NumPy, vtk, possibly others on Windows with environment.yml that has pip installs

### ISSUE THREAD

**Issue by larsoner** [conda/conda#8187]
## Current Behavior

As of about 10 days ago, I started hitting a DLL not found error on Windows 10 on AppVeyor (not OSX or Linux on Travis) when using an `environment.yml` file to install NumPy using conda and another package using `pip`, using the [widely used ci-helpers repo](https://github.com/astropy/ci-helpers). This code had been working reliably for a year or two before this. I am mystified because I cannot find changes to `conda`, the packages, or AppVeyor images that could have caused this.

### Steps to Reproduce

I've tried to boil this down to a MWE locally in a Windows 10 VM. In a Windows Git bash terminal (because I don't know how to use `cmd`/`PowerShell` properly):
```Console
$ curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
$ ./Miniconda3-latest-Windows-x86_64.exe  # just accept all defaults
$ export PATH=/c/Users/tester/Miniconda3/:/c/Users/tester/Miniconda3/Scripts/:$PATH
$ conda env create -n test -f environment.yml
```
<details>
  <summary>Output</summary>

    $ conda env create -n test -f environment.yml
    Solving environment: done
    
    
    ==> WARNING: A newer version of conda exists. <==
      current version: 4.5.12
      latest version: 4.6.1
    
    Please update conda by running
    
        $ conda update -n base -c defaults conda
    
    
    
    Downloading and Extracting Packages
    numpy-1.15.4         | 47 KB     | ############################################################################ | 100%
    mkl_fft-1.0.10       | 135 KB    | ############################################################################ | 100%
    python-3.7.2         | 17.7 MB   | ############################################################################ | 100%
    blas-1.0             | 6 KB      | ############################################################################ | 100%
    numpy-base-1.15.4    | 3.9 MB    | ############################################################################ | 100%
    ca-certificates-2018 | 153 KB    | ############################################################################ | 100%
    mkl_random-1.0.2     | 328 KB    | ############################################################################ | 100%
    icc_rt-2019.0.0      | 9.4 MB    | ############################################################################ | 100%
    mkl-2019.1           | 158.3 MB  | ############################################################################ | 100%
    intel-openmp-2019.1  | 1.7 MB    | ############################################################################ | 100%
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done
    Collecting python-picard (from -r C:\Users\tester\condaenv.7pskmwiu.requirements.txt (line 1))
      Using cached https://files.pythonhosted.org/packages/2e/08/2c22d1702a3aa4f84ec8f816c006b4c8dd16fdb04c06c4ffd56c1f97c8d5/python-picard-0.3.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "C:\Users\tester\Miniconda3\envs\test\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
            from . import multiarray
        ImportError: DLL load failed: The specified module could not be found.
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "C:\Users\tester\AppData\Local\Temp\pip-install-bam0ywrr\python-picard\setup.py", line 5, in <module>
            from numpy.distutils.core import setup
          File "C:\Users\tester\Miniconda3\envs\test\lib\site-packages\numpy\__init__.py", line 142, in <module>
            from . import add_newdocs
          File "C:\Users\tester\Miniconda3\envs\test\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
            from numpy.lib import add_newdoc
          File "C:\Users\tester\Miniconda3\envs\test\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
            from .type_check import *
          File "C:\Users\tester\Miniconda3\envs\test\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
            import numpy.core.numeric as _nx
          File "C:\Users\tester\Miniconda3\envs\test\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
            raise ImportError(msg)
        ImportError:
        Importing the multiarray numpy extension module failed.  Most
        likely you are trying to import a failed build of numpy.
        If you're working with a numpy git repo, try `git clean -xdf` (removes all
        files not under version control).  Otherwise reinstall numpy.
    
        Original error was: DLL load failed: The specified module could not be found.
    
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\tester\AppData\Local\Temp\pip-install-bam0ywrr\python-picard\
    
    CondaValueError: pip returned an error

</details>

Contents of `environment.yml` (using `python-picard` because it does `from numpy.distutils import setup` at the top of its `setup.py`):
```
dependencies:
- numpy
- pip:
  - python-picard
```
This issue was actually seen in the wild with a [DLL load error for `vtk`](https://ci.appveyor.com/project/mne-tools/mne-python/builds/21756378#L146) when it was in the `dependencies` list for `conda`, and a `pip` package was being built that required the conda-packaged `vtk` (specifically `mayavi`). So it seems to have problems with not just NumPy, but possibly any package that `pip` installing will require. So I think there is some `lib` path setting bug here.

Notably, if you the `pip` install bits are removed from `environment.yml` and are done separately with `pip install ...` after `source activate test`'ing, things work fine. For example, after the failure above, this works fine:
```Console
$ source activate test
$ pip install python-picard
```
<details>
  <summary>Output</summary>

    Collecting python-picard
      Using cached https://files.pythonhosted.org/packages/2e/08/2c22d1702a3aa4f84ec8f816c006b4c8dd16fdb04c06c4ffd56c1f97c8d5/python-picard-0.3.tar.gz
    Building wheels for collected packages: python-picard
      Running setup.py bdist_wheel for python-picard ... done
      Stored in directory: C:\Users\tester\AppData\Local\pip\Cache\wheels\33\41\c0\1dc5d7b51edeae9eddf7aa867c0d63fc35eeb84c8e9e3b20b1
    Successfully built python-picard
    Installing collected packages: python-picard
    Successfully installed python-picard-0.3

</details>

This happens on 4.5.12 (default miniconda) and 4.6.1 (installed using `conda update -n base conda`).

## Expected Behavior

Packages should install without issue.

## Environment Information

The following is after doing `source activate test`:

<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : test
    active env location : C:\Users\tester\Miniconda3\envs\test
            shell level : 1
       user config file : C:\Users\tester\.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Users\tester\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\tester\Miniconda3\pkgs
                          C:\Users\tester\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tester\Miniconda3\envs
                          C:\Users\tester\AppData\Local\conda\conda\envs
                          C:\Users\tester\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
<blank>
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at C:\Users\tester\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2018.12.5                     0    defaults
certifi                   2018.11.29               py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
intel-openmp              2019.1                      144    defaults
mkl                       2019.1                      144    defaults
mkl_fft                   1.0.10           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
numpy                     1.15.4           py37h19fb1c0_0    defaults
numpy-base                1.15.4           py37hc3f5095_0    defaults
openssl                   1.1.1a               he774522_0    defaults
pip                       18.1                     py37_0    defaults
python                    3.7.2                h8c8aaf0_0    defaults
python-picard             0.3                       <pip>
setuptools                40.6.3                   py37_0    defaults
sqlite                    3.26.0               he774522_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py37_0    defaults
wincertstore              0.2                      py37_0    defaults
```
</p></details>

**Comment by mingwandroid** [comment]
Please try:

`conda install -c rdonnelly python`

**Comment by larsoner** [comment]
On 4.6.1, after `conda env remove -n test` to remove the broken env, I did:
```Console
$ conda install -c rdonnely python
```
It changed to 3.7.2 and "downgraded" a bunch of stuff to match. Then:
```
$ conda create -n test -f environment.yml
```
Gave the same output as before: `DLL load failed`.

**Comment by msarahan** [comment]
I think this might be related to https://github.com/conda/conda/issues/8145

**Comment by larsoner** [comment]
That would make sense.

FWIW in case it helps to track down the offending change, I can replicate the problem even after doing:
```
conda install conda=4.3.27
```
but it goes away if I go one (available) version back:
```
conda install conda=4.3.25
```

**Comment by msarahan** [comment]
A bit more information:

* activation for post-link scripts has never really been a thing.
* pip installing something where compilation is required especially will require activation to ensure that the correct python in an env is used (such that the correct fallback to system compilers is present)
* for the reasons above, the env created by conda-env should be activated prior to running pip here, but is not (and has never been).
* we believe it may be advisable to have conda-env never allow pip to install dependencies, such that any implicit dependency must be met by conda somehow.  This will limit the amount of potential "accidental" compilation that pip attempts.

This brokenness was likely exacerbated by some recent change; however we believe the correct fix is to ensure activation of environments in more situations.  We're working towards that fix for the next conda release.

**Comment by larsoner** [comment]
> pip installing something where compilation is required 

FWIW the failures here (and in my MWE) do not require compilation, just importing the modules that were installed in the conda step.

(Incidentally, elsewhere compilation has been used just fine previously, but it's not such a limiting factor, at least in my use cases nowadays.)

> the env created by conda-env should be activated prior to running pip here, but is not (and has never been).

Any idea how installing vtk (or numpy) in the conda part, and mayavi (or python-picard) worked before? It sounds like you are saying that it should not have (?), but it has for months (probably over a year, maybe two?).

> we believe it may be advisable to have conda-env never allow pip to install dependencies, such that any implicit dependency must be met by conda somehow

Does this mean that the `pip` indented entries in environment.yml would be effectively disallowed?

**Comment by msarahan** [comment]
> Any idea how installing vtk (or numpy) in the conda part, and mayavi (or python-picard) worked before? It sounds like you are saying that it should not have (?), but it has for months (probably over a year, maybe two?).

We suspect the removal of Library/bin from PATH, see this patch on our 3.6, which has been removed with 3.7: https://github.com/AnacondaRecipes/python-feedstock/blob/master-3.6/recipe/meta.yaml#L16-L17

Does your code work if you force python 3.6, which should maintain the library/bin folder on PATH?

> Does this mean that the pip indented entries in environment.yml would be effectively disallowed?

No, that would be a major change in behavior.  What would be disallowed would be pip bringing in any *extra* dependencies beyond the ones you list explicitly.  This would be similar to conda-build's behavior, where any attempt by setuptools or pip to fetch indirect dependencies results in an error.

**Comment by larsoner** [comment]
> Does your code work if you force python 3.6, which should maintain the library/bin folder on PATH?

I can confirm that adding `- python<3.7` to the `environment.yml` is a suitable workaround for the problem! Thanks for your help and responsiveness.

> What would be disallowed would be pip bringing in any extra dependencies beyond the ones you list explicitly.

My quick reaction is that I would expect this to create additional maintenance work for updating the list any time a `pip`-listed thing adds a new dependency. In addition to backward compat break, it's also a bit unexpected since things in the `conda` list automatically pull in their dependencies, whereas the `pip` ones will no longer do so. But I understand the resulting improvements could be worth it.

FWIW, I'm not sure this change in behavior would fix the problem here -- `pip: python-picard` does not try to install anything other than itself, it just needs to make use of the `- numpy` installed from the `conda` list. But perhaps you have changes in mind that would fix this problem, and as a side effect, have repercussions on how `pip` listings are handled.

**Comment by flutefreak7** [comment]
I've been having issues yesterday and today trying to setup a common dev environment across coworker's machines using an environment.yml file with conda and pip and I wonder if my issues are related. If I conda activate the  environment and then pip install it works, but using the environment file want working for the pup stuff.

I can try and get details together tomorrow to see if I'm seeing the same broken behavior mentioned here or something else.

**Comment by larsoner** [comment]
@flutefreak7 if you are installing 3.7, yes it could be related. Can you try adding `- python<3.7` to your `environment.yml` to see if it fixes things? That's the workaround I am currently using successfully.

**Comment by flutefreak7** [comment]
Will do! I patched things up to get into 3.7 this week (mostly renaming `async` variables...) but no dataclasses yet, so no reason I can't step back.

**Comment by larsoner** [comment]
Slightly off-topic (but related to testing the fix):

- I was notified by Github that 4.6.4 was released 2 days ago, and saw it had the fix as part of it.
- I tried to use it and failed, but realized that it probably needed to show up in the [Anaconda packages page](https://anaconda.org/anaconda/conda). I saw that it landed today. 
- I tried to use it and [failed](https://ci.appveyor.com/project/mne-tools/mne-python/builds/22408044), because it hasn't landed in the [main repo](https://repo.anaconda.com/pkgs/main/win-64/) yet.

Are the relationships between these things documented somewhere? In the meantime, I'll keep occasionally hitting F5 whenever I notice the main-repo Chrome tab open in order to know when to ping my repo's CIs to test that everything works on 3.7 again.

**Comment by msarahan** [comment]
When conda is tagged, it then goes to the conda-canary channel for a little while (generally 1-2 days) before it goes to defaults.  We intended to release it to defaults yesterday, but something appears to have gone wrong.  It should be available shortly.

**Comment by larsoner** [comment]
Sounds good, no real rush from my end -- more just a point of curiosity. But it looks like it has now landed, and [things are failing differently on Windows](https://ci.appveyor.com/project/mne-tools/mne-python/builds/22408603) when it goes to upgrade to `conda=4.6.4`:
```
Solving environment: ...working... failed
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\conda\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\conda\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\conda\lib\site-packages\conda\cli\main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "C:\conda\lib\site-packages\conda\cli\install.py", line 235, in install
        force_reinstall=context.force,
      File "C:\conda\lib\site-packages\conda\core\solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\conda\lib\site-packages\conda\core\solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "C:\conda\lib\site-packages\conda\core\solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "C:\conda\lib\site-packages\conda\core\solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "C:\conda\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "C:\conda\lib\site-packages\conda\core\index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\conda\lib\site-packages\conda\core\subdir_data.py", line 95, in query
        self.load()
      File "C:\conda\lib\site-packages\conda\core\subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "C:\conda\lib\site-packages\conda\core\subdir_data.py", line 246, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "C:\conda\lib\site-packages\conda\core\subdir_data.py", line 374, in _process_raw_repodata_str
        package_record = PackageRecord(**info)
      File "C:\conda\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\conda\lib\site-packages\conda\_vendor\auxlib\entity.py", line 736, in __init__
        setattr(self, key, kwargs[key])
      File "C:\conda\lib\site-packages\conda\_vendor\auxlib\entity.py", line 427, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
      File "C:\conda\lib\site-packages\conda\models\records.py", line 102, in box
        val = tuple(f for f in (ff.strip() for ff in val) if f)
    TypeError: 'NoneType' object is not iterable
`$ C:\conda\Scripts\conda install -q conda=4.6.4`
```
I can see if I can reproduce locally with my minimal script if this is not enough to see the problem.

**Comment by msarahan** [comment]
That looks like you got some corrupt index somehow.

conda clean -iy

will clean your index cache.  If it stays a problem, it's a very big deal, so please let us know one way or another.

**Comment by msarahan** [comment]
I also see this.  We're looking into it.

**Comment by msarahan** [comment]
This is due to null values present in the "free" channel repodata.  We'll remove them quickly and debug their presence.

**Comment by msarahan** [comment]
Repodata issues were not related, but should be resolved.

**Comment by larsoner** [comment]
Repodata problem fixed! Unfortunately I still get the same DLL loading error as before [on AppVeyor](https://ci.appveyor.com/project/mne-tools/mne-python/builds/22410917), so 4.6.4 does not seem to fix the problem (all `python-picard` does with numpy is try to import from it at the top of its `setup.py`):
```
Collecting python-picard (from -r C:\projects\mne-python\condaenv.g3fci9wb.requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/2e/08/2c22d1702a3aa4f84ec8f816c006b4c8dd16fdb04c06c4ffd56c1f97c8d5/python-picard-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\conda\envs\test\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
        from . import multiarray
    ImportError: DLL load failed: The specified module could not be found.
```
I have not tried to replicate with my MWE but it should fail the same way.

**Comment by mingwandroid** [comment]
I know what this is and am working on a fix. It's getting rather late though so it won't be ready today.
