### ISSUE TITLE
conda env create Not Working With environment.yml File

### ISSUE THREAD

**Issue by cSchubes** [conda/conda#8346]
## Current Behavior
I am trying to create a conda environment using an environment.yml file on Windows 10 inside the Anaconda Prompt. When I do so, none of the packages listed in the environnment.yml actually get installed, only the defaults. You can see the command executing below with verbosity set to 2:
```
(base) C:\Users\Me\Documents\Stuff\raven>conda env create --file=./environment_windows.yml -v -v
DEBUG conda.gateways.logging:set_verbosity(150): verbosity set to 2
DEBUG conda.core.solve:solve_final_state(212): solving prefix C:\Users\Carson\Anaconda3\envs\raven
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("certifi=2018.11.29"), MatchSpec("sqlite=3.26.0"), MatchSpec("zlib=1.2.11"), MatchSpec("setuptools=40.8.0"), MatchSpec("python=3.6.8"), MatchSpec("wheel=0.32.3"), MatchSpec("xz=5.2.4"), MatchSpec("ca-certificates=2019.1.23"), MatchSpec("tk=8.6.8"), MatchSpec("pip=19.0.1"), MatchSpec("openssl=1.1.1a")})
  prune: False
Collecting package metadata: ...working... DEBUG conda.core.package_cache_data:_check_writable(252): package cache directory 'C:\Users\Carson\Anaconda3\pkgs' writable: True
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/r/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\4ea078d6.json
DEBUG urllib3.util.retry:from_int(210): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG urllib3.connectionpool:_new_conn(813): Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/r/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> If-Modified-Since: Mon, 25 Feb 2019 22:47:04 GMT
> If-None-Match: "85ac6edeadea1c5ba6488550362bd4ee"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af90bb589b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "85ac6edeadea1c5ba6488550362bd4ee"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Mon, 25 Feb 2019 22:47:04 GMT
< Server: cloudflare
< Set-Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954; expires=Wed, 26-Feb-20 19:05:54 GMT; path=/; domain=.anaconda.com; HttpOnly; Secure
< Vary: Accept-Encoding
< x-amz-id-2: GRd9ClLhD+G6zg0cyUgA09Z4gL+osxnLBuZ7sPpx9Y5+XJK8JvhFuRcO8GXKx5RFgQAd0OoCaS8=
< x-amz-request-id: B1734BC7D898B252
< x-amz-version-id: x2bq2WWe0_iAo2bpBsBBwXbwi2Vy9mjU
< Connection: keep-alive
< Elapsed: 00:00.160034


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/r/noarch'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\4ea078d6.q
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/msys2/win-64 at C:\Users\Carson\Anaconda3\pkgs\cache\5ca77eed.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/msys2/win-64/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Mon, 25 Feb 2019 22:46:44 GMT
> If-None-Match: "1d3c1efb0690c44dc06531ee0856273a"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af90fb959b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "1d3c1efb0690c44dc06531ee0856273a"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Mon, 25 Feb 2019 22:46:44 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: ctsWdkPk1+g5UH/9bnBoqUfHxxyUPvfHHDp1twR6Dl6T6jqNJl10e3rFXr175DjSpf0y1zvQgBc=
< x-amz-request-id: 5BB8403B79CA45B2
< x-amz-version-id: DD2z27h6UedCs6dO084FvdalcFwW9Qn0
< Connection: keep-alive
< Elapsed: 00:00.024495


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/msys2/win-64'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\5ca77eed.q
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/free/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\d77296e0.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/free/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Fri, 15 Feb 2019 20:57:51 GMT
> If-None-Match: "b23fbf0113c7195c9a87e96d1a6431f7"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af912bde9b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "b23fbf0113c7195c9a87e96d1a6431f7"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Fri, 15 Feb 2019 20:57:51 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: 8e9BsFGjkoovQroI/hoMArnUENjKpaSHny5HMqLX4HEioRgI+Xqxm2bbSQV6BpJ5cXLWGwq4GGY=
< x-amz-request-id: 7331E63B3D426E6B
< x-amz-version-id: EuBGIf6WRNSwjnaCD5OSKC_9l3KtarP2
< Connection: keep-alive
< Elapsed: 00:00.016776


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/free/noarch'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\d77296e0.q
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/main/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\3e39a7aa.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/main/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Mon, 25 Feb 2019 22:45:49 GMT
> If-None-Match: "90bd5a411a2082ee55feccccf68bfaaa"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af915c249b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "90bd5a411a2082ee55feccccf68bfaaa"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Mon, 25 Feb 2019 22:45:49 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: aKZPkfRYm+x9x/P1qTFTdcU1MCWaGBc3zIT3dBmNRuQXxX6j/rhI0J5l4wouFt9WT44bFwX8Ho0=
< x-amz-request-id: E34CAB0BE7436DCE
< x-amz-version-id: 0Inocr2MWPwi4U9iRltSNbWGmVNSI2Nz
< Connection: keep-alive
< Elapsed: 00:00.019093


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/main/noarch'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\3e39a7aa.q
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/msys2/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\c4a505b4.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/msys2/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Tue, 11 Sep 2018 18:44:08 GMT
> If-None-Match: "2bbdefb2e89410857cff09a1953f7349"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af918c689b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "2bbdefb2e89410857cff09a1953f7349"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Tue, 11 Sep 2018 18:44:08 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: CdfqgxJ1SRGS1PdcoOXMcl8ZlIkpTeyywS16VoIwr79rDO2cdNUxl2hruPSBD7B7S0DqEhTqB3g=
< x-amz-request-id: CE7B9172FCAA3B58
< x-amz-version-id: tNKjNSyxp584ZPAcoBNHGOVUzPoQgZUC
< Connection: keep-alive
< Elapsed: 00:00.022677


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/msys2/noarch'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\c4a505b4.q
DEBUG conda.core.subdir_data:_read_pickled(302): Pickle load validation failed for https://repo.anaconda.com/pkgs/msys2/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\c4a505b4.json.
DEBUG conda.core.subdir_data:_read_local_repdata(257): Loading raw json for https://repo.anaconda.com/pkgs/msys2/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\c4a505b4.json
DEBUG conda.core.subdir_data:_pickle_me(244): Saving pickled state for https://repo.anaconda.com/pkgs/msys2/noarch at C:\Users\Carson\Anaconda3\pkgs\cache\c4a505b4.json
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/r/win-64 at C:\Users\Carson\Anaconda3\pkgs\cache\920c960f.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/r/win-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/r/win-64/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Mon, 25 Feb 2019 22:47:18 GMT
> If-None-Match: "8edeac5b42c456a9038e611b74d8e96a"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af91bccf9b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "8edeac5b42c456a9038e611b74d8e96a"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Mon, 25 Feb 2019 22:47:18 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: OYh9v9mgbB9OR0K0Y9j5WRV6vDqycF5e20tJxrLyleTDmBnLSh/N7YHJgCeLVDrvVpUMetCHeLc=
< x-amz-request-id: 025B4B1CAC7539C8
< x-amz-version-id: 8x5utKRxX9V4kxUzrRWpBIi1AtC5Gi8f
< Connection: keep-alive
< Elapsed: 00:00.029586


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/r/win-64'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\920c960f.q
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/free/win-64 at C:\Users\Carson\Anaconda3\pkgs\cache\d6a04735.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/free/win-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/free/win-64/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Fri, 15 Feb 2019 20:58:41 GMT
> If-None-Match: "24464626d891021dbde19d7339b77fc4"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af922d769b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "24464626d891021dbde19d7339b77fc4"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Fri, 15 Feb 2019 20:58:41 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: hrYuoRDeaQgauwulET4izhGi6SwcAVAEfvN1EJlACOrlY2PKU+i4KGyXF9dbF6QvqGoVpq9TjTc=
< x-amz-request-id: 76390E37B08F1DE2
< x-amz-version-id: i2IFtQx1N7yMCAk0LJDGr7aJBcgRhprq
< Connection: keep-alive
< Elapsed: 00:00.017942


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/free/win-64'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\d6a04735.q
DEBUG conda.core.subdir_data:_load(213): Local cache timed out for https://repo.anaconda.com/pkgs/main/win-64 at C:\Users\Carson\Anaconda3\pkgs\cache\59ba4880.json
DEBUG urllib3.connectionpool:_make_request(393): https://repo.anaconda.com:443 "GET /pkgs/main/win-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(431):
>>GET /pkgs/main/win-64/repodata.json.bz2 HTTPS
> User-Agent: conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> Cookie: __cfduid=dc2542dcc87a9fe6d332441f45b81c7721551207954
> If-Modified-Since: Tue, 26 Feb 2019 17:14:07 GMT
> If-None-Match: "ddc049e989a06df96a80c493c135c52b"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 4af4af92eedc9b38-DFW
< Date: Tue, 26 Feb 2019 19:05:54 GMT
< ETag: "ddc049e989a06df96a80c493c135c52b"
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Tue, 26 Feb 2019 19:06:24 GMT
< Last-Modified: Tue, 26 Feb 2019 17:14:07 GMT
< Server: cloudflare
< Vary: Accept-Encoding
< x-amz-id-2: 04BgN/rTWgmTgzkoWGCYXNFxV6u/ZCY2m5clPyYUCbNnMueH02RLfP0Rqq6DN8hb0njzWFPU9Fo=
< x-amz-request-id: 57864076DD887CAD
< x-amz-version-id: QR74caAngv_n5rt8m5v5866nj_NBXj5E
< Connection: keep-alive
< Elapsed: 00:00.016379


DEBUG conda.core.subdir_data:_load(221): 304 NOT MODIFIED for 'https://repo.anaconda.com/pkgs/main/win-64'. Updating mtime and loading from disk
DEBUG conda.core.subdir_data:_read_pickled(284): found pickle file C:\Users\Carson\Anaconda3\pkgs\cache\59ba4880.q
done
Solving environment: ...working... DEBUG conda.resolve:bad_installed(886): Checking if the current environment is consistent
DEBUG conda.core.solve:_find_inconsistent_packages(355): inconsistent precs: None
DEBUG conda.resolve:get_reduced_index(354): Retrieving packages for:
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - openssl=1.1.1a
  - pip=19.0.1
  - python=3.6.8
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
DEBUG conda.resolve:filter_group(400): openssl: pruned from 54 -> 2
DEBUG conda.resolve:filter_group(400): vc: pruned from 10 -> 5
DEBUG conda.resolve:filter_group(400): pip: pruned from 127 -> 3
DEBUG conda.resolve:filter_group(400): python: pruned from 131 -> 75
DEBUG conda.resolve:filter_group(400): setuptools: pruned from 251 -> 98
DEBUG conda.resolve:filter_group(400): wheel: pruned from 44 -> 29
DEBUG conda.resolve:filter_group(400): tk: pruned from 9 -> 2
DEBUG conda.resolve:filter_group(400): ca-certificates: pruned from 4 -> 1
DEBUG conda.resolve:filter_group(400): xz: pruned from 9 -> 2
DEBUG conda.resolve:filter_group(400): wheel: pruned from 29 -> 3
DEBUG conda.resolve:filter_group(400): python: pruned from 75 -> 3
DEBUG conda.resolve:filter_group(400): sqlite: pruned from 29 -> 2
DEBUG conda.resolve:filter_group(400): vc: pruned from 5 -> 2
DEBUG conda.resolve:filter_group(400): vs2015_runtime: pruned from 7 -> 1
DEBUG conda.resolve:filter_group(400): pip: pruned from 3 -> 1
DEBUG conda.resolve:filter_group(400): setuptools: pruned from 98 -> 18
DEBUG conda.resolve:filter_group(400): wheel: pruned from 3 -> 1
DEBUG conda.resolve:filter_group(400): setuptools: pruned from 18 -> 1
DEBUG conda.resolve:filter_group(400): certifi: pruned from 39 -> 8
DEBUG conda.resolve:filter_group(400): wincertstore: pruned from 7 -> 2
DEBUG conda.resolve:filter_group(400): zlib: pruned from 17 -> 3
DEBUG conda.resolve:filter_group(400): sqlite: pruned from 2 -> 1
DEBUG conda.resolve:filter_group(400): certifi: pruned from 8 -> 1
DEBUG conda.resolve:filter_group(400): openssl: pruned from 2 -> 1
DEBUG conda.resolve:filter_group(400): tk: pruned from 2 -> 1
DEBUG conda.resolve:filter_group(400): xz: pruned from 2 -> 1
DEBUG conda.common.logic:get_sat_solver_cls(281): Using SAT solver interface 'pycosat'.
DEBUG conda.resolve:gen_clauses(688): gen_clauses returning with clause count: 102
DEBUG conda.resolve:generate_spec_constraints(696): generate_spec_constraints returning with clause count: 102
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 113
DEBUG conda.core.solve:_run_sat(499): final specs to add:
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - openssl=1.1.1a
  - pip=19.0.1
  - python=3.6.8
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
DEBUG conda.resolve:solve(1005): Solving for:
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - openssl=1.1.1a
  - pip=19.0.1
  - python=3.6.8
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
DEBUG conda.resolve:solve(1008): Solve: Getting reduced index of compliant packages
DEBUG conda.resolve:solve(1017): Solve: determining satisfiability
DEBUG conda.resolve:gen_clauses(688): gen_clauses returning with clause count: 102
DEBUG conda.resolve:generate_spec_constraints(696): generate_spec_constraints returning with clause count: 102
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 113
DEBUG conda.resolve:solve(1065): Solve: minimize removed packages
DEBUG conda.resolve:solve(1072): Solve: maximize versions of requested packages
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.resolve:solve(1076): Initial package channel/version metric: 0/0
DEBUG conda.resolve:solve(1079): Solve: minimize track_feature count
DEBUG conda.resolve:generate_feature_count(704): generate_feature_count returning with clause count: 116
DEBUG conda.common.logic:minimize(805): Clauses added, recomputing solution
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 116
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 117
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 117
DEBUG conda.common.logic:minimize(889): Final sum objective: 1
DEBUG conda.common.logic:minimize(901): New peak objective: 1
DEBUG conda.resolve:solve(1082): Track feature count: 1
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.resolve:solve(1093): Package misfeature count: 0
DEBUG conda.resolve:solve(1096): Solve: maximize build numbers of requested packages
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 121
DEBUG conda.common.logic:minimize(889): Final peak objective: 0
DEBUG conda.resolve:solve(1098): Initial package build metric: 0
DEBUG conda.resolve:solve(1102): Solve: minimize number of optional installations
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.resolve:solve(1105): Optional package install metric: 0
DEBUG conda.resolve:solve(1108): Solve: minimize number of necessary upgrades
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.resolve:solve(1111): Dependency update count: 0
DEBUG conda.resolve:solve(1114): Solve: maximize versions and builds of indirect dependencies
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 122
DEBUG conda.common.logic:minimize(889): Final sum objective: 0
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.common.logic:minimize(811): Empty objective, trivial solution
DEBUG conda.resolve:solve(1120): Additional package channel/version/build metrics: 0/0/0
DEBUG conda.resolve:solve(1123): Solve: prune unnecessary packages
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 125
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 127
DEBUG conda.common.logic:minimize(889): Final sum objective: 3
DEBUG conda.common.logic:minimize(901): New peak objective: 1
DEBUG conda.resolve:solve(1126): Weak dependency count: 3
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 128
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 128
DEBUG conda.common.logic:minimize(889): Final sum objective: 0
DEBUG conda.resolve:solve(1133): Timestamp metric: 0
DEBUG conda.resolve:solve(1135): Looking for alternate solutions
DEBUG conda.common.logic:_run_sat(734): Invoking SAT with clause count: 129
done
DEBUG conda.core.solve:solve_final_state(252): solved prefix C:\Users\Carson\Anaconda3\envs\raven
  solved_linked_dists:
    defaults::ca-certificates-2019.1.23-0
    defaults::vs2015_runtime-14.15.26706-h3a45250_0
    defaults::vc-14.1-h0510ff6_4
    defaults::openssl-1.1.1a-he774522_0
    defaults::sqlite-3.26.0-he774522_0
    defaults::tk-8.6.8-hfa6e2cd_0
    defaults::xz-5.2.4-h2fa13f4_4
    defaults::zlib-1.2.11-h62dcd97_3
    defaults::python-3.6.8-h9f7ef89_7
    defaults::certifi-2018.11.29-py36_0
    defaults::wincertstore-0.2-py36h7fe50ca_0
    defaults::setuptools-40.8.0-py36_0
    defaults::wheel-0.32.3-py36_0
    defaults::pip-19.0.1-py36_0

INFO conda.core.link:__init__(169): initializing UnlinkLinkTransaction with
  target_prefix: C:\Users\Carson\Anaconda3\envs\raven
  unlink_precs:

  link_precs:
    defaults::ca-certificates-2019.1.23-0
    defaults::vs2015_runtime-14.15.26706-h3a45250_0
    defaults::vc-14.1-h0510ff6_4
    defaults::openssl-1.1.1a-he774522_0
    defaults::sqlite-3.26.0-he774522_0
    defaults::tk-8.6.8-hfa6e2cd_0
    defaults::xz-5.2.4-h2fa13f4_4
    defaults::zlib-1.2.11-h62dcd97_3
    defaults::python-3.6.8-h9f7ef89_7
    defaults::certifi-2018.11.29-py36_0
    defaults::wincertstore-0.2-py36h7fe50ca_0
    defaults::setuptools-40.8.0-py36_0
    defaults::wheel-0.32.3-py36_0
    defaults::pip-19.0.1-py36_0

DEBUG conda.core.package_cache_data:__init__(561): instantiating ProgressiveFetchExtract with
  defaults::setuptools-40.8.0-py36_0
  defaults::python-3.6.8-h9f7ef89_7
  defaults::wincertstore-0.2-py36h7fe50ca_0
  defaults::tk-8.6.8-hfa6e2cd_0
  defaults::certifi-2018.11.29-py36_0
  defaults::vs2015_runtime-14.15.26706-h3a45250_0
  defaults::openssl-1.1.1a-he774522_0
  defaults::xz-5.2.4-h2fa13f4_4
  defaults::sqlite-3.26.0-he774522_0
  defaults::pip-19.0.1-py36_0
  defaults::vc-14.1-h0510ff6_4
  defaults::zlib-1.2.11-h62dcd97_3
  defaults::ca-certificates-2019.1.23-0
  defaults::wheel-0.32.3-py36_0

DEBUG conda.core.package_cache_data:_check_writable(252): package cache directory 'C:\Users\Carson\Anaconda3\pkgs' writable: True
Preparing transaction: ...working... DEBUG conda.core.package_cache_data:_check_writable(252): package cache directory 'C:\Users\Carson\AppData\Local\conda\conda\pkgs' writable: True
DEBUG conda.core.link:_get_python_version(661): found in current transaction python version 3.6.8
done
Verifying transaction: ...working... done
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGABRT
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGINT
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGTERM
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGBREAK
Executing transaction: ...working... INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::ca-certificates-2019.1.23-0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\ca-certificates-2019.1.23-0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::vs2015_runtime-14.15.26706-h3a45250_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\vs2015_runtime-14.15.26706-h3a45250_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::vc-14.1-h0510ff6_4 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\vc-14.1-h0510ff6_4

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::openssl-1.1.1a-he774522_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\openssl-1.1.1a-he774522_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::sqlite-3.26.0-he774522_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\sqlite-3.26.0-he774522_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::tk-8.6.8-hfa6e2cd_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\tk-8.6.8-hfa6e2cd_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::xz-5.2.4-h2fa13f4_4 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\xz-5.2.4-h2fa13f4_4

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::zlib-1.2.11-h62dcd97_3 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\zlib-1.2.11-h62dcd97_3

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::python-3.6.8-h9f7ef89_7 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\python-3.6.8-h9f7ef89_7

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::certifi-2018.11.29-py36_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\certifi-2018.11.29-py36_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::wincertstore-0.2-py36h7fe50ca_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\wincertstore-0.2-py36h7fe50ca_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::setuptools-40.8.0-py36_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\setuptools-40.8.0-py36_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::wheel-0.32.3-py36_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\wheel-0.32.3-py36_0

INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: defaults::pip-19.0.1-py36_0 <===
  prefix=C:\Users\Carson\Anaconda3\envs\raven
  source=C:\Users\Carson\Anaconda3\pkgs\pip-19.0.1-py36_0

done
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGABRT
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGINT
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGTERM
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGBREAK
#
# To activate this environment, use
#
#     $ conda activate raven
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
I truly have no idea what to do here. The `environment_windows.yml` file is shown below:
```
name: raven
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - openssl=1.1.1a
  - pip=19.0.1
  - python=3.6.8
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - click==7.0
    - click-plugins==1.0.4
    - delegator.py==0.1.1
    - future==0.17.1
    - pexpect==4.6.0
    - prompt-toolkit==1.0.15
    - ptyprocess==0.6.0
    - pygments==2.3.1
    - pyinquirer==1.0.3
    - regex==2019.2.21
    - six==1.12.0
    - wcwidth==0.1.7
    - whaaaaat==0.5.2
prefix: /home/carson/anaconda3/envs/raven
```

### Steps to Reproduce
Copy the `environment_windows.yml` file from above, then run the below command inside Anaconda Prompt on Windows 10.
```
conda env create --file-./environment_windows.yml -v -v
```

## Expected Behavior
The packages listed in the yml should be installed to the created conda env, however they are not.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : base
    active env location : C:\Users\Carson\Anaconda3
            shell level : 1
       user config file : C:\Users\Carson\.condarc
 populated config files : C:\Users\Carson\.condarc
          conda version : 4.6.7
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\Carson\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Carson\Anaconda3\pkgs
                          C:\Users\Carson\.conda\pkgs
                          C:\Users\Carson\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Carson\Anaconda3\envs
                          C:\Users\Carson\.conda\envs
                          C:\Users\Carson\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Carson\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  2018.12                  py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.6                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.1.0                    py37_0    defaults
astropy                   3.1              py37he774522_0    defaults
atomicwrites              1.2.1                    py37_0    defaults
attrs                     18.2.0           py37h28b3542_0    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.6.3                    py37_0    defaults
bitarray                  0.8.3            py37hfa6e2cd_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py37_0    defaults
bleach                    3.0.2                    py37_0    defaults
blosc                     1.14.4               he51fdeb_0    defaults
bokeh                     1.0.2                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h452e1ab_1    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37h74b6da3_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
click-plugins             1.0.4                    pypi_0    pypi
cloudpickle               0.6.1                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
comtypes                  1.1.7                    py37_0    defaults
conda                     4.6.7                    py37_0    defaults
conda-build               3.17.6                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.1                    py37_0    defaults
console_shortcut          0.1.1                         3    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.4.2            py37h7a1dbc1_0    defaults
curl                      7.63.0            h2a8f88b_1000    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.2           py37ha925a31_0    defaults
cytoolz                   0.9.0.1          py37hfa6e2cd_1    defaults
dask                      1.0.0                    py37_0    defaults
dask-core                 1.0.0                    py37_0    defaults
datashape                 0.5.4                    py37_1    defaults
decorator                 4.3.0                    py37_0    defaults
defusedxml                0.5.0                    py37_1    defaults
delegator-py              0.1.1                    pypi_0    pypi
distributed               1.25.1                   py37_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.2.3                    py37_2    defaults
et_xmlfile                1.0.1                    py37_0    defaults
fastcache                 1.0.2            py37hfa6e2cd_2    defaults
filelock                  3.0.10                   py37_0    defaults
flask                     1.0.2                    py37_1    defaults
flask-cors                3.0.7                    py37_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.17.1                   py37_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.3.7            py37he774522_1    defaults
glob2                     0.6                      py37_1    defaults
greenlet                  0.4.15           py37hfa6e2cd_0    defaults
h5py                      2.8.0            py37h3bdd7fb_2    defaults
hdf5                      1.10.2               hac2f561_1    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.4.1                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.6                      py37_0    defaults
intel-openmp              2019.1                      144    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.2.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
isort                     4.3.4                    py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.13.2                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.35.3                   py37_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
keyring                   17.0.0                   py37_0    defaults
kiwisolver                1.0.1            py37h6538335_0    defaults
krb5                      1.16.1               hc04afaa_7    defaults
lazy-object-proxy         1.3.1            py37hfa6e2cd_2    defaults
libarchive                3.3.3                h0643e63_5    defaults
libcurl                   7.63.0            h2a8f88b_1000    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.35               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.0                h7a1dbc1_4    defaults
libtiff                   4.0.9                h36446d0_2    defaults
libxml2                   2.9.8                hadb2253_1    defaults
libxslt                   1.1.32               hf6f1972_0    defaults
llvmlite                  0.26.0           py37ha925a31_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.2.5            py37hef2cd61_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.0            py37he774522_0    defaults
matplotlib                3.0.2            py37hc8f65d3_0    defaults
mccabe                    0.6.1                    py37_1    defaults
menuinst                  1.4.14           py37hfa6e2cd_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2019.1                      144    defaults
mkl-service               1.1.2            py37hb782905_5    defaults
mkl_fft                   1.0.6            py37h6288b17_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
more-itertools            4.3.0                    py37_0    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.5.6            py37he980bc4_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.4.0                    py37_1    defaults
nbformat                  4.4.0                    py37_0    defaults
networkx                  2.2                      py37_1    defaults
nltk                      3.4                      py37_1    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.7.4                    py37_0    defaults
numba                     0.41.0           py37hf9181ef_0    defaults
numexpr                   2.6.8            py37hdce8814_0    defaults
numpy                     1.15.4           py37h19fb1c0_0    defaults
numpy-base                1.15.4           py37hc3f5095_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
odo                       0.5.1                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.5.12                   py37_0    defaults
openssl                   1.1.1a               he774522_0    defaults
packaging                 18.0                     py37_0    defaults
pandas                    0.23.4           py37h830ac7b_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.1                    py37_0    defaults
partd                     0.3.9                    py37_0    defaults
path.py                   11.5.0                   py37_0    defaults
pathlib2                  2.3.3                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.6.0                    pypi_0    pypi
pickleshare               0.7.5                    py37_0    defaults
pillow                    5.3.0            py37hdc69c19_0    defaults
pip                       18.1                     py37_0    defaults
pkginfo                   1.4.2                    py37_1    defaults
pluggy                    0.8.0                    py37_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.5.0                    py37_0    defaults
prompt-toolkit            1.0.15                   pypi_0    pypi
psutil                    5.4.8            py37he774522_0    defaults
ptyprocess                0.6.0                    pypi_0    pypi
py                        1.7.0                    py37_0    defaults
pycodestyle               2.4.0                    py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37hfa6e2cd_9    defaults
pycurl                    7.43.0.2         py37h7a1dbc1_0    defaults
pyflakes                  2.0.0                    py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pyinquirer                1.0.3                    pypi_0    pypi
pylint                    2.2.2                    py37_0    defaults
pyodbc                    4.0.25           py37ha925a31_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pyparsing                 2.3.0                    py37_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.4.4            py37he6f6034_0    defaults
pytest                    4.0.2                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.2.0                    py37_0    defaults
pytest-openfiles          0.3.1                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.1                h8c8aaf0_6    defaults
python-dateutil           2.7.5                    py37_0    defaults
python-libarchive-c       2.8                      py37_6    defaults
pytz                      2018.7                   py37_0    defaults
pywavelets                1.0.1            py37h8c2d366_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyyaml                    3.13             py37hfa6e2cd_0    defaults
pyzmq                     17.1.2           py37hfa6e2cd_0    defaults
qt                        5.9.7            vc14h73c81de_0  [vc14]  defaults
qtawesome                 0.5.3                    py37_0    defaults
qtconsole                 4.4.3                    py37_0    defaults
qtpy                      1.5.2                    py37_0    defaults
regex                     2019.02.21               pypi_0    pypi
requests                  2.21.0                   py37_0    defaults
rope                      0.11.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
scikit-image              0.14.1           py37ha925a31_0    defaults
scikit-learn              0.20.1           py37h343c172_0    defaults
scipy                     1.1.0            py37h29ff71c_2    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                40.6.3                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.0.1                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
sphinx                    1.8.2                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.2                    py37_0    defaults
spyder-kernels            0.3.0                    py37_0    defaults
sqlalchemy                1.2.15           py37he774522_0    defaults
sqlite                    3.26.0               he774522_0    defaults
statsmodels               0.9.0            py37h452e1ab_0    defaults
sympy                     1.3                      py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   5.1.1            py37hfa6e2cd_0    defaults
tqdm                      4.28.1           py37h28b3542_0    defaults
traitlets                 4.3.2                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
whaaaaat                  0.5.2                    pypi_0    pypi
wheel                     0.32.3                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
win_inet_pton             1.0.1                    py37_1    defaults
win_unicode_console       0.5                      py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py37hfa6e2cd_2    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.2                    py37_0    defaults
xlwings                   0.15.1                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.2.5                he025d50_1    defaults
zict                      0.1.3                    py37_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults
```
</p></details>

**Comment by soapy1** [comment]
I can't seem to reproduce this. What is the output of listing the packages in the environment?
```
$ conda activate raven
$ conda list
```

**Comment by cSchubes** [comment]
@soapy1 here is my output inside the raven environment:
```
(raven) C:\Users\Me\Documents\Stuff\raven>conda list
# packages in environment at C:\Users\Carson\Anaconda3\envs\raven:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0
certifi                   2018.11.29               py36_0
openssl                   1.1.1a               he774522_0
pip                       19.0.1                   py36_0
python                    3.6.8                h9f7ef89_7
setuptools                40.8.0                   py36_0
sqlite                    3.26.0               he774522_0
tk                        8.6.8                hfa6e2cd_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py36_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.4                h2fa13f4_4
zlib                      1.2.11               h62dcd97_3
```

**Comment by msarahan** [comment]
I think you may be confusing conda with the "prefix" key at the bottom of your file.  That's a path from a linux system.  If this is the problem, conda should be giving you a better error about that path.

Try removing that key and see if it works.

**Comment by DerFlob** [comment]
Installing pip-dependencies from a .yaml-file stopped working for me with conda 4.6.7 as well. Previous versions 4.6.6 or earlier work fine.

@soapy1 Which version did you use to try to replicate this issue?
@msarahan I am on Windows as well, without a prefix key in my environment.yaml.

**Comment by YassineAbdelouadoud** [comment]
> 
> 
> Installing pip-dependencies from a .yaml-file stopped working for me with conda 4.6.7 as well. Previous versions 4.6.6 or earlier work fine.
> 
> @soapy1 Which version did you use to try to replicate this issue?
> @msarahan I am on Windows as well, without a prefix key in my environment.yaml.

Same behaviour here : no installation from pip dependencies since conda 4.6.7 on windows 10 or 7. This is reproducible with a very simple environment file : 

`name : dimosim_test2
dependencies :
    - python=2.7
    - pip:
        - lxml`

**Comment by pliantenergy** [comment]
> Same behaviour here : no installation from pip dependencies since conda 4.6.7 on windows 10 or 7. This is reproducible with a very simple environment file :
> 
> name : test_env
> dependencies :
> - python=2.7
> - pip:
> - lxml

I am also having this problem with environment .yml files and I reproduced it with @YassineAbdelouadoud 's test_env

There are no errors in creating the environment, but `conda list` in the new environment shows no `lxml` installation. Manually installing `lxml` with `pip` in the activated environment works fine.

**Comment by msarahan** [comment]
There was a problem with environment paths that had spaces.  This is fixed in conda 4.6.8:

conda update -c conda-canary conda

Please try it and see if it helps.

**Comment by zdog234** [comment]
@msarahan Unfortunately, I'm still getting this issue on 4.6.8

My `environment.yml`:
```
dependencies:
  - python=3.6
  - pytest
  - pip:
    - datarobot
```

Sorry for the not-very-informative comment. I don't have time rn to post more, but I'll try to dig into this a bit more later.

**Comment by zdog234** [comment]
I dug into `conda_env.pip_util.pip_subprocess`, and checked `stdout` and found this:

```
(Pdb) print(stdout)
Requirement already satisfied: datarobot in c:\users\zdufour\miniconda3\lib\site-packages (from -r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (2.15.0)
Requirement already satisfied: requests-toolbelt>=0.6 in c:\users\zdufour\miniconda3\lib\site-packages (from datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: urllib3>=1.23 in c:\users\zdufour\miniconda3\lib\site-packages (from datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (1.24.1)
Requirement already satisfied: pandas>=0.15 in c:\users\zdufour\miniconda3\lib\site-packages (from datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (0.24.2)
Requirement already satisfied: pyyaml>=3.11 in c:\users\zdufour\miniconda3\lib\site-packages (from datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (5.1)
Requirement already satisfied: requests>=2.21 in c:\users\zdufour\miniconda3\lib\site-packages (from datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: trafaret!=1.1.0,<2.0,>=0.7 in c:\users\zdufour\miniconda3\lib\site-packages (from datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\zdufour\miniconda3\lib\site-packages (from pandas>=0.15->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (2.8.0)
Requirement already satisfied: pytz>=2011k in c:\users\zdufour\miniconda3\lib\site-packages (from pandas>=0.15->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (2018.9)
Requirement already satisfied: numpy>=1.12.0 in c:\users\zdufour\miniconda3\lib\site-packages (from pandas>=0.15->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (1.16.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\zdufour\miniconda3\lib\site-packages (from requests>=2.21->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\zdufour\miniconda3\lib\site-packages (from requests>=2.21->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zdufour\miniconda3\lib\site-packages (from requests>=2.21->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (2019.3.9)
Requirement already satisfied: six>=1.5 in c:\users\zdufour\miniconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas>=0.15->datarobot->-r C:\Users\ZDUFOUR\project_directory\condaenv.5g2kh9ye.requirements.txt (line 1)) (1.12.0)
```

It seems like the temporary `.bat` command that gets run (which for me is 

`@CALL "C:\Users\ZDUFOUR\miniconda3\bin\conda" activate "C:\Users\ZDUFOUR\Documents\project_directory\venv"
@pip install -r "C:\Users\ZDUFOUR\Documents\project_directory\condaenv.5g2kh9ye.requirements.txt"`

Doesn't have the desired effect of installing into the `C:\Users\ZDUFOUR\Documents\project_directory\venv` directory

**Comment by zdog234** [comment]
conda 4.6.9 has fixed the issue for me:

`conda update -c conda-canary conda`

@msarahan , thanks so much for fixing this! You might be able to close this issue.

**Comment by msarahan** [comment]
Thanks for confirming @zdog234 - closing as fixed by #8435

**Comment by cSchubes** [comment]
Works for me using `conda update -c conda-canary conda` as well. Doing just `conda update conda` does NOT work, as it only upgrades to 4.6.8. 

Thanks!

**Comment by linmydreaml** [comment]
```
name: flugelhorn
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py37_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_0
  - openssl=1.0.2o=h26aff7b_0
  - pip=10.0.1=py37_0
  - python=3.7.0=hc167b69_0
  - readline=7.0=hc1231fa_4
  - setuptools=39.2.0=py37_0
  - sqlite=3.24.0=ha441bb4_0
  - tk=8.6.7=h35a86e2_3
  - wheel=0.31.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
prefix: C:\Users\aleksandr_sipko\AppData\Local\Continuum\anaconda3\envs\flugelhorn


```

Doesn't work!

**Comment by linmydreaml** [comment]
I've downgrated conda version to 4.6.6 but still the same error:

` conda install -f conda-4.6.6-py37_0.tar.bz2`

> CondaValueError: The target prefix is the base prefix. Aborting.

**Comment by zdog234** [comment]
It doesn't seem like you need to use prefix. Prefix is meant to be used when you want to put a conda environment in a nonstandard location (such as `./venv`)

Try removing prefix from your environment.yml file

**Comment by davidrpugh** [comment]
I was under the impression that the `prefix` key in the environment file is ignored. If you want to install into a different location, then you need to pass the prefix explicitly at the command line.

`conda env create --file environment.yml --prefix ./env`
