### ISSUE TITLE
Pip requirements not installed from environment YAML

### ISSUE THREAD

**Issue by addisonElliott** [conda/conda#8404]
## Current Behavior

On Windows, creating a new conda environment via an environment YAML completely fails to install the necessary specified pip dependencies. This issue only occurs when creating environment via Anaconda prompt and not via the Command Prompt.

This problem arose after upgrading to the latest conda (4.6.8). From my research on the matter, this seems to be commit that causes the issue: https://github.com/conda/conda/commit/2d37b81896f448375b62c9a78ede91ff057f602c

### Steps to Reproduce
1. Create environment with the following YAML file: `conda env create --file environment.yml`
```
# run: conda env create --file environment.yml
name: PATS
channels:
  - conda-forge
dependencies:
  - python=3
  - vtk>=8.2.0
  - numpy
  - matplotlib
  - scipy
  - pip:
    - pynrrd
    - pyqt5
    - pydicom
    - colorama
    - nibabel
    - matplotlib
    - imageio
    - pywt
    - polarTransform
    - pyqt5ac
```

**Note:** Experimented with different libraries, not causing the problem. Can use any YAML environment file that has pip dependencies.

2. Activate environment and call `pip list`, all pip packages will be missing. No output about installing pip dependencies from command prompt.

3. Repeat with `cmd.exe` and it works fine. Assuming you have ran `conda init` or have conda in the PATH.

## Expected Behavior

Anaconda should install the pip dependencies or show an error message.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : PATS
    active env location : C:\Users\Addison\Anaconda3\envs\PATS
            shell level : 2
       user config file : C:\Users\Addison\.condarc
 populated config files :
          conda version : 4.6.8
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Users\Addison\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Addison\Anaconda3\pkgs
                          C:\Users\Addison\.conda\pkgs
                          C:\Users\Addison\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Addison\Anaconda3\envs
                          C:\Users\Addison\.conda\envs
                          C:\Users\Addison\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

# Debugging

Here is the console output from attempting to install the environment. Note that I have added some custom print debug statements to track down what is going on. I commented out the deletion of the temporary requirements.txt file and changed the save path for the BAT file created to do the installation. They are shown below the log.

I then attempted to run the BAT file via the command line. I noticed that the conda path was wrong and I received the message "The specified path could not be found". 

The conda path was set to `C:/Users/Addison/Anaconda3/bin/conda`, but it **should** be `C:/Users/Addison/Anaconda3/condabin/conda`. I did not have the `CONDA_BAT` environment variable set in the Anaconda prompt. Now, either I should have the `CONDA_BAT` env. variable or the default path should be `condabin` rather than `bin` but either way I end up with an error.

I fixed this by calling `conda init` but I also had to give the `--anaconda-prompt` option. **Side-note:** Trying to create an environment from YAML file gave me a permissions error. I had to go back and run as admin. Kind of annoying and I don't have to do this with the Anaconda prompt shortcut.

Was I supposed to call `conda init` to setup my `CONDA_BAT`? Might be worthwhile to include some documentation on this...unless it already exists.

After getting the `CONDA_BAT` env variable setup, this still did not fix my issue. Same exact results. And running from the command would install my pip packages fine. I even took the **exact** command arguments that were passed to `Subprocess.POpen` and ran them in Windows (Win+R & type the commands in). It ran just fine...

No idea where to go from here. I'm going to revert back to an older version of conda since this process has been frustrating. Hopefully this issue is reproducible and helps to find a solution.

```
(base) C:\Users\Addison\Documents\PythonProjects\PATS>conda env create --file environment.yml
woah Dependencies([('conda', ['python=3', "vtk[version='>=8.2.0']", 'numpy', 'matplotlib', 'scipy', 'pip']), ('pip', ['pynrrd', 'pyqt5', 'pydicom', 'colorama', 'nibabel', 'matplotlib', 'imageio', 'pywt', 'polarTransform', 'pyqt5ac'])])
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ @CALL "C:\Users\Addison\Anaconda3\condabin\conda.bat" activate "C:\Users\Addison\Anaconda3\envs\PATS"

@@CALL "C:\Users\Addison\Anaconda3\envs\PATS\Scripts\.qt-post-link.bat"

done
install: ['install', '-r', '"C:\\Users\\Addison\\Documents\\PythonProjects\\PATS\\condaenv.evpds0fd.requirements.txt"']
@CALL "C:\Users\Addison\Anaconda3\condabin\conda.bat" activate "C:\Users\Addison\Anaconda3\envs\PATS"

@pip install -r "C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.evpds0fd.requirements.txt"
Okay, unsure: ['install', '-r', '"C:\\Users\\Addison\\Documents\\PythonProjects\\PATS\\condaenv.evpds0fd.requirements.txt"'] C:\Users\Addison\Anaconda3\envs\PATS None C:\Users\Addison\Documents\PythonProjects\PATS C:/Users/Addison/Desktop/test.bat ['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', 'C:/Users/Addison/Desktop/test.bat']
#
# To activate this environment, use
#
#     $ conda activate PATS
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\Addison\Documents\PythonProjects\PATS>conda activate PATS

(PATS) C:\Users\Addison\Documents\PythonProjects\PATS>pip list
Package         Version
--------------- ------------
certifi         2019.3.9
cycler          0.10.0
future          0.17.1
kiwisolver      1.0.1
matplotlib      3.0.3
mkl-fft         1.0.10
mkl-random      1.0.2
numpy           1.16.2
pip             19.0.3
pyparsing       2.3.1
python-dateutil 2.8.0
scipy           1.2.1
setuptools      40.8.0
six             1.12.0
tornado         6.0.1
vtk             -PKG-VERSION
wheel           0.33.1
wincertstore    0.2

(PATS) C:\Users\Addison\Documents\PythonProjects\PATS>
```

test.bat
```
@CALL "C:\Users\Addison\Anaconda3\condabin\conda.bat" activate "C:\Users\Addison\Anaconda3\envs\PATS"
@pip install -r "C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.evpds0fd.requirements.txt"
```

requirements.txt
```
pynrrd
pyqt5
pydicom
colorama
nibabel
matplotlib
imageio
pywt
polarTransform
pyqt5ac
```

**Edit:** I debugged some more because I was curious. I noticed that the `stderr` and `stdout` output from the process is not handled. Maybe it would be wise to output that in verbose mode?

Anyway, the output can be seen below. The interesting thing to note is that it's installing the pip requirements fine, but not in the **right** environment! It's installing in the base environment, not the newly created one.

```
(base) C:\Users\Addison\Documents\PythonProjects\PATS>conda env create --file environment.yml
woah Dependencies([('conda', ['python=3', "vtk[version='>=8.2.0']", 'numpy', 'matplotlib', 'scipy', 'pip']), ('pip', ['pynrrd', 'pyqt5', 'pydicom', 'colorama', 'nibabel', 'matplotlib', 'imageio', 'pywt', 'polarTransform', 'pyqt5ac'])])
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
woah C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt
test: ['install', '-r', '"C:\\Users\\Addison\\Documents\\PythonProjects\\PATS\\condaenv.gdun687f.requirements.txt"'] C:\Users\Addison\Anaconda3\envs\PATS2 None C:\Users\Addison\Documents\PythonProjects\PATS C:\Users\Addison\Anaconda3\envs\PATS2\.tmpdw6vobls.bat ['C:\\WINDOWS\\system32\\cmd.exe', '/d', '/c', 'C:\\Users\\Addison\\Anaconda3\\envs\\PATS2\\.tmpdw6vobls.bat']
test: Requirement already satisfied: pynrrd in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 1)) (0.3.6)
Requirement already satisfied: pyqt5 in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 2)) (5.12)
Requirement already satisfied: pydicom in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 3)) (1.2.2)
Requirement already satisfied: colorama in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: nibabel in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 5)) (2.3.3)
Requirement already satisfied: matplotlib in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 6)) (3.0.2)
Requirement already satisfied: imageio in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 7)) (2.4.1)
Requirement already satisfied: pywt in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 8)) (1.0.6)
Requirement already satisfied: polarTransform in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (2.0.0)
Requirement already satisfied: pyqt5ac in c:\users\addison\anaconda3\lib\site-packages (from -r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 10)) (1.0.3)
Requirement already satisfied: numpy>=1.11.1 in c:\users\addison\anaconda3\lib\site-packages (from pynrrd->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 1)) (1.15.4)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.14 in c:\users\addison\anaconda3\lib\site-packages (from pyqt5->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 2)) (4.19.14)
Requirement already satisfied: bz2file in c:\users\addison\anaconda3\lib\site-packages (from nibabel->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 5)) (0.98)
Requirement already satisfied: six>=1.3 in c:\users\addison\anaconda3\lib\site-packages (from nibabel->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 5)) (1.12.0)
Requirement already satisfied: cycler>=0.10 in c:\users\addison\anaconda3\lib\site-packages (from matplotlib->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\addison\anaconda3\lib\site-packages (from matplotlib->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\addison\anaconda3\lib\site-packages (from matplotlib->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 6)) (2.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\addison\anaconda3\lib\site-packages (from matplotlib->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 6)) (2.7.5)
Requirement already satisfied: requests in c:\users\addison\anaconda3\lib\site-packages (from pywt->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 8)) (2.21.0)
Requirement already satisfied: scikit-image in c:\users\addison\anaconda3\lib\site-packages (from polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (0.14.1)
Requirement already satisfied: scipy in c:\users\addison\anaconda3\lib\site-packages (from polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (1.1.0)
Requirement already satisfied: pyyaml in c:\users\addison\anaconda3\lib\site-packages (from pyqt5ac->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 10)) (3.13)
Requirement already satisfied: click in c:\users\addison\anaconda3\lib\site-packages (from pyqt5ac->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 10)) (7.0)
Requirement already satisfied: setuptools in c:\users\addison\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 6)) (40.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\addison\anaconda3\lib\site-packages (from requests->pywt->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 8)) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\addison\anaconda3\lib\site-packages (from requests->pywt->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 8)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\addison\anaconda3\lib\site-packages (from requests->pywt->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 8)) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\addison\anaconda3\lib\site-packages (from requests->pywt->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 8)) (1.24.1)
Requirement already satisfied: networkx>=1.8 in c:\users\addison\anaconda3\lib\site-packages (from scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (2.2)
Requirement already satisfied: pillow>=4.3.0 in c:\users\addison\anaconda3\lib\site-packages (from scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (5.3.0)
Requirement already satisfied: PyWavelets>=0.4.0 in c:\users\addison\anaconda3\lib\site-packages (from scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (1.0.1)
Requirement already satisfied: dask[array]>=0.9.0 in c:\users\addison\anaconda3\lib\site-packages (from scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (1.0.0)
Requirement already satisfied: cloudpickle>=0.2.1 in c:\users\addison\anaconda3\lib\site-packages (from scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (0.6.1)
Requirement already satisfied: decorator>=4.3.0 in c:\users\addison\anaconda3\lib\site-packages (from networkx>=1.8->scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (4.3.0)
Requirement already satisfied: toolz>=0.7.3; extra == "array" in c:\users\addison\anaconda3\lib\site-packages (from dask[array]>=0.9.0->scikit-image->polarTransform->-r C:\Users\Addison\Documents\PythonProjects\PATS\condaenv.gdun687f.requirements.txt (line 9)) (0.9.0)

#
# To activate this environment, use
#
#     $ conda activate PATS2
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\Addison\Documents\PythonProjects\PATS>
```

**Edit2:** I decided to edit the BAT file created and include an `echo %PATH%` and `where pip` to see what is going on. For some reason, the PATH variable gets messed up. As I said, if I run the **exact same** command with arguments from Windows afterwards, it all works fine. Something is happening on the `conda activate` side right after the environment is created...

```
"PATH: C:\Users\Addison\Anaconda3\;C:\Users\Addison\Anaconda3\Library\mingw-w64\bin;C:\Users\Addison\Anaconda3\Library\usr\bin;C:\Users\Addison\Anaconda3\Library\bin;C:\Users\Addison\Anaconda3\Scripts;C:\Users\Addison\Anaconda3\bin;C:\Users\Addison\Anaconda3\envs\PATS7;C:\Users\Addison\Anaconda3\envs\PATS7\Library\mingw-w64\bin;C:\Users\Addison\Anaconda3\envs\PATS7\Library\usr\bin;C:\Users\Addison\Anaconda3\envs\PATS7\Library\bin;C:\Users\Addison\Anaconda3\envs\PATS7\Scripts;C:\Users\Addison\Anaconda3\envs\PATS7\bin;C:\Users\Addison\Anaconda3\condabin;C:\Users\Addison\Anaconda3\condabin\;C:\Perl64\site\bin;C:\Perl64\bin;c:\program files\graphicsmagick-1.3.30-q16;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\ActiveTcl\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Calibre2\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;c:\iverilog\bin;c:\iverilog\gtkwave\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\MATLAB\R2018a\runtime\win64;C:\Program Files\MATLAB\R2018a\bin;C:\Program Files\MongoDB\Server\4.0\bin;C:\Users\Addison\Anaconda3\envs\PATS\Library\bin;C:\Users\Addison\AppData\Local\Microsoft\WindowsApps;;C:\Users\Addison\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Addison\AppData\Roaming\npm;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\intelFPGA\18.1\modelsim_ase\win32aloem;C:\intelFPGA_lite\18.1\modelsim_ase\win32aloem

(PATS7) C:\Users\Addison\Documents\PythonProjects\PATS>where pip
C:\Users\Addison\Anaconda3\Scripts\pip.exe
C:\Users\Addison\Anaconda3\envs\PATS7\Scripts\pip.exe
```

**Comment by jpgill86** [comment]
I have the same problem on Windows, and I followed a similar (though less thorough; good job @addisonElliott) debugging process before finally searching "condabin" in the issue tracker and landing here!

If I change [this line](https://github.com/conda/conda/blob/e3f1b5d64f77af0a077284704849f8e523974adc/conda/utils.py#L268) from

`conda_bat = env.get("CONDA_BAT", abspath(join(root_prefix, 'bin', 'conda')))`

to

`conda_bat = env.get("CONDA_BAT", abspath(join(root_prefix, 'condabin', 'conda')))`

then pip will install the dependencies, but in the base environment instead of the new environment, as @addisonElliott reported. Standard output is not printed to the screen while pip is running, as in older versions of conda, making it difficult to tell what's going on, but inserting a debugger breakpoint into `pip_subprocess` (described [here](https://github.com/conda/conda/issues/8347#issuecomment-467634205)) shows that the `stdout` variable contains the pip output.

I think this line of code originated [here](https://github.com/conda/conda/commit/9903f00aa0a6e985a11d1602c30b4efde44b1452#diff-315c016a32ef55653e67795ff2b18b7cR1016) (PR #8229; it has been moved between files since then, see PR #8263) in a commit that was originally [merged](https://github.com/conda/conda/commit/17c0b70891c81a2cb6a83119035c5e1e4903c625) into master on Feb 7 and first included in release 4.6.3. So, I would suspect that this issue has existed since then.

I have not figured out why pip is installing in base instead of the new environment.

**Comment by addisonElliott** [comment]
@jpgill86 Pretty much agree with everything you've stated. As for changing the `conda_bat` line, I noticed that if I run `conda init` then it will set the `CONDA_BAT` env. variable in the Anaconda prompt **I think**.

I am unable to figure out why the `conda activate` command is not working. I can run the BAT file generated in the exact same Anaconda prompt and it works fine.

**Comment by jpgill86** [comment]
**To recap my understanding so far, I see two problems:**

1. The default path to `conda_bat` is incorrect in Windows and should be changed.
2. Even when this is corrected, something goes wrong with environment activation in `pip_subprocess`, causing the pip dependencies to be installed in the base environment rather than the new environment.

**Regarding problem 1:**

> As for changing the `conda_bat` line, I noticed that if I run `conda init` then it will set the `CONDA_BAT` env. variable in the Anaconda prompt **I think**.

I haven't tried this yet and am a little hesitant to do so. I've never used `conda init` before, can see it's marked "experimental" by `conda --help`, and I'd like to avoid accidentally masking this problem for now. The `CONDA_BAT` environment variable is not set for me, so the default path for `conda_bat` gets used, which can only be fixed on my system by changing `'bin'` to `'condabin'`, as described [above](https://github.com/conda/conda/issues/8404#issuecomment-472951203).

**Regarding problem 2:**

> I am unable to figure out why the `conda activate` command is not working. I can run the BAT file generated in the exact same Anaconda prompt and it works fine.

Same here. I can run `cmd /d /c pathtobat` from either the Anaconda prompt or from the Windows prompt, as in

`cmd /d /c D:\Users\Jeffrey\Anaconda3\envs\myenv01\.tmpkj8o7sat.bat`

where `.tmpkj8o7sat.bat` and the `condaenv.ecgal3gd.requirements.txt` file it targeted were prevented from being deleted during setup. This works using either prompt, installing dependencies using pip in the correct (new) environment. I'm using `cmd /d /c pathtobat` since this is the form of the command returned to `pip_subprocess` in `command_args` by `wrap_subprocess_call`, determined [here](https://github.com/conda/conda/blob/e3f1b5d64f77af0a077284704849f8e523974adc/conda/utils.py#L277).

**Comment by msarahan** [comment]
Thanks for your helpful report and analysis.  We'll work on fixing this for the next release.

**Comment by msarahan** [comment]
I believe this test should cover this use case?

https://github.com/conda/conda/blob/master/tests/conda_env/test_env.py#L355-L379

I note that pip interop is enabled in the env creation in that test.  Maybe that's the missing piece?  I'll see if I can track down any other places where the wrong pip is getting used.  Unfortunately, falling through to later entries on PATH can have this sort of problem.  It may be that, or it may be clumsiness on our part for somehow referencing the base env when we shouldn't.

**Comment by addisonElliott** [comment]
I enabled pip interop and was able to reproduce the bug still. I enabled it two ways just to make sure:
1. `conda config --set pip_interop_enabled True`
2. `setx CONDA_PIP_INTEROP_ENABLED true`

Saved the `pip_argh.yml` file and attempted with that. Same result, `argh` was installed on `base` but not `test_argh`.

Not exactly sure how the test is passing unless it's not checking the right environment.

From what I can tell, the issue is that `conda activate <ENV>` is not working in the BAT file directly after the environment is created. The odd issue is that the BAT file can be run afterwards and it will work fine.

**Comment by wqp89324** [comment]
## Current Behavior

I think this is related to the reported issue: conda clone or import env fails, because of some pip subcommands.

### Steps to Reproduce

```
# run: conda env create --file environment.yml
name: test
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - blas=1.0
  - boto3=1.9.113
  - botocore=1.12.114
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.2
  - cryptography=2.6.1
  - docutils=0.14
  - icc_rt=2019.0.0
  - idna=2.8
  - intel-openmp=2019.1
  - jmespath=0.9.4
  - mkl=2018.0.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1b
  - pandas=0.24.2
  - pip=19.0.3
  - pycparser=2.19
  - pymysql=0.8.1
  - pyopenssl=19.0.0
  - pysocks=1.6.8
  - python=3.6.7
  - python-crfsuite=0.9.6
  - python-dateutil=2.8.0
  - pytz=2018.9
  - s3transfer=0.2.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools=40.8.0
  - six=1.12.0
  - urllib3=1.24.1
  - vc=14
  - vs2015_runtime=14.0.25420
  - wheel=0.33.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - pip:
    - absl-py==0.2.2
    - astor==0.6.2
    - bleach==1.5.0
    - gast==0.2.0
    - grpcio==1.13.0
    - h5py==2.8.0
    - html5lib==0.9999999
    - keras==2.2.0
    - keras-applications==1.0.2
    - keras-preprocessing==1.0.1
    - markdown==2.6.11
    - more-itertools==4.1.0
    - protobuf==3.6.0
    - pyyaml==3.12
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - werkzeug==0.14.1
```


## Environment Information
<details open><summary><code>`conda info`</code></summary><p>


```
active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\xxx\.condarc
 populated config files : C:\Users\xxx\.condarc
          conda version : 4.6.8
    conda-build version : 3.10.9
         python version : 3.6.6.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\xxx\.conda\pkgs
                          C:\Users\xxx\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\xxx\.conda\envs
                          C:\Users\xxx\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.15063
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

Error Message
```
CondaEnvException: Pip subcommand failed with
output: Requirement already satisfied: absl-py==0.2.2 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: astor==0.6.2 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 2)) (0.6.2)
Collecting bleach==1.5.0 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184d4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: gast==0.2.0 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 4)) (0.2.0)
Requirement already satisfied: grpcio==1.13.0 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 5)) (1.13.0)
Requirement already satisfied: h5py==2.8.0 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 6)) (2.8.0)
Collecting html5lib==0.9999999 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 7))
Collecting keras==2.2.0 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/68/12/4cabc5c01451eb3b413d19ea151f36e33026fc0efb932bf51bcaf54acbf5/Keras-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: keras-applications==1.0.2 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 9)) (1.0.2)
Requirement already satisfied: keras-preprocessing==1.0.1 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 10)) (1.0.1)
Collecting markdown==2.6.11 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl
Requirement already satisfied: more-itertools==4.1.0 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 12)) (4.1.0)
Collecting protobuf==3.6.0 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/75/7a/0dba607e50b97f6a89fa3f96e23bf56922fa59d748238b30507bfe361bbc/protobuf-3.6.0-cp36-cp36m-win_amd64.whl
Collecting pyyaml==3.12 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 14))
Collecting tensorboard==1.8.0 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/59/a6/0ae6092b7542cfedba6b2a1c9b8dceaf278238c39484f3ba03b03f07803c/tensorboard-1.8.0-py3-none-any.whl
Collecting tensorflow==1.8.0 (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/f4/88/980d7032b7408fcca5b0b8d420fcd97919197a9e7acf280ab74fc7db6993/tensorflow-1.8.0-cp36-cp36m-win_amd64.whl
Requirement already satisfied: termcolor==1.1.0 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: werkzeug==0.14.1 in c:\programdata\anaconda3\lib\site-packages (from -r D:\condaenv.vkgdtz1e.requirements.txt (line 18)) (0.14.1)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from absl-py==0.2.2->-r D:\condaenv.vkgdtz1e.requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: numpy>=1.7 in c:\programdata\anaconda3\lib\site-packages (from h5py==2.8.0->-r D:\condaenv.vkgdtz1e.requirements.txt (line 6)) (1.15.1)
Requirement already satisfied: scipy>=0.14 in c:\programdata\anaconda3\lib\site-packages (from keras==2.2.0->-r D:\condaenv.vkgdtz1e.requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from protobuf==3.6.0->-r D:\condaenv.vkgdtz1e.requirements.txt (line 13)) (39.1.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in c:\programdata\anaconda3\lib\site-packages (from tensorboard==1.8.0->-r D:\condaenv.vkgdtz1e.requirements.txt (line 15)) (0.31.1)
Installing collected packages: html5lib, bleach, pyyaml, keras, markdown, protobuf, tensorboard, tensorflow
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 2.1.4
    Uninstalling bleach-2.1.4:
      Successfully uninstalled bleach-2.1.4
  Found existing installation: PyYAML 3.13

error: The system cannot find the path specified.
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by msarahan** [comment]
@wqp89324 please file a separate issue.  There's two things there.  The first may be related:

```
error: The system cannot find the path specified.
```

The second is not:
```
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

It's not clear if this second thing is actually blocking anything, or if it's just noise.  I do think it's pip complaining about the conda package that is already present. Pip has grown that error message fairly recently.  It will take a long time to ferret out and fix all the conda packages that use a distutils install.  It would help to have conda-build catch this kind of thing and warn about it at package build time, but it's also going to annoy package builders.  Their packages work fine with conda - why should they do work so that pip can uninstall their packages?  In an ideal world, pip and conda would interoperate completely and cleanly, but that's not where we're at today.

**Comment by wqp89324** [comment]
@msarahan thanks for your reply, my situation is temporarily solved by reverting conda back to a previous version. I will wait for the next conda update to try again.

**Comment by msarahan** [comment]
Does the latter message about failure to uninstall sure up with the older conda?

**Comment by wqp89324** [comment]
Yes, I don't have a problem now.

**Comment by sappelhoff** [comment]
I have the same issue as reported in the OP.

- The pip dependencies are ignored when installing via
    - Anaconda Prompt
    - Powershell (with conda on my user env variables and having run `conda init` from Anaconda Prompt before)

- Repeat with cmd.exe and it works fine. Assuming you have ran conda init or have conda in the PATH.
    - I can confirm, with the standard cmd it works fine

Windows 10, conda 4.6.8

**Comment by jpgill86** [comment]
I believe this was was fixed in 4.6.9. See duplicate issue #8346. I think this issue can be closed.

**Comment by addisonElliott** [comment]
Thank you for notifying me. Confirmed that it is fixed.

**Comment by bfialkoff** [comment]
Im still experiencing this issue on windows 10. Conda is not installing my pip deps. I have tried:
1) listing pip explicitly as a dependency 
2) `conda update -c conda-canary conda`
3) `conda update`
4) uninstalling and reinstalling
5) installing from command prompt (run as admin)

Im at my wits end. Can anyone help?

**Comment by aplowman** [comment]
@bfialkoff I thought I had the same problem, but it turns out I had a typo in one of my pip package names, so the whole pip install script was failing. Worth checking!
