### ISSUE TITLE
Exception reactivating base when opening new bash window in TMUX 

### ISSUE THREAD

**Issue by timrae** [conda/conda#8565]
### Steps to Reproduce
0. Open new bash shell
0. Call `tmux`
0. Create a new sub-window inside tmux (e.g. `ctrl+B`-->`%`)
0. Exception thrown

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 138, in main
        return activator_main()
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 940, in main
        print(activator.execute(), end='')
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 173, in execute
        return getattr(self, self.command)()
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 150, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 275, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 297, in _build_activate_stack
        return self.build_reactivate()
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 442, in build_reactivate
        new_path = self.pathsep_join(self._replace_prefix_in_path(conda_prefix, conda_prefix))
      File "/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 555, in _replace_prefix_in_path
        if path_list[last_idx + 1] == library_bin_dir:
    IndexError: list index out of range

`$ /anaconda3/bin/conda shell.posix activate base`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/anaconda3/bin/conda
             CONDA_PREFIX=/anaconda3
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/anaconda3/bin/python
               CONDA_ROOT=/anaconda3
              CONDA_SHLVL=1
                     PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/anaconda3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /anaconda3
            shell level : 1
       user config file : /Users/timothy.rae/.condarc
 populated config files :
          conda version : 4.6.11
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda3/pkgs
                          /Users/timothy.rae/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/timothy.rae/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.1 Darwin/18.5.0 OSX/10.14.4
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

## Expected Behavior
`base` is successfully carried over to the new tmux window

## Environment Information

As shown in error message.

## Additional Information

`.bash_profile` contains the following (unmodified from install time) code:

```bash
# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
```

**Comment by timrae** [comment]
Note:

This is the line that causes the crash:

https://github.com/conda/conda/blob/master/conda/activate.py#L570

Git blame suggests that @msarahan might be responsible

**Comment by msarahan** [comment]
this should be fixed in conda 4.6.13, which is available now on conda-forge or the conda-canary channel.  Depending on how the test period goes, it will probably be out on defaults on Friday.

**Comment by timrae** [comment]
Thank you

**Comment by tgy** [comment]
I still have this issue. @timrae was it solved for you? I have conda `4.8.3`, `python version : 3.7.6.final.0`,

**Comment by grahams** [comment]
I also have an issue which appears to be the same:

https://gist.github.com/grahams/88e360331147dfe5ed2b27fa7ba21ed6

**Comment by jamt9000** [comment]
I had this issue in conda 4.8.4 and zsh on mac when programatically opening a new Terminal.app

**Comment by steventartakovsky-vungle** [comment]
I still have this issue
