### ISSUE TITLE
conda init interferes with custom powershell profile prompt

### ISSUE THREAD

**Issue by t-makaro** [conda/conda#8598]
I have a custom powershell prompt that sets up posh-git and a few other things by defining a function called prompt within my powershell profile. 
```powershell
function prompt {
    $origLastExitCode = $LASTEXITCODE
    Write-Host 'PS ' -ForegroundColor Darkcyan -nonewline
    Write-VcsStatus

    $maxPathLength = 80
    $curPath = $ExecutionContext.SessionState.Path.CurrentLocation.Path
    if ($curPath.Length -gt $maxPathLength) {
        $curPath = '...' + $curPath.SubString($curPath.Length - $maxPathLength + 3)
    }

    Write-Host $curPath -ForegroundColor White
    $LASTEXITCODE = $origLastExitCode
    "$('>' * ($nestedPromptLevel + 1)) "
}

# Enable git support
Import-Module posh-git
$global:GitPromptSettings.BeforeText = '['
$global:GitPromptSettings.AfterText  = '] '
```
Unfortunately, my custom prompt is completely ignored after upgrading to conda 4.6.14. Downgrading restores the functionality.

#8570 Seems to be the culprit.

**Comment by MrKriss** [comment]
Just tried with latest dev version it appears this is already fixed (the prompt backup function is now scoped correctly). Just need to make sure you define your custom prompt function before the conda hook in `C:\Users\username\Documents\WindowsPowerShell\profile.ps1`. That way conda can add its environment prefix to it.

**Comment by Seanny123** [comment]
I can confirm this work in conda `4.7.1` and would thus recommend closing this issue.

**Comment by itsalaidbacklife** [comment]
I am still having a similar issue on conda 4.7.5. 

After running conda init, my posh git no longer appends git info to each input line. I do not define a prompt function in my profile. My profile just cd's into a specified folder, imports posh-git, and defines some helper functions for changing directories, etc.

 I am confused by 

> Just need to make sure you define your custom prompt function before the conda hook in C:\Users\username\Documents\WindowsPowerShell\profile.ps1
because my profile does not define a custom prompt function, or have any direct reference to conda (though I am able to run conda commands successfully). I had been using the default prompt, and importing posh-git, which was overwriting it to include extra stuff. 

If I define an empty prompt() function before importing posh-git, I get the posh-git prompt, without the conda environment prefex. If I omit the prompt() function, I get the conda environment prefix and the current path, but none of the posh-git info. Is there a way to get both the conda prefix, and my posh-git info in my prompt?

**Comment by TTTPOB** [comment]
> 
> 
> I am still having a similar issue on conda 4.7.5.
> 
> After running conda init, my posh git no longer appends git info to each input line. I do not define a prompt function in my profile. My profile just cd's into a specified folder, imports posh-git, and defines some helper functions for changing directories, etc.
> 
> I am confused by
> 
> > Just need to make sure you define your custom prompt function before the conda hook in C:\Users\username\Documents\WindowsPowerShell\profile.ps1
> 
> because my profile does not define a custom prompt function, or have any direct reference to conda (though I am able to run conda commands successfully). I had been using the default prompt, and importing posh-git, which was overwriting it to include extra stuff.
> 
> If I define an empty prompt() function before importing posh-git, I get the posh-git prompt, without the conda environment prefex. If I omit the prompt() function, I get the conda environment prefix and the current path, but none of the posh-git info. Is there a way to get both the conda prefix, and my posh-git info in my prompt?

I dont know if you are still suffering from this. for me the solution is first to run
```powershell
conda init --reverse
```
to eliminate the effect of `conda init`
second add
```powershell
#region conda initialize
# !! Contents within this block are managed by 'conda init' !!
(& PATH_TO_CONDA_BIN\conda.exe shell.powershell hook) | Out-String | Invoke-Expression
#endregion
```
to your custom profile (`$profile`), remember to replace `PATH_TO_CONDA_BIN` to your path.
then you should be happy :)

**Comment by Japanuspus** [comment]
@itsalaidbacklife If you look at the posh-git docs, posh-git will not modify a non-standard prompt. For me a working solution was to simply put posh-git before anaconda in my `profile.ps1`.
