### ISSUE TITLE
conda create fails with "An unexpected error has occurred."

### ISSUE THREAD

**Issue by gboeing** [conda/conda#8963]
## Current Behavior

I freshly installed miniconda on windows this morning. I did some conda config steps (documented below) then tried to create a conda env, but it failed with "An unexpected error has occurred."

### Steps to Reproduce

Install miniconda on windows then open the anaconda prompt and run

```
conda config --set show_channel_urls true
conda config --set channel_priority strict
conda config --prepend channels conda-forge
conda update -n base conda
conda create -n test cartopy
```

The commands complete successfully, until the final command, which outputs:
```
(base) C:\>conda create -n test cartopy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\cli\main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\cli\install.py", line 256, in install
        force_reinstall=context.force_reinstall or context.force,
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\core\solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\core\solve.py", line 150, in solve_for_diff
        force_remove)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._run_sat(ssc)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\core\solve.py", line 780, in _run_sat
        repodata_fn=self._repodata_fn)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\resolve.py", line 1183, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\resolve.py", line 336, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\resolve.py", line 425, in build_conflict_map
        deps = set.union(*[set(self.ms_depends_.get(prec)) for prec in precs])
      File "C:\Users\Geoff\Miniconda3\lib\site-packages\conda\resolve.py", line 425, in <listcomp>
        deps = set.union(*[set(self.ms_depends_.get(prec)) for prec in precs])
    TypeError: 'NoneType' object is not iterable

`$ C:\Users\Geoff\Miniconda3\Scripts\conda-script.py create -n test cartopy`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_BAT=C:\Users\Geoff\Miniconda3\condabin\conda.bat
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Geoff\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Geoff\Miniconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\Geoff\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Geoff\Miniconda3\python.exe
               CONDA_ROOT=C:\Users\Geoff\Miniconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Geoff
                     PATH=C:\Users\Geoff\Miniconda3;C:\Users\Geoff\Miniconda3\Library\mingw-w64\
                          bin;C:\Users\Geoff\Miniconda3\Library\usr\bin;C:\Users\Geoff\Miniconda
                          3\Library\bin;C:\Users\Geoff\Miniconda3\Scripts;C:\Users\Geoff\Minicon
                          da3\bin;C:\Users\Geoff\Miniconda3;C:\Users\Geoff\Miniconda3\Library\mi
                          ngw-w64\bin;C:\Users\Geoff\Miniconda3\Library\usr\bin;C:\Users\Geoff\M
                          iniconda3\Library\bin;C:\Users\Geoff\Miniconda3\Scripts;C:\Users\Geoff
                          \Miniconda3\bin;C:\Users\Geoff\Miniconda3\condabin;C:\Program Files
                          (x86)\Common
                          Files\Oracle\Java\javapath;C:\ProgramData\DockerDesktop\version-
                          bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C
                          :\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShe
                          ll\v1.0;C:\Users\Geoff\AppData\Local\GitHub\PortableGit_d76a6a98c93159
                          31ec4927243517bc09e9b731a0\cmd;C:\Program Files\Git\cmd;C:\Program
                          Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\WINDOWS\Sy
                          stem32\OpenSSH;C:\Windows\System32;C:\Users\Geoff\AppData\Local\Micros
                          oft\WindowsApps;C:\Users\Geoff\AppData\Local\Microsoft\WindowsApps;G:\
                          texlive\2019\bin\win32;.;C:\Users\Geoff\Miniconda3\lib\site-
                          packages\pywin32_system32;C:\Users\Geoff\Miniconda3\lib\site-
                          packages\pywin32_system32
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Geoff\Miniconda3
            shell level : 1
       user config file : C:\Users\Geoff\.condarc
 populated config files : C:\Users\Geoff\.condarc
          conda version : 4.7.8
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\Geoff\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Geoff\Miniconda3\pkgs
                          C:\Users\Geoff\.conda\pkgs
                          C:\Users\Geoff\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Geoff\Miniconda3\envs
                          C:\Users\Geoff\.conda\envs
                          C:\Users\Geoff\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.8 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

## Expected Behavior

conda would create the environment without throwing an error

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(base) C:\>conda info

     active environment : base
    active env location : C:\Users\Geoff\Miniconda3
            shell level : 1
       user config file : C:\Users\Geoff\.condarc
 populated config files : C:\Users\Geoff\.condarc
          conda version : 4.7.8
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\Geoff\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Geoff\Miniconda3\pkgs
                          C:\Users\Geoff\.conda\pkgs
                          C:\Users\Geoff\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Geoff\Miniconda3\envs
                          C:\Users\Geoff\.conda\envs
                          C:\Users\Geoff\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.8 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(base) C:\>conda config --show-sources
==> C:\Users\Geoff\.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
show_channel_urls: True
report_errors: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(base) C:\>conda list --show-channel-urls
# packages in environment at C:\Users\Geoff\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
bzip2                     1.0.8                hfa6e2cd_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37hb32ad35_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.7.8                    py37_0    conda-forge
conda-package-handling    1.3.11                   py37_0    conda-forge
console_shortcut          0.1.1                         3    defaults
cryptography              2.7              py37hb32ad35_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
libarchive                3.3.3             h4890af2_1006    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libxml2                   2.9.9                h9ce36c8_2    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
lzo                       2.10              hfa6e2cd_1000    conda-forge
menuinst                  1.4.16                   py37_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
powershell_shortcut       0.0.1                         2    defaults
pycosat                   0.6.3           py37hfa6e2cd_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pywin32                   224             py37hfa6e2cd_1000    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.71         py37hfa6e2cd_1000    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hfa6e2cd_0    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.33.4                   py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1005    conda-forge
zstd                      1.4.0                hd8a0e53_0    conda-forge
```
</p></details>

**Comment by msarahan** [comment]
please try to update.  4.7.9 is currently on the conda-canary channel, and it should fix this issue.

**Comment by gboeing** [comment]
Thanks @msarahan that resolves it.

**Comment by ManuMahadevaswamy** [comment]
> conda env create -f environemnt.yml

@msarahan , I 'm using 4.8.3 version, but I'm still getting the same error

**Comment by ndamo** [comment]
I am having the same issue as @ManuMahadevaswamy. I am using version 4.8.3 too and I tried to reinstall conda but same problem.

**Comment by caselga** [comment]
Tried the following solution re UTF8 encoding and it worked for me:
https://stackoverflow.com/questions/60530958/conda-env-create-from-yml-gives-unexpected-error
