### ISSUE TITLE
Cannot activate environments (possibly to due to space in Windows 10 user name)

### ISSUE THREAD

**Issue by Tomalwo** [conda/conda#9562]
## Current Behavior

I cannot activate any conda environments including base.

I suspect that the issue is related to the fact that my windows username ("Thomas Wortmann") has a space. The username is tied to my windows account, which requires a format with "firstname lastname". I would prefer to not make a new windows account to run conda. 

### Steps to Reproduce

- Install Miniconda3
- Run Anaconda Prompt
- `conda activate base`
- Results in: 
```
The system cannot find the path specified.
activate does not accept more than one argument:
['base', 'Wortmann\\AppData\\Local\\Temp\\conda-32741-32674.tmp']
```

## Expected Behavior

I should not get this error message.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
 active environment : None
            shell level : 0
       user config file : C:\Users\Thomas Wortmann\.condarc
 populated config files : C:\Users\Thomas Wortmann\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\Thomas Wortmann\.conda\pkgs
                          C:\Users\Thomas Wortmann\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\Thomas Wortmann\.conda\envs
                          C:\Users\Thomas Wortmann\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Thomas Wortmann\.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                1.2.0                    py37_0    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.13.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
conda                     4.7.12                   py37_0    defaults
conda-package-handling    1.6.0            py37h62dcd97_0    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.16           py37he774522_0    defaults
openssl                   1.1.1d               he774522_3    defaults
pip                       19.3.1                   py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.4                h5263a28_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                41.4.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.30.0               he774522_0    defaults
tqdm                      4.36.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wheel                     0.33.6                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
```
</p></details>

**Comment by forrestwaters** [comment]
Closing in favor of #8888 ; this should be fixed by https://github.com/conda/conda/pull/9409 which was included in conda 4.8, we just need a new Anaconda/Miniconda release which should happen in the next couple months.

**Comment by Tomalwo** [comment]
OK thanks @forrestwaters , I'll try the workaround in [#8888](https://github.com/conda/conda/issues/8888) till then.

**Comment by anntzer** [comment]
I can confirm that this still doesn't work with the fix in #8888.

**Comment by Tomalwo** [comment]
@anntzer I have opened [#9757](issue.https://github.com/conda/conda/issues/9757) as a new (more precise, IMHO)

**Comment by anntzer** [comment]
thanks.
