### ISSUE TITLE
`conda env export` fails with InvalidVersionSpec

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#9624]
## Current Behavior

On `conda 4.8.0`, running `conda env export` sometimes fails with:

```
InvalidVersionSpec: Invalid version '(>=': unable to convert to expression tree: ['(']
```

I believe this is because of a mis-parse of some `pip` dependency.

### Steps to Reproduce

The clearest example of this is when you `pip install nb-black`:

```
$ docker run -i -t continuumio/miniconda3 /bin/bash
Unable to find image 'continuumio/miniconda3:latest' locally
latest: Pulling from continuumio/miniconda3
Digest: sha256:6c979670684d970f8ba934bf9b7bf42e77c30a22eb96af1f30a039b484719159
Status: Downloaded newer image for continuumio/miniconda3:latest
(base) root@c7e8acb830b8:/# pip install nb-black
...
(base) root@c7e8acb830b8:/# conda env export

InvalidVersionSpec: Invalid version '(>=': unable to convert to expression tree: ['(']

```

## Expected Behavior
Hopefully, `conda env export` should run perfectly fine

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /opt/anaconda
            shell level : 2
       user config file : /home/alan/.condarc
 populated config files : /home/alan/.condarc
          conda version : 4.8.0
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /home/alan/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /home/alan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.6 Linux/5.3.0-26-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /home/alan/.condarc <==
channel_priority: strict
channels:
  - pytorch
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /opt/anaconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
analysis                  0.1                       dev_0    <develop>
boto3                     1.11.6                     py_0    conda-forge
botocore                  1.14.6                     py_0    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cogdata                   0.1                       dev_0    <develop>
cogdata-service           0.1                       dev_0    <develop>
cogdevices                0.1                       dev_0    <develop>
conda                     4.8.0                    py37_1    conda-forge
conda-package-handling    1.6.0            py37h516909a_1    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
ctrl                      0.1                       dev_0    <develop>
ctrl-sdk                  0.1                       dev_0    <develop>
ctrl-sdk-internal         0.1                       dev_0    <develop>
ctrlflow                  0.1                       dev_0    <develop>
docutils                  0.15.2                   py37_0    conda-forge
greenlet                  0.4.15                   pypi_0    pypi
idna                      2.8                   py37_1000    conda-forge
ifaddr                    0.1.6                    pypi_0    pypi
jmespath                  0.9.4                      py_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
msgpack                   0.6.2                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
netifaces                 0.10.9                   pypi_0    pypi
numpy                     1.17.3                   pypi_0    pypi
openssl                   1.1.1d               h516909a_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pybmi                     0.1                       dev_0    <develop>
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pynvim                    0.3.2                    pypi_0    pypi
pyopenssl                 19.1.0                   py37_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.6                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.80         py37h516909a_1000    conda-forge
s3transfer                0.3.1                    py37_0    conda-forge
setuptools                45.1.0                   py37_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
symspellpy                6.5.2                    pypi_0    pypi
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.41.1                     py_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
websockets                8.1                      pypi_0    pypi
wheel                     0.33.6                   py37_0    conda-forge
workflow                  0.1                       dev_0    <develop>
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeroconf                  0.23.0                   pypi_0    pypi
zlib                      1.2.11            h516909a_1006    conda-forge
```
</p></details>

**Comment by alanhdu** [comment]
I've tracked this down to `conda.common.pkg_formats.python.parse_specification`: if you feed in `black (>='19.3') ; python_version >= "3.6"` as an input, it chokes on the parenthesis.

**Comment by theRealSuperMario** [comment]
Did I understand correctly that this issue is fixed?

If so, how can I update my conda version to get this to work ? I tried `conda update Conda` which gives me version `4.8.4`, but this won't do it.

**Comment by wisekh6** [comment]
Is this issue fixed?
`conda update conda` (which install `conda 4.8.5`) does not resolve it.

**Comment by joshjavier** [comment]
I'm also having the same issue with Conda 4.8.3. Tried running `conda env export > environment.yml`, which resulted in an error:
```
InvalidVersionSpec: Invalid version '(>=': unable to convert to expression tree: ['(']
```

**Comment by ariasjose** [comment]
> I'm also having the same issue with Conda 4.8.3. Tried running `conda env export > environment.yml`, which resulted in an error:
> 
> ```
> InvalidVersionSpec: Invalid version '(>=': unable to convert to expression tree: ['(']
> ```

Same issue with same conda version, hope we have a quick fix for this.

**Comment by dutchminator** [comment]
Same issue here, conda 4.9.2.

**Comment by rbavery** [comment]
Same issue here.

```
→ conda env export > app-environment-exp.yml

InvalidVersionSpec: Invalid version '3.0.2geopandas>=0.7.0': invalid character(s)

(cropmask) 
# rave at rave-desktop in ~/CropMask_RCNN/app on git:pytorchapi ✖︎ [0:09:17]
→ conda --version                           
conda 4.9.2
```

Happy to provide more info if it is needed.

**Comment by benslack19** [comment]
> Same issue here, conda 4.9.2. It fails on single quotes in the dependencies for pip-installed nb_black.
> 
> Manually editing the dependencies for `nb_black` from
> 
> > Requires-Dist: yapf (>='0.28') ; python_version < "3.6"
> > Requires-Dist: black (>='19.3') ; python_version >= "3.6"
> 
> to
> 
> > Requires-Dist: yapf (>=0.28) ; python_version < "3.6"
> > Requires-Dist: black (>=19.3) ; python_version >= "3.6"
> 
> in `/Users/[USERNAME]/opt/anaconda3/envs/[ENVNAME]/lib/python3.6/site-packages/nb_black-1.0.7.dist-info/` resolves the issue as a work-around.

Thank you for this workaround. To be clear, the relevant text was found in the `METADATA` file in this folder.

**Comment by RLashofRegas** [comment]
FYI for those like me who stumbled across this but don't have nb_black installed:
The error message for me was  `InvalidVersionSpec: Invalid version '4.7.0<4.8.0': invalid character(s)`
The issue for me was in the redshift_connector package. On Windows I ran this in powershell from my `C:\Users\<user>\Anaconda3\envs\<env name>\Lib\site-packages\` folder:
`Get-ChildItem -File -Recurse -Filter METADATA | Select-String "4.7.0<4.8.0" | Select-Object -Unique Path`
In the file I found a bunch of lines like this: `Requires-Dist: scramp (>=1.2.0<1.3.0)` (missing comma between version specs). After adding the commas `conda env export` worked.

**Comment by evanli05** [comment]
> Same issue here, conda 4.9.2. It fails on single quotes in the dependencies for pip-installed nb_black.
> 
> Manually editing the dependencies for `nb_black` from
> 
> > Requires-Dist: yapf (>='0.28') ; python_version < "3.6"
> > Requires-Dist: black (>='19.3') ; python_version >= "3.6"
> 
> to
> 
> > Requires-Dist: yapf (>=0.28) ; python_version < "3.6"
> > Requires-Dist: black (>=19.3) ; python_version >= "3.6"
> 
> in `/Users/[USERNAME]/opt/anaconda3/envs/[ENVNAME]/lib/python3.6/site-packages/nb_black-1.0.7.dist-info/` resolves the issue as a work-around.

Thanks, this one did the trick.

**Comment by blacksun-V** [comment]
How to determine which package is causing the error ？

**Comment by 60south** [comment]
Still fails under conda 22.9.0

**Comment by gaurav274** [comment]
> How to determine which package is causing the error ？

`conda env export -vv`

**Comment by 60south** [comment]
> conda env export -vv

Gives a traceback but still doesn't identify the offending package.

**Comment by bio-la** [comment]
having the same issue, but i can `conda env export` on other environments. I read somewhere that `conda-forge` seemed to be the problem, but it's not the case for my environments which have `conda-forge` channel and don't give me any problem.

**Comment by loongmxbt** [comment]
Same issue, some package skip an xarray version, thus cause `KeyError !=2022.06`

**Comment by vikramaditya91** [comment]
Same issue with 
[`    - jupyter_core >=4.12,!=5.0.*`](https://github.com/conda-forge/jupyter_server-feedstock/blob/main/recipe/meta.yaml#L31)


Do the maintainers of `conda` think that this is an issue of `conda-forge` or something for `conda` to fix?

**Comment by stefanpricopie** [comment]
Same issue with `pyro-ppl-1.8.6-pyhd8ed1ab_0.json`
`conda.exceptions.InvalidVersionSpec: Invalid version '2.0<3': invalid character(s)`

**Comment by void-mckenzie** [comment]
> FYI for those like me who stumbled across this but don't have nb_black installed: The error message for me was `InvalidVersionSpec: Invalid version '4.7.0<4.8.0': invalid character(s)` The issue for me was in the redshift_connector package. On Windows I ran this in powershell from my `C:\Users\<user>\Anaconda3\envs\<env name>\Lib\site-packages\` folder: `Get-ChildItem -File -Recurse -Filter METADATA | Select-String "4.7.0<4.8.0" | Select-Object -Unique Path` In the file I found a bunch of lines like this: `Requires-Dist: scramp (>=1.2.0<1.3.0)` (missing comma between version specs). After adding the commas `conda env export` worked.

This solved it for me, thanks a ton!

**Comment by acgvar** [comment]
I have a linux terminal (OpenSUSE).

The error came about when I used the command
```
conda env export > environment.yml
```
The error appears as 
```
InvalidVersionSpec: Invalid version '(>=': unable to convert to expression tree: ['(']
```

Solution:
I went to the folder,
```
/Users/[USERNAME]/opt/anaconda3/envs/[ENVNAME]/lib/python3.6/site-packages/
```
where `[ENVNAME]` is the current environment.

I found the erroneous file in that folder by typing,
```
grep -iR "(>='" ./*/METADATA
```
It should list the `METADATA` files that contains the string `(>='` (e.g. `./flox-0.6.7.dist-info/METADATA:Requires-Dist: numpy (>='1.20')`). I edited those files and removed the single quotes (e.g. `(>=1.20)`).

After that, the export command works.

I hope this helps.
