### ISSUE TITLE
Windows 10 install get stuck at extract: anaconda-2020.02-py37_0.tar.bz2

### ISSUE THREAD

**Issue by krakken1972** [conda/conda#9867]
## Current Behavior

when running installation of 2020.02 file on Windows 10.  it gets stuck on the tar file specified.  There are several people with this issue on Stack Overflow.

### Steps to Reproduce

```
Run installation as Admin or standard user.
```

## Expected Behavior

Install should complete fully

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
We really need you to include more information before we're able to help. Please provide information sufficient for someone else to reproduce the issue you're seeing.

**Comment by samcarey** [comment]
I had the same issue installing miniconda on Windows 10, version 1803.

This hangs at extracting conda-4.8.2-py37_0: https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe

This one installs just fine: https://repo.anaconda.com/miniconda/Miniconda3-4.7.12.1-Windows-x86_64.exe

**Comment by krakken1972** [comment]
> We really need you to include more information before we're able to help. Please provide information sufficient for someone else to reproduce the issue you're seeing.

@kalefranz Sorry, but there's not much more to tell.  I literally run the installer as an Admin and it hangs on that file for hours and hours at the extract step per the detailed view.  No  error messages are generated.   I used the 2019 installer and it works fine.

**Comment by mingwandroid** [comment]
@kalefranz this is probably the 64 threads or more problem. @krakken1972 what cpu have you?

**Comment by krakken1972** [comment]
i5-8350U 1.7GhZ running Windows 10 64 bit.

**Comment by SuryaKiran523** [comment]
Hello, 
I have the same issue on my work machine i7-8650U CPU @ 1.90GHz 2.11 GHz, but it installed fine on my personal machine i7-4710MQ CPU @ 2.50GHz 2.50 GHz.

"Extract: anaconda-2020.02-py37_0.tar.bz2" --> Installation was struck at this stage. After waiting for couple of hours I opened and ended the tasks that were ideal for very long in Task Manager. Looks like this issue is with only 64-bit version. When installing Anaconda 64-bit version in my task manager it shows "Anaconda installer (32-bit), is this normal?

**Comment by robson76** [comment]
As mentioned by ClaraJacintho in https://github.com/ContinuumIO/anaconda-issues/issues/6258#issuecomment-565063685:

_I found that the "security module" called Warsaw (or GAS antifraud), used by many banks in Brazil for internet banking security, was interfering with the installation. I uninstalled it and was able to install Anaconda3.2019.10 64 bits on my Windows 10 machine._

It worked for me.

**Comment by s4m0r4m4** [comment]
I have run into this same issue with the 2020.02 installer for 64 bit. I can't run any of the conda commands requested in the intial post, since I can't install anaconda. The intaller hangs at the "Extract: anaconda-2020.02-py37_0.tar.bz2" line and sits at 0 CPU usage and 2.2MB memory.

I'm on Windows server 2016.

This one installs just fine:  https://repo.anaconda.com/archive/Anaconda3-2019.10-Windows-x86_64.exe

**Comment by coolboxGit** [comment]
Just tried installing it today and got exactly same problem.

**Comment by willgittoes** [comment]
I get the same problem.

```
         Operating System: Windows 10 Pro 64-bit (10.0, Build 18362) (18362.19h1_release.190318-1202)
                 Language: English (Regional Setting: English)
      System Manufacturer: System manufacturer
             System Model: System Product Name
                     BIOS: 1002 (type: UEFI)
                Processor: AMD Ryzen Threadripper 2990WX 32-Core Processor (64 CPUs), ~3.0GHz
                   Memory: 65536MB RAM
      Available OS Memory: 65408MB RAM
                Page File: 11635MB used, 123404MB available
```

Furthermore, after waiting for 10 minutes the system hard crashed - something I've not had before on this machine.

**Comment by mingwandroid** [comment]
Please install miniconda then conda install anaconda=2020.02.

This upstream Cpython bug is fixed in the miniconda installer but we haven't released an anaconda installer with the fix yet. Those come out on a quarterly schedule.

**Comment by drishh207** [comment]
> I have run into this same issue with the 2020.02 installer for 64 bit. I can't run any of the conda commands requested in the intial post, since I can't install anaconda. The intaller hangs at the "Extract: anaconda-2020.02-py37_0.tar.bz2" line and sits at 0 CPU usage and 2.2MB memory.
> 
> I'm on Windows server 2016.
> 
> This one installs just fine: https://repo.anaconda.com/archive/Anaconda3-2019.10-Windows-x86_64.exe

Does this really works..because I am facing the same problem?

**Comment by sutongkui** [comment]
The same problem for my new PC with AMD 3970, win10. Miniconda works well, thanks @mingwandroid

**Comment by mingwandroid** [comment]
Anaconda 2020.07 has now been released and includes this fix. Thanks!

**Comment by stshap** [comment]
I just trying installing Anaconda 2020.07 and faced the same issue as described - i.e., I don't think the issue is resolved

**Comment by ankush2kn** [comment]
Same for me on my Windows 10 machine - not solved.
Tried installing: Anaconda3-2020.07-Windows-x86_64
Installer is stuck at extracting: anaconda-2020.07-py38_0.tar.bz2

**Comment by luckydad** [comment]
Same for me on Windows 10. 
Installed Anaconda3-2020.07-Windows-x86_64.exe as Admin 
and it gets stuck at 

Extract: anaconda-2020.07-py38_0.tar.bz2

Same experience with 2020.02
2019.10 version installed successfully but that is Python 2.7! 
Please advise.

**Comment by haph-vi** [comment]
Had the same issue with 2020.07 but it continued almost exactly after reading this whole thread.
So maybe the issue is resolved but it takes longer to install than normal and some (like myself) think it's the same issue as before.

**Comment by cbracketdash** [comment]
I have the same issue. I am going to try letting it run overnight to see if it finishes

**Comment by cbracketdash** [comment]
GUYS, I let Miniconda installer run all night (even though it was stuck at the tar.bz2) AND IT FINISHED INSTALLING. I am trying the same thing tonight with Anaconda.

**Comment by spisokgit** [comment]
I had the same issue(after anaconda 3 installed, no script, no prompt, no navigator), I solved, 1.step jdk uninstall, 2.step antivirus, 3. step firewall, 4. anaconda3-5.1.0-windows-x86_64 install
show anaconda navigator and prompt show,

**Comment by mattiasu96** [comment]
I had the same problem: the installation failed during the extraction of the tar.bz2 file.
I solved the problem by disabling temporarely the antivirus (in my case Avast antivirus). The antivirus was somehow blocking the installation of Anaconda.

**Comment by Kartikaysharma007** [comment]
I am still facing this issue. Any permanent solution?

**Comment by ellakumi** [comment]
I had this same issue.  I temporarily disabled Auto-Blocking on my antivirus  and it worked!

**Comment by apupdh1** [comment]
Tried installing on office windows10 64-bit machine. Windows security wouldn't allow me to modify anything on it security system, as usual managed by super-admin (employee can be an admin for this machine to install software). Can't block antivirus etc. 

Any other suggestion how else to install/fix it? It is already been more than 3 hours hanging at the same place. 
Extract: anaconda-2021.05-py38_0.tar.bz2

**Comment by LeaBear** [comment]
Same situation!But waited for 5 minutes or so,it passed.

**Comment by yangqu** [comment]
I had the same issue too.It is still stuck at extracting.I tried 3 categories of installers.Maybe the antivirus software is the block

**Comment by alexmaude5** [comment]
I circumvented this issue by using task manager to end the task _conda which subsequently rebooted and the installation completed
